In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('final_players_ipl_2021.csv')
df

           Player Name
0      Abhishek Sharma
1      Lockie Ferguson
2       Mohammed Siraj
3     Moises Henriques
4  Nathan Coulter-Nile
5         Ravi Bishnoi
6       Mahipal Lomror
7        Glenn Maxwell
8     Jonny Bairstow †

In [2]:
import pandas as pd

# Load DataFrames from CSV files
df2 = pd.read_csv('batting.csv')  # Replace with the actual file name
df3 = pd.read_csv('bowling.csv')  # Replace with the actual file name

df_names = df['Player Name'].tolist()
df2_names = df2['batsmanName'].tolist()
df3_names = df3['bowlerName'].tolist()

# Check names in df against df2 and df3
df['In_df2'] = df['Player Name'].isin(df2_names)  # Adds a boolean column for df2
df['In_df3'] = df['Player Name'].isin(df3_names)  # Adds a boolean column for df3

# Alternatively, to get matching names
matching_in_df2 = df[df['In_df2']]
matching_in_df3 = df[df['In_df3']]

# Print the DataFrame with new columns indicating presence in df2 and df3
print("Original DataFrame with match indicators:")
print(df)

# Print the matching players
print("\nMatching players in df2:")
print(matching_in_df2)

print("\nMatching players in df3:")
print(matching_in_df3)

# Optionally, you can save the updated DataFrame to a new CSV
df

Original DataFrame with match indicators:
           Player Name  In_df2  In_df3
0      Abhishek Sharma    True    True
1      Lockie Ferguson    True    True
2       Mohammed Siraj    True    True
3     Moises Henriques    True    True
4  Nathan Coulter-Nile    True    True
5         Ravi Bishnoi    True    True
6       Mahipal Lomror    True    True
7        Glenn Maxwell    True    True
8     Jonny Bairstow †    True   False

Matching players in df2:
           Player Name  In_df2  In_df3
0      Abhishek Sharma    True    True
1      Lockie Ferguson    True    True
2       Mohammed Siraj    True    True
3     Moises Henriques    True    True
4  Nathan Coulter-Nile    True    True
5         Ravi Bishnoi    True    True
6       Mahipal Lomror    True    True
7        Glenn Maxwell    True    True
8     Jonny Bairstow †    True   False

Matching players in df3:
           Player Name  In_df2  In_df3
0      Abhishek Sharma    True    True
1      Lockie Ferguson    True    True
2       Mohammed Siraj    True    True
3     Moises Henriques    True    True
4  Nathan Coulter-Nile    True    True
5         Ravi Bishnoi    True    True
6       Mahipal Lomror    True    True
7        Glenn Maxwell    True    True

           Player Name  In_df2  In_df3
0      Abhishek Sharma    True    True
1      Lockie Ferguson    True    True
2       Mohammed Siraj    True    True
3     Moises Henriques    True    True
4  Nathan Coulter-Nile    True    True
5         Ravi Bishnoi    True    True
6       Mahipal Lomror    True    True
7        Glenn Maxwell    True    True
8     Jonny Bairstow †    True   False

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

# Load the batting data
batting_df = pd.read_csv('batting.csv')

# Create a mapping of player names to their profile links
player_links = {}
for index, row in batting_df.iterrows():
    player_name = row['batsmanName']  # Adjust if the column name is different
    player_link = row['player_link']  # Adjust if the column name is different
    player_links[player_name] = player_link

# Function to scrape the country and playing role information from player profile
def get_player_info(profile_url):
    try:
        response = requests.get(profile_url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Fetch country information
            country_elem = soup.find('a', title=lambda x: x and "cricket team profile" in x)
            country = country_elem.find('span', class_='ds-text-title-s').text.strip() if country_elem else "Country not found"
            
            # Fetch playing role information using the provided method
            player_details = soup.find('div', class_='ds-grid lg:ds-grid-cols-3 ds-grid-cols-2 ds-gap-4 ds-mb-8')
            playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None
            playing_role = playing_role_elem.find_next('span').text.strip() if playing_role_elem else "Role not found"
            
            return country, playing_role
        else:
            print(f"Failed to retrieve data for URL: {profile_url}")
    except Exception as e:
        print(f"Error fetching information for {profile_url}: {e}")
    return "Country not found", "Role not found"

# Check country and role for each player in df
countries = []
roles = []
for index, row in df.iterrows():
    player_name = row['Player Name']
    if player_name in player_links:
        profile_url = player_links[player_name]
        country, role = get_player_info(profile_url)
        countries.append(country)
        roles.append(role)
        time.sleep(1)  # Add delay to avoid overwhelming the server
    else:
        countries.append("Not Found")
        roles.append("Not Found")

# Add the country and role information to the DataFrame
df['Country'] = countries
df['Role'] = roles

# Print the updated DataFrame
print("Updated DataFrame with country and role information:")
print(df)

C:\Users\kiran\AppData\Local\Temp\ipykernel_13416\3202768010.py:29: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None

Updated DataFrame with country and role information:
           Player Name  In_df2  In_df3      Country                 Role
0      Abhishek Sharma    True    True        India           Allrounder
1      Lockie Ferguson    True    True  New Zealand               Bowler
2       Mohammed Siraj    True    True        India               Bowler
3     Moises Henriques    True    True    Australia           Allrounder
4  Nathan Coulter-Nile    True    True    Australia   Bowling Allrounder
5         Ravi Bishnoi    True    True        India               Bowler
6       Mahipal Lomror    True    True    Rajasthan           Allrounder
7        Glenn Maxwell    True    True    Australia   Batting Allrounder
8     Jonny Bairstow †    True   False      England  Wicketkeeper Batter

In [4]:
df = df.drop(columns=['In_df2', 'In_df3'])
df.to_csv('final_players_ipl_2021_with_info.csv', index=False)
df

           Player Name      Country                 Role
0      Abhishek Sharma        India           Allrounder
1      Lockie Ferguson  New Zealand               Bowler
2       Mohammed Siraj        India               Bowler
3     Moises Henriques    Australia           Allrounder
4  Nathan Coulter-Nile    Australia   Bowling Allrounder
5         Ravi Bishnoi        India               Bowler
6       Mahipal Lomror    Rajasthan           Allrounder
7        Glenn Maxwell    Australia   Batting Allrounder
8     Jonny Bairstow †      England  Wicketkeeper Batter

In [5]:
import pandas as pd


# Select players with country name 'India'
indian_players = df[df['Country'] == 'India']

# Print the result
print("Indian Players:")
print(indian_players)

# Optionally, save the Indian players to a new CSV file
indian_players.to_csv('indian_players.csv', index=False)
print("Indian players saved to indian_players.csv")

Indian Players:
       Player Name Country        Role
0  Abhishek Sharma   India  Allrounder
2   Mohammed Siraj   India      Bowler
5     Ravi Bishnoi   India      Bowler
Indian players saved to indian_players.csv

In [2]:
import pandas as pd
df = pd.read_csv('final_players_ipl_2021_with_info.csv')
df1 = pd.read_csv('final_batting_stats.csv')
df2 = pd.read_csv('final_bowling_stats.csv')
df_batting = df.merge(df1, left_on='Player Name', right_on='batsmanName', how='left')

# Merge the resulting dataframe with df2 (bowling stats) using Player Name and bowlerName
df_combined = df_batting.merge(df2, left_on='Player Name', right_on='bowlerName', how='left')

# Save the combined dataframe to a CSV file
df_combined.to_csv('combined_player_data.csv', index=False)

# Display the combined dataframe
print(df_combined)

           Player Name      Country                 Role          batsmanName  \
0      Abhishek Sharma        India           Allrounder      Abhishek Sharma
1      Lockie Ferguson  New Zealand               Bowler      Lockie Ferguson
2       Mohammed Siraj        India               Bowler       Mohammed Siraj
3     Moises Henriques    Australia           Allrounder     Moises Henriques
4  Nathan Coulter-Nile    Australia   Bowling Allrounder  Nathan Coulter-Nile
5         Ravi Bishnoi        India               Bowler         Ravi Bishnoi
6       Mahipal Lomror    Rajasthan           Allrounder       Mahipal Lomror
7        Glenn Maxwell    Australia   Batting Allrounder        Glenn Maxwell
8       Jonny Bairstow      England  Wicketkeeper Batter       Jonny Bairstow

   inning_batted  Average_SR  Average_Boundary_Percentage  total_runs  \
0              7  114.184286                    35.252050          98
1              3   54.543333                    55.555556          18
2              4   41.427500                    50.000000          20
3              4   95.585000                    12.500000          31
4              2   75.000000                     0.000000           4
5              1   25.000000                     0.000000           1
6              4  127.667500                    35.120078          94
7             14  127.404286                    55.064352         513
8              2  114.900000                    51.212121          67

   batting_average           bowlerName  inningbowled  avg_bowling_economy  \
0        14.000000      Abhishek Sharma           6.0                 6.92
1         6.000000      Lockie Ferguson           8.0                 7.31
2         5.000000       Mohammed Siraj          15.0                 6.72
3         7.750000     Moises Henriques           5.0                 5.60
4         2.000000  Nathan Coulter-Nile           5.0                 6.35
5         1.000000         Ravi Bishnoi           9.0                 6.39
6        23.500000       Mahipal Lomror           4.0                 6.46
7        36.642857        Glenn Maxwell           6.0                 8.79
8        33.500000                  NaN           NaN                  NaN

   avg_bowling_strike  average_bowling_avg  average_dot_ball_%
0                7.50                 7.00               40.28
1               14.00                15.79               42.71
2               14.33                17.08               47.96
3                7.00                 4.50               50.83
4               14.00                14.17               44.17
5               13.33                12.58               40.28
6               18.00                22.00               31.25
7               12.00                14.25               25.93
8                 NaN                  NaN                 NaN

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)