In [1]:
import pandas as pd

# Filter criteria: (typically for openers)
# 1. Batting Average > 30
# 2. Strike Rate > 140
# 3. Innings Batted >= 3
# 4. Boundary % > 50

In [2]:
file_path = "batting.csv"  
df = pd.read_csv(file_path)
print(df.head())

       batsmanName  runs  balls minutes  4s  6s      SR  \
0  Ruturaj Gaikwad    32     27      41   3   1  118.51
1   Faf du Plessis    86     59     104   7   3  145.76
2    Robin Uthappa    31     15      26   0   3  206.66
3        Moeen Ali    37     20      36   2   3  185.00
4     Shubman Gill    51     43      74   6   0  118.60

                                         player_link   match_id
0  https://www.espncricinfo.com/cricketers/rutura...  scorecard
1  https://www.espncricinfo.com/cricketers/faf-du...  scorecard
2  https://www.espncricinfo.com/cricketers/robin-...  scorecard
3  https://www.espncricinfo.com/cricketers/moeen-...  scorecard
4  https://www.espncricinfo.com/cricketers/shubma...  scorecard

In [3]:
df = df.drop(columns=['match_id'])
print(df.head())

       batsmanName  runs  balls minutes  4s  6s      SR  \
0  Ruturaj Gaikwad    32     27      41   3   1  118.51
1   Faf du Plessis    86     59     104   7   3  145.76
2    Robin Uthappa    31     15      26   0   3  206.66
3        Moeen Ali    37     20      36   2   3  185.00
4     Shubman Gill    51     43      74   6   0  118.60

                                         player_link
0  https://www.espncricinfo.com/cricketers/rutura...
1  https://www.espncricinfo.com/cricketers/faf-du...
2  https://www.espncricinfo.com/cricketers/robin-...
3  https://www.espncricinfo.com/cricketers/moeen-...
4  https://www.espncricinfo.com/cricketers/shubma...

In [4]:
df = df.sort_values(by='batsmanName')

print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link
457  https://www.espncricinfo.com/cricketers/ab-de-...
398  https://www.espncricinfo.com/cricketers/ab-de-...
329  https://www.espncricinfo.com/cricketers/ab-de-...
35   https://www.espncricinfo.com/cricketers/ab-de-...
139  https://www.espncricinfo.com/cricketers/ab-de-...
..                                                 ...
213  https://www.espncricinfo.com/cricketers/yashas...
101  https://www.espncricinfo.com/cricketers/yashas...
389  https://www.espncricinfo.com/cricketers/yashas...
463  https://www.espncricinfo.com/cricketers/yuzven...
640  https://www.espncricinfo.com/cricketers/yuzven...

[934 rows x 8 columns]

In [5]:
df.describe()

             runs       balls          4s          6s
count  934.000000  934.000000  934.000000  934.000000
mean    18.967880   14.937901    1.657388    0.735546
std     20.903828   13.659792    2.231117    1.208970
min      0.000000    0.000000    0.000000    0.000000
25%      3.000000    4.000000    0.000000    0.000000
50%     12.000000   10.000000    1.000000    0.000000
75%     28.000000   22.000000    2.000000    1.000000
max    124.000000   64.000000   13.000000    8.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 934 entries, 457 to 640
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   batsmanName  934 non-null    object
 1   runs         934 non-null    int64
 2   balls        934 non-null    int64
 3   minutes      934 non-null    object
 4   4s           934 non-null    int64
 5   6s           934 non-null    int64
 6   SR           934 non-null    object
 7   player_link  934 non-null    object
dtypes: int64(4), object(4)
memory usage: 65.7+ KB

In [7]:
name_counts = df['batsmanName'].value_counts()

# Step 2: Add a new column to the DataFrame that shows how many times each player appears
df['inning_batted'] = df['batsmanName'].map(name_counts)

# Step 3: Display the updated DataFrame
print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

[934 rows x 9 columns]

In [8]:
print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

[934 rows x 9 columns]

In [9]:
df['SR'] = pd.to_numeric(df['SR'], errors='coerce')

df_cleaned = df[(df['SR'] != 0) & (df['SR'].notna())]

print(df_cleaned)

          batsmanName  runs  balls minutes  4s  6s      SR  \
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
279    AB de Villiers     4      1       7   1   0  400.00
..                ...   ...    ...     ...  ..  ..     ...
437  Yashasvi Jaiswal    49     36      74   6   2  136.11
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
279  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
437  https://www.espncricinfo.com/cricketers/yashas...             10
213  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

[823 rows x 9 columns]

In [10]:
df['SR'] = pd.to_numeric(df['SR'], errors='coerce').fillna(0)

df['Average_SR'] = df.groupby('batsmanName')['SR'].transform('mean')

print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted  \
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

     Average_SR
457     148.570
398     148.570
329     148.570
35      148.570
139     148.570
..          ...
213     131.166
101     131.166
389     131.166
463      35.710
640      35.710

[934 rows x 10 columns]

In [11]:
df['boundaries'] = df['4s'] + df['6s']

print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted  \
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

     Average_SR  boundaries
457     148.570           0
398     148.570           1
329     148.570           2
35      148.570           1
139     148.570           2
..          ...         ...
213     131.166           9
101     131.166           0
389     131.166           0
463      35.710           0
640      35.710           0

[934 rows x 11 columns]

In [12]:
df['boundary_runs'] = (df['4s'] * 4) + (df['6s'] * 6)

print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted  \
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

     Average_SR  boundaries  boundary_runs
457     148.570           0              0
398     148.570           1              6
329     148.570           2             10
35      148.570           1              4
139     148.570           2             10
..          ...         ...            ...
213     131.166           9             42
101     131.166           0              0
389     131.166           0              0
463      35.710           0              0
640      35.710           0              0

[934 rows x 12 columns]

In [13]:

df['boundary_percentage'] = (df['boundary_runs'] / df['runs']) * 100

print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted  \
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

     Average_SR  boundaries  boundary_runs  boundary_percentage
457     148.570           0              0                  NaN
398     148.570           1              6            50.000000
329     148.570           2             10            90.909091
35      148.570           1              4            36.363636
139     148.570           2             10            52.631579
..          ...         ...            ...                  ...
213     131.166           9             42            84.000000
101     131.166           0              0                  NaN
389     131.166           0              0             0.000000
463      35.710           0              0             0.000000
640      35.710           0              0             0.000000

[934 rows x 13 columns]

In [14]:
df['Average_Boundary_Percentage'] = df.groupby('batsmanName')['boundary_percentage'].transform('mean')

df

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs,boundary_percentage,Average_Boundary_Percentage
457,AB de Villiers,0,1,4,0,0,0.00,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570,0,0,NaN,64.759382
398,AB de Villiers,12,11,18,0,1,109.09,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570,1,6,50.000000,64.759382
329,AB de Villiers,11,6,20,1,1,183.33,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570,2,10,90.909091,64.759382
35,AB de Villiers,11,9,9,1,0,122.22,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570,1,4,36.363636,64.759382
139,AB de Villiers,19,13,31,1,1,146.15,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570,2,10,52.631579,64.759382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,Yashasvi Jaiswal,50,21,33,6,3,238.09,https://www.espncricinfo.com/cricketers/yashas...,10,131.166,9,42,84.000000,69.687414
101,Yashasvi Jaiswal,0,3,3,0,0,0.00,https://www.espncricinfo.com/cricketers/yashas...,10,131.166,0,0,NaN,69.687414
389,Yashasvi Jaiswal,5,4,8,0,0,125.00,https://www.espncricinfo.com/cricketers/yashas...,10,131.166,0,0,0.000000,69.687414
463,Yuzvendra Chahal,2,6,12,0,0,33.33,https://www.espncricinfo.com/cricketers/yuzven...,2,35.710,0,0,0.000000,0.000000
640,Yuzvendra Chahal,8,21,32,0,0,38.09,https://www.espncricinfo.com/cricketers/yuzven...,2,35.710,0,0,0.000000,0.000000

In [15]:
df['total_runs'] = df.groupby('batsmanName')['runs'].transform('sum')
df['inning_batted'] = df.groupby('batsmanName')['inning_batted'].transform('count')

# Step 2: Calculate batting average for each player and add it to the DataFrame
df['batting_average'] = df['total_runs'] / df['inning_batted']

# Step 3: Display the updated DataFrame with batting averages and other columns
print(df)

          batsmanName  runs  balls minutes  4s  6s      SR  \
457    AB de Villiers     0      1       4   0   0    0.00
398    AB de Villiers    12     11      18   0   1  109.09
329    AB de Villiers    11      6      20   1   1  183.33
35     AB de Villiers    11      9       9   1   0  122.22
139    AB de Villiers    19     13      31   1   1  146.15
..                ...   ...    ...     ...  ..  ..     ...
213  Yashasvi Jaiswal    50     21      33   6   3  238.09
101  Yashasvi Jaiswal     0      3       3   0   0    0.00
389  Yashasvi Jaiswal     5      4       8   0   0  125.00
463  Yuzvendra Chahal     2      6      12   0   0   33.33
640  Yuzvendra Chahal     8     21      32   0   0   38.09

                                           player_link  inning_batted  \
457  https://www.espncricinfo.com/cricketers/ab-de-...              8
398  https://www.espncricinfo.com/cricketers/ab-de-...              8
329  https://www.espncricinfo.com/cricketers/ab-de-...              8
35   https://www.espncricinfo.com/cricketers/ab-de-...              8
139  https://www.espncricinfo.com/cricketers/ab-de-...              8
..                                                 ...            ...
213  https://www.espncricinfo.com/cricketers/yashas...             10
101  https://www.espncricinfo.com/cricketers/yashas...             10
389  https://www.espncricinfo.com/cricketers/yashas...             10
463  https://www.espncricinfo.com/cricketers/yuzven...              2
640  https://www.espncricinfo.com/cricketers/yuzven...              2

     Average_SR  boundaries  boundary_runs  boundary_percentage  \
457     148.570           0              0                  NaN
398     148.570           1              6            50.000000
329     148.570           2             10            90.909091
35      148.570           1              4            36.363636
139     148.570           2             10            52.631579
..          ...         ...            ...                  ...
213     131.166           9             42            84.000000
101     131.166           0              0                  NaN
389     131.166           0              0             0.000000
463      35.710           0              0             0.000000
640      35.710           0              0             0.000000

     Average_Boundary_Percentage  total_runs  batting_average
457                    64.759382         106            13.25
398                    64.759382         106            13.25
329                    64.759382         106            13.25
35                     64.759382         106            13.25
139                    64.759382         106            13.25
..                           ...         ...              ...
213                    69.687414         249            24.90
101                    69.687414         249            24.90
389                    69.687414         249            24.90
463                     0.000000          10             5.00
640                     0.000000          10             5.00

[934 rows x 16 columns]

In [16]:
df.to_csv('processed_batting_stats.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [17]:
columns_to_keep = ['batsmanName', 'inning_batted', 'Average_SR', 'Average_Boundary_Percentage', 'total_runs', 'batting_average']

# Create the new DataFrame with the specified columns
df2 = df[columns_to_keep]

# Display the new DataFrame
df2.head()

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
457,AB de Villiers,8,148.57,64.759382,106,13.25
398,AB de Villiers,8,148.57,64.759382,106,13.25
329,AB de Villiers,8,148.57,64.759382,106,13.25
35,AB de Villiers,8,148.57,64.759382,106,13.25
139,AB de Villiers,8,148.57,64.759382,106,13.25

In [18]:
# Removing duplicate rows from the DataFrame
df2 = df2.drop_duplicates()

# Display the updated DataFrame
print(df2)

           batsmanName  inning_batted  Average_SR  \
457     AB de Villiers              8  148.570000
635   AB de Villiers †              6  112.938333
376        Abdul Samad             10  100.077000
177    Abhishek Sharma              7  114.184286
340         Adam Milne              3   66.666667
..                 ...            ...         ...
459  Wanindu Hasaranga              2   50.000000
584  Washington Sundar              4   66.377500
93   Wriddhiman Saha †              9   82.412222
266   Yashasvi Jaiswal             10  131.166000
463   Yuzvendra Chahal              2   35.710000

     Average_Boundary_Percentage  total_runs  batting_average
457                    64.759382         106        13.250000
635                    30.897661         207        34.500000
376                    39.761812         111        11.100000
177                    35.252050          98        14.000000
340                    20.000000          16         5.333333
..                           ...         ...              ...
459                     0.000000           1         0.500000
584                    26.785714          31         7.750000
93                     41.317088         131        14.555556
266                    69.687414         249        24.900000
463                     0.000000          10         5.000000

[161 rows x 6 columns]

In [19]:
df2.to_csv('final_batting_stats.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [20]:
# for openers
filtered_df2 = df2[
    (df2['batting_average'] > 30) &
    (df2['Average_SR'] >140) &
    (df2['inning_batted'] > 3) &
    (df2['Average_Boundary_Percentage'] > 50)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Evin Lewis,5,165.896000,75.140485,151,30.200000
1,Jonny Bairstow †,5,160.382000,71.310602,181,36.200000
2,Prithvi Shaw,15,141.690667,59.987192,479,31.933333

In [21]:
selected_players = filtered_df2['batsmanName']
selected_players

0          Evin Lewis
1    Jonny Bairstow †
2        Prithvi Shaw
Name: batsmanName, dtype: object

# Filter criteria: (typically for middle order)
# Batting Average > 40
# Strike Rate > 125
# Innings Batted > 3
# Average balls faced by the batter in an innings> 20

In [22]:
df['total_balls'] = df.groupby('batsmanName')['balls'].transform('sum')

df['innings_played'] = df.groupby('batsmanName')['inning_batted'].transform('count')
df['balls_avg'] = df['total_balls'] / df['innings_played']
df.head(10)

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs,boundary_percentage,Average_Boundary_Percentage,total_runs,batting_average,total_balls,innings_played,balls_avg
457,AB de Villiers,0,1,4,0,0,0.00,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,0,0,NaN,64.759382,106,13.25,85,8,10.625
398,AB de Villiers,12,11,18,0,1,109.09,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,1,6,50.000000,64.759382,106,13.25,85,8,10.625
329,AB de Villiers,11,6,20,1,1,183.33,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,2,10,90.909091,64.759382,106,13.25,85,8,10.625
35,AB de Villiers,11,9,9,1,0,122.22,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,1,4,36.363636,64.759382,106,13.25,85,8,10.625
139,AB de Villiers,19,13,31,1,1,146.15,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,2,10,52.631579,64.759382,106,13.25,85,8,10.625
279,AB de Villiers,4,1,7,1,0,400.00,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,1,4,100.000000,64.759382,106,13.25,85,8,10.625
72,AB de Villiers,26,26,26,2,1,100.00,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,3,14,53.846154,64.759382,106,13.25,85,8,10.625
193,AB de Villiers,23,18,30,1,2,127.77,https://www.espncricinfo.com/cricketers/ab-de-...,8,148.570000,3,16,69.565217,64.759382,106,13.25,85,8,10.625
635,AB de Villiers †,4,9,15,0,0,44.44,https://www.espncricinfo.com/cricketers/ab-de-...,6,112.938333,0,0,0.000000,30.897661,207,34.50,126,6,21.000
583,AB de Villiers †,75,42,49,3,5,178.57,https://www.espncricinfo.com/cricketers/ab-de-...,6,112.938333,8,42,56.000000,30.897661,207,34.50,126,6,21.000

In [23]:
# Merge df2 with df to add the balls_avg column
df2 = df2.merge(df[['batsmanName', 'balls_avg']], on='batsmanName', how='left')

# Display the updated df2
print(df2)

          batsmanName  inning_batted  Average_SR  Average_Boundary_Percentage  \
0      AB de Villiers              8     148.570                    64.759382
1      AB de Villiers              8     148.570                    64.759382
2      AB de Villiers              8     148.570                    64.759382
3      AB de Villiers              8     148.570                    64.759382
4      AB de Villiers              8     148.570                    64.759382
..                ...            ...         ...                          ...
929  Yashasvi Jaiswal             10     131.166                    69.687414
930  Yashasvi Jaiswal             10     131.166                    69.687414
931  Yashasvi Jaiswal             10     131.166                    69.687414
932  Yuzvendra Chahal              2      35.710                     0.000000
933  Yuzvendra Chahal              2      35.710                     0.000000

     total_runs  batting_average  balls_avg
0           106            13.25     10.625
1           106            13.25     10.625
2           106            13.25     10.625
3           106            13.25     10.625
4           106            13.25     10.625
..          ...              ...        ...
929         249            24.90     16.800
930         249            24.90     16.800
931         249            24.90     16.800
932          10             5.00     13.500
933          10             5.00     13.500

[934 rows x 7 columns]

In [24]:
# Removing duplicate rows from the DataFrame
df2 = df2.drop_duplicates()

# Display the updated DataFrame
print(df2)

           batsmanName  inning_batted  Average_SR  \
0       AB de Villiers              8  148.570000
8     AB de Villiers †              6  112.938333
14         Abdul Samad             10  100.077000
24     Abhishek Sharma              7  114.184286
31          Adam Milne              3   66.666667
..                 ...            ...         ...
907  Wanindu Hasaranga              2   50.000000
909  Washington Sundar              4   66.377500
913  Wriddhiman Saha †              9   82.412222
922   Yashasvi Jaiswal             10  131.166000
932   Yuzvendra Chahal              2   35.710000

     Average_Boundary_Percentage  total_runs  batting_average  balls_avg
0                      64.759382         106        13.250000  10.625000
8                      30.897661         207        34.500000  21.000000
14                     39.761812         111        11.100000   8.700000
24                     35.252050          98        14.000000  10.714286
31                     20.000000          16         5.333333   5.666667
..                           ...         ...              ...        ...
907                     0.000000           1         0.500000   1.000000
909                    26.785714          31         7.750000  11.750000
913                    41.317088         131        14.555556  15.555556
922                    69.687414         249        24.900000  16.800000
932                     0.000000          10         5.000000  13.500000

[161 rows x 7 columns]

In [25]:

filtered_df2 = df2[
    (df2['batting_average'] > 35) &
    (df2['Average_SR'] > 125) &
    (df2['inning_batted'] > 3) &
    (df2['balls_avg'] > 20)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average,balls_avg
0,Glenn Maxwell,14,127.404286,55.064352,513,36.642857,25.428571
1,Jonny Bairstow †,5,160.382000,71.310602,181,36.200000,24.400000

In [26]:
combined_df = pd.concat([filtered_df2, selected_players])
combined_df.to_csv('selected_players.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

# Filter criteria: (typically for lower order)
# Batting Average > 25
# Strike Rate > 130
# Innings Batted > 3
# Average balls faced by the batter in an innings> 12
# Innings Bowled > 1

In [27]:

filtered_df2 = df2[
    (df2['batting_average'] > 25) &
    (df2['Average_SR'] > 130) &
    (df2['inning_batted'] > 3) &
    (df2['balls_avg'] > 12)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2.to_csv('temp.csv', index=False)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average,balls_avg
0,Evin Lewis,5,165.896000,75.140485,151,30.200000,18.600000
1,Jonny Bairstow †,5,160.382000,71.310602,181,36.200000,24.400000
2,Prithvi Shaw,15,141.690667,59.987192,479,31.933333,20.066667
3,Saurabh Tiwary,4,144.987500,50.000000,115,28.750000,24.250000