In [119]:
import pandas as pd
df = pd.read_csv('bowling.csv')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,match_id
0,Chris Woakes,9.0,0,37,3,4.11,37,3,0,4,1,https://www.espncricinfo.com/cricketers/chris-...,scorecard
1,Jofra Archer,10.0,0,42,1,4.20,33,1,1,5,0,https://www.espncricinfo.com/cricketers/jofra-...,scorecard
2,Liam Plunkett,10.0,0,42,3,4.20,36,4,0,0,0,https://www.espncricinfo.com/cricketers/liam-p...,scorecard
3,Mark Wood,10.0,1,49,1,4.90,33,3,1,2,0,https://www.espncricinfo.com/cricketers/mark-w...,scorecard
4,Adil Rashid,8.0,0,39,0,4.87,15,1,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,scorecard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,Jofra Archer,7.0,1,27,3,3.85,29,4,0,1,0,https://www.espncricinfo.com/cricketers/jofra-...,scorecard
525,Adil Rashid,8.0,0,35,1,4.37,27,4,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,scorecard
526,Moeen Ali,10.0,0,63,1,6.30,28,6,2,0,0,https://www.espncricinfo.com/cricketers/moeen-...,scorecard
527,Liam Plunkett,7.0,0,37,2,5.28,20,1,2,0,0,https://www.espncricinfo.com/cricketers/liam-p...,scorecard
528,Ben Stokes,2.5,0,12,2,4.23,11,2,0,0,0,https://www.espncricinfo.com/cricketers/ben-st...,scorecard

In [120]:
df.describe()

,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls
count,529.000000,529.000000,529.000000,529.000000,529.000000,529.000000,529.000000,529.000000,529.000000,529.000000
mean,7.562760,0.255198,41.637051,1.202268,5.684348,23.185255,3.746692,0.674858,1.141777,0.083176
std,2.706186,0.568338,18.222962,1.266824,1.963850,10.439023,2.474130,1.088921,1.272053,0.314848
min,0.300000,0.000000,1.000000,0.000000,1.330000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,0.000000,29.000000,0.000000,4.400000,16.000000,2.000000,0.000000,0.000000,0.000000
50%,8.300000,0.000000,42.000000,1.000000,5.500000,24.000000,4.000000,0.000000,1.000000,0.000000
75%,10.000000,0.000000,55.000000,2.000000,6.700000,31.000000,5.000000,1.000000,2.000000,0.000000
max,10.000000,3.000000,110.000000,6.000000,21.000000,46.000000,13.000000,11.000000,8.000000,3.000000

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529 entries, 0 to 528
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bowlerName   529 non-null    object
 1   overs        529 non-null    float64
 2   maidens      529 non-null    int64
 3   runs         529 non-null    int64
 4   wickets      529 non-null    int64
 5   economy      529 non-null    float64
 6   dots         529 non-null    int64
 7   fours        529 non-null    int64
 8   sixes        529 non-null    int64
 9   wides        529 non-null    int64
 10  no_balls     529 non-null    int64
 11  bowler_link  529 non-null    object
 12  match_id     529 non-null    object
dtypes: float64(2), int64(8), object(3)
memory usage: 53.9+ KB

In [122]:
df.drop(['match_id'], axis=1, inplace=True)

In [123]:
df = df.sort_values(by='bowlerName')

print(df)

           bowlerName  overs  maidens  runs  wickets  economy  dots  fours  \
376       Aaron Finch    2.0        0    13        1     6.50     4      1
145       Aaron Finch    1.0        0     7        0     7.00     2      1
424        Adam Zampa   10.0        0    58        1     5.80    33      8
384        Adam Zampa    6.0        0    50        0     8.33     6      4
282        Adam Zampa    9.0        0    68        1     7.55    21      5
..                ...    ...      ...   ...      ...      ...   ...    ...
107  Yuzvendra Chahal   10.0        0    50        1     5.00    31      6
390  Yuzvendra Chahal   10.0        0    62        2     6.20    21      3
255  Yuzvendra Chahal   10.0        0    36        2     3.60    41      5
329  Yuzvendra Chahal    7.0        0    53        0     7.57    13      1
28   Yuzvendra Chahal   10.0        0    63        1     6.30    28      5

     sixes  wides  no_balls                                        bowler_link
376      0      1         0  https://www.espncricinfo.com/cricketers/aaron-...
145      0      0         0  https://www.espncricinfo.com/cricketers/aaron-...
424      1      0         0  https://www.espncricinfo.com/cricketers/adam-z...
384      1      0         0  https://www.espncricinfo.com/cricketers/adam-z...
282      3      1         0  https://www.espncricinfo.com/cricketers/adam-z...
..     ...    ...       ...                                                ...
107      0      2         0  https://www.espncricinfo.com/cricketers/yuzven...
390      1      1         0  https://www.espncricinfo.com/cricketers/yuzven...
255      0      0         0  https://www.espncricinfo.com/cricketers/yuzven...
329      3      2         0  https://www.espncricinfo.com/cricketers/yuzven...
28       1      4         0  https://www.espncricinfo.com/cricketers/yuzven...

[529 rows x 12 columns]

In [124]:
name_counts = df['bowlerName'].value_counts()

# Step 2: Add a new column to the DataFrame that shows how many times each player appears
df['inningbowled'] = df['bowlerName'].map(name_counts)

# Step 3: Display the updated DataFrame
print(df)

           bowlerName  overs  maidens  runs  wickets  economy  dots  fours  \
376       Aaron Finch    2.0        0    13        1     6.50     4      1
145       Aaron Finch    1.0        0     7        0     7.00     2      1
424        Adam Zampa   10.0        0    58        1     5.80    33      8
384        Adam Zampa    6.0        0    50        0     8.33     6      4
282        Adam Zampa    9.0        0    68        1     7.55    21      5
..                ...    ...      ...   ...      ...      ...   ...    ...
107  Yuzvendra Chahal   10.0        0    50        1     5.00    31      6
390  Yuzvendra Chahal   10.0        0    62        2     6.20    21      3
255  Yuzvendra Chahal   10.0        0    36        2     3.60    41      5
329  Yuzvendra Chahal    7.0        0    53        0     7.57    13      1
28   Yuzvendra Chahal   10.0        0    63        1     6.30    28      5

     sixes  wides  no_balls  \
376      0      1         0
145      0      0         0
424      1      0         0
384      1      0         0
282      3      1         0
..     ...    ...       ...
107      0      2         0
390      1      1         0
255      0      0         0
329      3      2         0
28       1      4         0

                                           bowler_link  inningbowled
376  https://www.espncricinfo.com/cricketers/aaron-...             2
145  https://www.espncricinfo.com/cricketers/aaron-...             2
424  https://www.espncricinfo.com/cricketers/adam-z...             4
384  https://www.espncricinfo.com/cricketers/adam-z...             4
282  https://www.espncricinfo.com/cricketers/adam-z...             4
..                                                 ...           ...
107  https://www.espncricinfo.com/cricketers/yuzven...             8
390  https://www.espncricinfo.com/cricketers/yuzven...             8
255  https://www.espncricinfo.com/cricketers/yuzven...             8
329  https://www.espncricinfo.com/cricketers/yuzven...             8
28   https://www.espncricinfo.com/cricketers/yuzven...             8

[529 rows x 13 columns]

In [125]:
import pandas as pd

# Load the CSV file and make sure to reference the correct column name
players_to_check_df = pd.read_csv('temp.csv')

# Convert the 'batsmanName' column to a list
players_to_check = players_to_check_df['batsmanName'].tolist()

# Filter the DataFrame to find players who have bowled more than 2 innings
filtered_df = df[df['inningbowled'] > 2]

# Check if the player names are present in the filtered DataFrame
present_players = filtered_df[filtered_df['bowlerName'].isin(players_to_check)]

# Display the result
present_players

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled
113,Carlos Brathwaite,7.0,0,53,0,7.57,15,5,0,1,0,https://www.espncricinfo.com/cricketers/carlos...,7
511,Carlos Brathwaite,4.0,0,14,0,3.50,14,1,0,0,0,https://www.espncricinfo.com/cricketers/carlos...,7
238,Carlos Brathwaite,6.0,0,58,2,9.66,8,3,3,1,0,https://www.espncricinfo.com/cricketers/carlos...,7
177,Carlos Brathwaite,3.0,0,33,0,11.00,0,3,0,2,0,https://www.espncricinfo.com/cricketers/carlos...,7
417,Carlos Brathwaite,10.0,0,67,3,6.70,31,9,1,2,0,https://www.espncricinfo.com/cricketers/carlos...,7
82,Carlos Brathwaite,9.0,0,63,4,7.00,22,3,3,3,1,https://www.espncricinfo.com/cricketers/carlos...,7
363,Carlos Brathwaite,5.0,0,35,0,7.00,11,4,0,1,0,https://www.espncricinfo.com/cricketers/carlos...,7
440,Hardik Pandya,6.0,0,31,0,5.16,16,2,0,0,0,https://www.espncricinfo.com/cricketers/hardik...,9
26,Hardik Pandya,10.0,0,55,1,5.50,29,5,0,5,0,https://www.espncricinfo.com/cricketers/hardik...,9
388,Hardik Pandya,10.0,0,68,0,6.80,24,6,1,2,1,https://www.espncricinfo.com/cricketers/hardik...,9
108,Hardik Pandya,10.0,0,60,3,6.00,26,5,1,2,0,https://www.espncricinfo.com/cricketers/hardik...,9
180,Hardik Pandya,5.0,0,28,1,5.60,13,3,0,0,1,https://www.espncricinfo.com/cricketers/hardik...,9
256,Hardik Pandya,10.0,1,51,2,5.10,32,3,0,2,0,https://www.espncricinfo.com/cricketers/hardik...,9
125,Hardik Pandya,10.0,0,60,0,6.00,22,4,1,1,0,https://www.espncricinfo.com/cricketers/hardik...,9
327,Hardik Pandya,8.0,0,44,2,5.50,21,5,0,1,0,https://www.espncricinfo.com/cricketers/hardik...,9
51,Hardik Pandya,10.0,0,50,1,5.00,25,4,0,1,1,https://www.espncricinfo.com/cricketers/hardik...,9
320,Imad Wasim,10.0,0,49,0,4.90,23,2,0,2,0,https://www.espncricinfo.com/cricketers/imad-w...,5
187,Imad Wasim,3.0,0,17,0,5.66,7,1,0,0,0,https://www.espncricinfo.com/cricketers/imad-w...,5
148,Imad Wasim,10.0,0,48,2,4.80,34,5,1,0,0,https://www.espncricinfo.com/cricketers/imad-w...,5
231,Imad Wasim,10.0,0,48,0,4.80,26,4,0,0,0,https://www.espncricinfo.com/cricketers/imad-w...,5
69,Imad Wasim,6.0,0,26,0,4.33,16,2,0,0,0,https://www.espncricinfo.com/cricketers/imad-w...,5

In [126]:
selected_players =pd.read_csv('selected_players.csv')
selected_players = pd.concat([present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

            bowlerName       batsmanName
113  Carlos Brathwaite               NaN
511  Carlos Brathwaite               NaN
238  Carlos Brathwaite               NaN
177  Carlos Brathwaite               NaN
417  Carlos Brathwaite               NaN
82   Carlos Brathwaite               NaN
363  Carlos Brathwaite               NaN
440      Hardik Pandya               NaN
26       Hardik Pandya               NaN
388      Hardik Pandya               NaN
108      Hardik Pandya               NaN
180      Hardik Pandya               NaN
256      Hardik Pandya               NaN
125      Hardik Pandya               NaN
327      Hardik Pandya               NaN
51       Hardik Pandya               NaN
320         Imad Wasim               NaN
187         Imad Wasim               NaN
148         Imad Wasim               NaN
231         Imad Wasim               NaN
69          Imad Wasim               NaN
0                  NaN      Alex CareyÂ â€
1                  NaN  Avishka Fernando
2                  NaN        Imad Wasim
3                  NaN         Jason Roy
4                  NaN     Jos ButtlerÂ â€
5                  NaN    Kusal PereraÂ â€
6                  NaN        Litton Das
7                  NaN   Shimron Hetmyer

In [127]:
# PARAMETERS
# Batting Average > 15
# Strike Rate > 130
# Innings Batted > 2
# Innings Bowled > 4
# Bowling Economy > 7
# Bowling Strike Rate > 20

In [128]:
df2 = pd.read_csv('final_batting_stats.csv')
df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Aaron FinchÂ (c),10,82.950000,45.162750,507,50.700000
1,Adam Zampa,2,16.665000,0.000000,1,0.500000
2,Adil Rashid,5,76.666000,24.250000,45,9.000000
3,Aftab Alam,3,46.666667,85.714286,14,4.666667
4,Aiden Markram,6,71.123333,53.103898,140,23.333333
...,...,...,...,...,...,...
142,Usman Khawaja,9,90.367778,44.331312,316,35.111111
143,Vijay Shankar,3,81.470000,46.655720,58,19.333333
144,Virat KohliÂ (c),9,83.860000,32.322177,443,49.222222
145,Wahab Riaz,6,132.611667,52.222222,88,14.666667
146,Yuzvendra Chahal,1,100.000000,80.000000,5,5.000000

In [129]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   batsmanName                  147 non-null    object
 1   inning_batted                147 non-null    int64
 2   Average_SR                   147 non-null    float64
 3   Average_Boundary_Percentage  147 non-null    float64
 4   total_runs                   147 non-null    int64
 5   batting_average              147 non-null    float64
dtypes: float64(3), int64(2), object(1)
memory usage: 7.0+ KB

In [130]:
filtered_df2 = df2[
    (df2['batting_average'] > 15) &
    (df2['Average_SR'] > 100) &
    (df2['inning_batted'] > 2)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Alex CareyÂ â€,9,114.805556,43.785348,375,41.666667
1,Avishka Fernando,4,106.320000,63.239142,203,50.750000
2,Carlos Brathwaite,6,117.373333,53.450613,154,25.666667
3,Chris Morris,4,117.307500,51.815476,74,18.500000
4,Colin de Grandhomme,8,105.005000,38.005952,190,23.750000
5,Glenn Maxwell,10,162.965000,62.167038,177,17.700000
6,Hardik Pandya,9,121.186667,45.732020,226,25.111111
7,Imad Wasim,5,112.144000,42.986319,162,32.400000
8,Jason Roy,7,110.357143,68.234728,443,63.285714
9,Jos ButtlerÂ â€,9,126.351111,36.182616,312,34.666667
10,Kusal PereraÂ â€,7,105.311429,45.171151,273,39.000000
11,Lahiru Thirimanne,5,109.870000,41.348847,143,28.600000
12,Litton Das,5,103.928000,46.869439,184,36.800000
13,Mosaddek Hossain,6,101.228333,32.298535,117,19.500000
14,Shimron Hetmyer,8,102.527500,43.485720,257,32.125000

In [131]:
df['avg_bowling_economy'] = df.groupby('bowlerName')['economy'].transform('mean')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Yuzvendra Chahal,10.0,0,50,1,5.00,31,6,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175
390,Yuzvendra Chahal,10.0,0,62,2,6.20,21,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175
255,Yuzvendra Chahal,10.0,0,36,2,3.60,41,5,0,0,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175
329,Yuzvendra Chahal,7.0,0,53,0,7.57,13,1,3,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175
28,Yuzvendra Chahal,10.0,0,63,1,6.30,28,5,1,4,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175

bowling strike rate = avg no of balls required to take a wicket = total run / total wickets

In [132]:
import numpy as np

# Calculate the bowling strike rate and set to 0 if wickets = 0
df['bowling SR'] = np.where(df['wickets'] == 0, 0, (df['overs'] * 6) / df['wickets'])

# Display the updated DataFrame
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,12.0
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,0.0
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,60.0
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,0.0
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Yuzvendra Chahal,10.0,0,50,1,5.00,31,6,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0
390,Yuzvendra Chahal,10.0,0,62,2,6.20,21,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0
255,Yuzvendra Chahal,10.0,0,36,2,3.60,41,5,0,0,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0
329,Yuzvendra Chahal,7.0,0,53,0,7.57,13,1,3,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,0.0
28,Yuzvendra Chahal,10.0,0,63,1,6.30,28,5,1,4,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0

In [133]:
# Step 1: Filter the DataFrame to exclude rows where economy is 0
filtered_df = df[df['bowling SR'] != 0]

# Step 2: Calculate the average economy for each bowler and add it to the original DataFrame
df['avg_bowling_strike'] = df.groupby('bowlerName')['bowling SR'].transform(lambda x: x[x != 0].mean())

# Display the updated DataFrame
df.head(20)

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.750000,12.0,12.000000
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.750000,0.0,12.000000
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,60.0,43.333333
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,0.0,43.333333
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,54.0,43.333333
490,Adam Zampa,8.0,0,60,3,7.50,19,5,3,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,16.0,43.333333
203,Adil Rashid,10.0,0,49,0,4.90,31,5,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667
17,Adil Rashid,10.0,0,54,3,5.40,26,3,1,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,20.0,34.666667
263,Adil Rashid,10.0,0,45,2,4.50,27,3,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,30.0,34.666667
466,Adil Rashid,5.0,0,43,0,8.60,9,3,2,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667
412,Adil Rashid,10.0,0,64,1,6.40,22,5,1,2,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,60.0,34.666667
131,Adil Rashid,6.0,0,40,0,6.66,12,5,0,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667
356,Adil Rashid,10.0,0,61,0,6.10,27,2,3,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667
304,Adil Rashid,10.0,0,66,3,6.60,30,3,4,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,20.0,34.666667
4,Adil Rashid,8.0,0,39,0,4.87,15,1,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667
95,Adil Rashid,5.0,0,30,1,6.00,12,3,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,30.0,34.666667
525,Adil Rashid,8.0,0,35,1,4.37,27,4,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,48.0,34.666667
335,Aftab Alam,5.0,1,16,0,3.20,23,2,0,2,0,https://www.espncricinfo.com/cricketers/aftab-...,3,5.473333,0.0,29.100000
397,Aftab Alam,8.1,0,45,3,5.51,24,6,0,1,0,https://www.espncricinfo.com/cricketers/aftab-...,3,5.473333,16.2,29.100000
248,Aftab Alam,7.0,1,54,1,7.71,19,7,1,0,0,https://www.espncricinfo.com/cricketers/aftab-...,3,5.473333,42.0,29.100000

In [134]:
import numpy as np

# Calculate the bowling strike rate and set to 0 if wickets = 0
df['bowling_avg'] = np.where(df['wickets'] == 0, 0, (df['runs']) / df['wickets'])

# Display the updated DataFrame
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,12.0,12.000000,13.0
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,0.0,12.000000,0.0
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,60.0,43.333333,58.0
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,0.0,43.333333,0.0
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,54.0,43.333333,68.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Yuzvendra Chahal,10.0,0,50,1,5.00,31,6,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0,36.000000,50.0
390,Yuzvendra Chahal,10.0,0,62,2,6.20,21,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0,36.000000,31.0
255,Yuzvendra Chahal,10.0,0,36,2,3.60,41,5,0,0,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0,36.000000,18.0
329,Yuzvendra Chahal,7.0,0,53,0,7.57,13,1,3,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,0.0,36.000000,0.0
28,Yuzvendra Chahal,10.0,0,63,1,6.30,28,5,1,4,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0,36.000000,63.0

In [135]:
# Step 1: Filter the DataFrame to exclude rows where bowling_avg is 0
filtered_df = df[df['bowling_avg'] != 0]

# Step 2: Calculate the average bowling_avg for each bowler and add it to the original DataFrame
df['average_bowling_avg'] = df.groupby('bowlerName')['bowling_avg'].transform(lambda x: x[x != 0].mean())

# Display the updated DataFrame
df.head(20)

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.750000,12.0,12.000000,13.0,13.000000
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.750000,0.0,12.000000,0.0,13.000000
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,60.0,43.333333,58.0,48.666667
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,0.0,43.333333,0.0,48.666667
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,54.0,43.333333,68.0,48.666667
490,Adam Zampa,8.0,0,60,3,7.50,19,5,3,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.295000,16.0,43.333333,20.0,48.666667
203,Adil Rashid,10.0,0,49,0,4.90,31,5,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667,0.0,31.916667
17,Adil Rashid,10.0,0,54,3,5.40,26,3,1,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,20.0,34.666667,18.0,31.916667
263,Adil Rashid,10.0,0,45,2,4.50,27,3,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,30.0,34.666667,22.5,31.916667
466,Adil Rashid,5.0,0,43,0,8.60,9,3,2,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667,0.0,31.916667
412,Adil Rashid,10.0,0,64,1,6.40,22,5,1,2,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,60.0,34.666667,64.0,31.916667
131,Adil Rashid,6.0,0,40,0,6.66,12,5,0,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667,0.0,31.916667
356,Adil Rashid,10.0,0,61,0,6.10,27,2,3,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667,0.0,31.916667
304,Adil Rashid,10.0,0,66,3,6.60,30,3,4,1,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,20.0,34.666667,22.0,31.916667
4,Adil Rashid,8.0,0,39,0,4.87,15,1,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,0.0,34.666667,0.0,31.916667
95,Adil Rashid,5.0,0,30,1,6.00,12,3,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,30.0,34.666667,30.0,31.916667
525,Adil Rashid,8.0,0,35,1,4.37,27,4,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,11,5.854545,48.0,34.666667,35.0,31.916667
335,Aftab Alam,5.0,1,16,0,3.20,23,2,0,2,0,https://www.espncricinfo.com/cricketers/aftab-...,3,5.473333,0.0,29.100000,0.0,34.500000
397,Aftab Alam,8.1,0,45,3,5.51,24,6,0,1,0,https://www.espncricinfo.com/cricketers/aftab-...,3,5.473333,16.2,29.100000,15.0,34.500000
248,Aftab Alam,7.0,1,54,1,7.71,19,7,1,0,0,https://www.espncricinfo.com/cricketers/aftab-...,3,5.473333,42.0,29.100000,54.0,34.500000

In [136]:
# dot ball percentage
df['dot_ball_percentage'] = ((df['dots']) / (df['overs']*6)) *100
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg,dot_ball_percentage
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,12.0,12.000000,13.0,13.000000,33.333333
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,0.0,12.000000,0.0,13.000000,33.333333
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,60.0,43.333333,58.0,48.666667,55.000000
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,0.0,43.333333,0.0,48.666667,16.666667
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,54.0,43.333333,68.0,48.666667,38.888889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Yuzvendra Chahal,10.0,0,50,1,5.00,31,6,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0,36.000000,50.0,32.375000,51.666667
390,Yuzvendra Chahal,10.0,0,62,2,6.20,21,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0,36.000000,31.0,32.375000,35.000000
255,Yuzvendra Chahal,10.0,0,36,2,3.60,41,5,0,0,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0,36.000000,18.0,32.375000,68.333333
329,Yuzvendra Chahal,7.0,0,53,0,7.57,13,1,3,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,0.0,36.000000,0.0,32.375000,30.952381
28,Yuzvendra Chahal,10.0,0,63,1,6.30,28,5,1,4,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0,36.000000,63.0,32.375000,46.666667

In [137]:
df['average_dot_ball_%'] = df.groupby('bowlerName')['dot_ball_percentage'].transform('mean')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg,dot_ball_percentage,average_dot_ball_%
376,Aaron Finch,2.0,0,13,1,6.50,4,1,0,1,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,12.0,12.000000,13.0,13.000000,33.333333,33.333333
145,Aaron Finch,1.0,0,7,0,7.00,2,1,0,0,0,https://www.espncricinfo.com/cricketers/aaron-...,2,6.7500,0.0,12.000000,0.0,13.000000,33.333333,33.333333
424,Adam Zampa,10.0,0,58,1,5.80,33,8,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,60.0,43.333333,58.0,48.666667,55.000000,37.534722
384,Adam Zampa,6.0,0,50,0,8.33,6,4,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,0.0,43.333333,0.0,48.666667,16.666667,37.534722
282,Adam Zampa,9.0,0,68,1,7.55,21,5,3,1,0,https://www.espncricinfo.com/cricketers/adam-z...,4,7.2950,54.0,43.333333,68.0,48.666667,38.888889,37.534722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,Yuzvendra Chahal,10.0,0,50,1,5.00,31,6,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0,36.000000,50.0,32.375000,51.666667,48.720238
390,Yuzvendra Chahal,10.0,0,62,2,6.20,21,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0,36.000000,31.0,32.375000,35.000000,48.720238
255,Yuzvendra Chahal,10.0,0,36,2,3.60,41,5,0,0,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,30.0,36.000000,18.0,32.375000,68.333333,48.720238
329,Yuzvendra Chahal,7.0,0,53,0,7.57,13,1,3,2,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,0.0,36.000000,0.0,32.375000,30.952381,48.720238
28,Yuzvendra Chahal,10.0,0,63,1,6.30,28,5,1,4,0,https://www.espncricinfo.com/cricketers/yuzven...,8,6.0175,60.0,36.000000,63.0,32.375000,46.666667,48.720238

In [138]:
df.fillna(0, inplace=True)
df = df.round(2)
df.to_csv('processed_balling_stats.csv', index=False)

In [139]:
df3 = df[['bowlerName', 'inningbowled', 'avg_bowling_economy', 'avg_bowling_strike', 'average_bowling_avg', 'average_dot_ball_%']].copy()
df3.drop_duplicates(inplace=True)
df3
df3.to_csv('final_bowling_stats.csv', index=False)

In [140]:
# Filter the DataFrame based on the given conditions
filtered_df3 = df3[
    (df3['inningbowled'] > 2) & 
    (df3['avg_bowling_economy'] < 7) & 
    (df3['avg_bowling_strike'] < 30) 
]

# Display the filtered DataFrame
filtered_df3

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
335,Aftab Alam,3,5.47,29.10,34.50,57.10
522,Aiden Markram,3,6.14,24.00,22.00,43.52
416,Andre Russell,4,5.11,23.00,21.50,61.28
201,Ben Stokes,11,4.92,21.38,13.17,50.62
316,Chris Gayle,4,6.02,24.00,18.00,37.36
90,Chris Woakes,11,5.15,27.25,22.08,58.63
58,Dhananjaya de Silva,6,5.65,20.00,15.33,46.57
162,Dwaine Pretorius,3,4.33,19.00,10.92,63.12
375,Glenn Maxwell,8,6.31,0.00,0.00,40.61
494,Gulbadin Naib,9,6.49,28.60,27.43,43.88
430,James Neesham,9,6.22,24.54,22.86,49.37
80,Jason Holder,8,5.78,28.00,22.00,53.28
357,Joe Root,3,5.63,15.00,13.50,36.85
235,Kemar Roach,4,3.61,20.00,12.17,67.22
40,Marcus Stoinis,8,6.04,27.00,26.38,47.48
372,Mitchell Starc,10,5.42,29.09,29.24,58.38
365,Mohammad Amir,8,4.86,29.43,26.62,55.53
178,Mohammed Shami,4,5.26,22.39,23.95,61.76
217,Mustafizur Rahman,8,6.67,27.71,32.69,46.22
150,Shaheen Shah Afridi,5,5.01,24.42,23.18,58.37
311,Sheldon Cottrell,9,5.67,28.00,27.17,55.88
322,Shoaib Malik,3,6.94,18.00,10.00,35.65
456,Suranga Lakmal,3,6.44,0.00,0.00,51.85
343,Thisara Perera,6,5.45,24.00,19.00,46.83

In [141]:
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Alex CareyÂ â€,9,114.805556,43.785348,375,41.666667
1,Avishka Fernando,4,106.320000,63.239142,203,50.750000
2,Carlos Brathwaite,6,117.373333,53.450613,154,25.666667
3,Chris Morris,4,117.307500,51.815476,74,18.500000
4,Colin de Grandhomme,8,105.005000,38.005952,190,23.750000
5,Glenn Maxwell,10,162.965000,62.167038,177,17.700000
6,Hardik Pandya,9,121.186667,45.732020,226,25.111111
7,Imad Wasim,5,112.144000,42.986319,162,32.400000
8,Jason Roy,7,110.357143,68.234728,443,63.285714
9,Jos ButtlerÂ â€,9,126.351111,36.182616,312,34.666667
10,Kusal PereraÂ â€,7,105.311429,45.171151,273,39.000000
11,Lahiru Thirimanne,5,109.870000,41.348847,143,28.600000
12,Litton Das,5,103.928000,46.869439,184,36.800000
13,Mosaddek Hossain,6,101.228333,32.298535,117,19.500000
14,Shimron Hetmyer,8,102.527500,43.485720,257,32.125000

In [142]:
# List of player names to check
players_to_check = filtered_df2['batsmanName'].tolist()

# Check if these names are present in the 'bowlerName' column of filtered_df3
present_players2 = filtered_df3[filtered_df3['bowlerName'].isin(players_to_check)]

# Display the result
present_players2
# Display unique bowler names to verify if players exist

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
375,Glenn Maxwell,8,6.31,0.0,0.0,40.61

In [143]:
selected_players = pd.concat([present_players2['bowlerName'], present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

        bowlerName         bowlerName       batsmanName
375  Glenn Maxwell                NaN               NaN
113            NaN  Carlos Brathwaite               NaN
511            NaN  Carlos Brathwaite               NaN
238            NaN  Carlos Brathwaite               NaN
177            NaN  Carlos Brathwaite               NaN
417            NaN  Carlos Brathwaite               NaN
82             NaN  Carlos Brathwaite               NaN
363            NaN  Carlos Brathwaite               NaN
440            NaN      Hardik Pandya               NaN
26             NaN      Hardik Pandya               NaN
388            NaN      Hardik Pandya               NaN
108            NaN      Hardik Pandya               NaN
180            NaN      Hardik Pandya               NaN
256            NaN      Hardik Pandya               NaN
125            NaN      Hardik Pandya               NaN
327            NaN      Hardik Pandya               NaN
51             NaN      Hardik Pandya               NaN
320            NaN         Imad Wasim               NaN
187            NaN         Imad Wasim               NaN
148            NaN         Imad Wasim               NaN
231            NaN         Imad Wasim               NaN
69             NaN         Imad Wasim               NaN
0              NaN                NaN      Alex CareyÂ â€
1              NaN                NaN  Avishka Fernando
2              NaN                NaN        Imad Wasim
3              NaN                NaN         Jason Roy
4              NaN                NaN     Jos ButtlerÂ â€
5              NaN                NaN    Kusal PereraÂ â€
6              NaN                NaN        Litton Das
7              NaN                NaN   Shimron Hetmyer

In [144]:
# Filter the DataFrame based on the given conditions
filtered_df4 = df3[
    (df3['inningbowled'] > 3) & 
    (df3['avg_bowling_economy'] < 8) & 
    (df3['avg_bowling_strike'] < 16) &
    (df3['average_bowling_avg'] < 25) &
    (df3['average_dot_ball_%'] > 40 ) 
]

# Display the filtered DataFrame
filtered_df4

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
375,Glenn Maxwell,8,6.31,0.0,0.0,40.61
521,Jean-Paul Duminy,4,7.50,12.0,15.0,40.62

In [145]:
selected_players = pd.concat([filtered_df4['bowlerName'],present_players2['bowlerName'], present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

           bowlerName     bowlerName         bowlerName       batsmanName
375     Glenn Maxwell  Glenn Maxwell                NaN               NaN
521  Jean-Paul Duminy            NaN                NaN               NaN
113               NaN            NaN  Carlos Brathwaite               NaN
511               NaN            NaN  Carlos Brathwaite               NaN
238               NaN            NaN  Carlos Brathwaite               NaN
177               NaN            NaN  Carlos Brathwaite               NaN
417               NaN            NaN  Carlos Brathwaite               NaN
82                NaN            NaN  Carlos Brathwaite               NaN
363               NaN            NaN  Carlos Brathwaite               NaN
440               NaN            NaN      Hardik Pandya               NaN
26                NaN            NaN      Hardik Pandya               NaN
388               NaN            NaN      Hardik Pandya               NaN
108               NaN            NaN      Hardik Pandya               NaN
180               NaN            NaN      Hardik Pandya               NaN
256               NaN            NaN      Hardik Pandya               NaN
125               NaN            NaN      Hardik Pandya               NaN
327               NaN            NaN      Hardik Pandya               NaN
51                NaN            NaN      Hardik Pandya               NaN
320               NaN            NaN         Imad Wasim               NaN
187               NaN            NaN         Imad Wasim               NaN
148               NaN            NaN         Imad Wasim               NaN
231               NaN            NaN         Imad Wasim               NaN
69                NaN            NaN         Imad Wasim               NaN
0                 NaN            NaN                NaN      Alex CareyÂ â€
1                 NaN            NaN                NaN  Avishka Fernando
2                 NaN            NaN                NaN        Imad Wasim
3                 NaN            NaN                NaN         Jason Roy
4                 NaN            NaN                NaN     Jos ButtlerÂ â€
5                 NaN            NaN                NaN    Kusal PereraÂ â€
6                 NaN            NaN                NaN        Litton Das
7                 NaN            NaN                NaN   Shimron Hetmyer

In [116]:
# Combine the 'bowlerName' and 'batsmanName' columns, removing NaN values
player_names = selected_players[['bowlerName', 'batsmanName']].stack().dropna().unique()

# Convert to a list if required
player_names_list = list(player_names)

# Print the list of unique player names
player_names_list

['Glenn Maxwell',
 'Jean-Paul Duminy',
 'Carlos Brathwaite',
 'Hardik Pandya',
 'Imad Wasim',
 'Alex Carey\xa0â€ ',
 'Avishka Fernando',
 'Jason Roy',
 'Jos Buttler\xa0â€ ',
 'Kusal Perera\xa0â€ ',
 'Litton Das',
 'Shimron Hetmyer']

In [117]:
df_players = pd.DataFrame(player_names_list, columns=["Player Name"])

# Save the DataFrame to a CSV file
csv_filename = 'final_players_ODI_2024.csv'
df_players.to_csv(csv_filename, index=False)

print(f"Player names saved to {csv_filename}")

Player names saved to final_players_ODI_2024.csv