In [56]:
import pandas as pd

# Filter criteria: (typically for openers)
# 1. Batting Average > 30
# 2. Strike Rate > 140
# 3. Innings Batted >= 3
# 4. Boundary % > 50

In [57]:
file_path = "batting.csv"  
df = pd.read_csv(file_path)
print(df.head())

           batsmanName  runs  balls  minutes  4s  6s      SR  \
0       Martin Guptill    19     18       30   2   1  105.55
1       Henry Nicholls    55     77      123   4   0   71.42
2  Kane Williamson (c)    30     53       77   2   0   56.60
3          Ross Taylor    15     31       47   0   0   48.38
4         Tom Latham †    47     56      104   2   1   83.92

                                         player_link   match_id
0  https://www.espncricinfo.com/cricketers/martin...  scorecard
1  https://www.espncricinfo.com/cricketers/henry-...  scorecard
2  https://www.espncricinfo.com/cricketers/kane-w...  scorecard
3  https://www.espncricinfo.com/cricketers/ross-t...  scorecard
4  https://www.espncricinfo.com/cricketers/tom-la...  scorecard

In [58]:
df = df.drop(columns=['match_id'])
print(df.head())

           batsmanName  runs  balls  minutes  4s  6s      SR  \
0       Martin Guptill    19     18       30   2   1  105.55
1       Henry Nicholls    55     77      123   4   0   71.42
2  Kane Williamson (c)    30     53       77   2   0   56.60
3          Ross Taylor    15     31       47   0   0   48.38
4         Tom Latham †    47     56      104   2   1   83.92

                                         player_link
0  https://www.espncricinfo.com/cricketers/martin...
1  https://www.espncricinfo.com/cricketers/henry-...
2  https://www.espncricinfo.com/cricketers/kane-w...
3  https://www.espncricinfo.com/cricketers/ross-t...
4  https://www.espncricinfo.com/cricketers/tom-la...

In [59]:
df = df.sort_values(by='batsmanName')

print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link
22   https://www.espncricinfo.com/cricketers/aaron-...
627  https://www.espncricinfo.com/cricketers/aaron-...
547  https://www.espncricinfo.com/cricketers/aaron-...
513  https://www.espncricinfo.com/cricketers/aaron-...
581  https://www.espncricinfo.com/cricketers/aaron-...
..                                                 ...
248  https://www.espncricinfo.com/cricketers/wahab-...
714  https://www.espncricinfo.com/cricketers/wahab-...
96   https://www.espncricinfo.com/cricketers/wahab-...
566  https://www.espncricinfo.com/cricketers/wahab-...
55   https://www.espncricinfo.com/cricketers/yuzven...

[812 rows x 8 columns]

In [60]:
df.describe()

             runs       balls     minutes          4s          6s
count  812.000000  812.000000  812.000000  812.000000  812.000000
mean    26.158867   29.674877   44.456897    2.440887    0.439655
std     29.710782   30.548584   43.662384    3.032126    1.090279
min      0.000000    0.000000    1.000000    0.000000    0.000000
25%      4.000000    6.000000   11.000000    0.000000    0.000000
50%     16.000000   18.500000   28.000000    1.000000    0.000000
75%     39.250000   43.000000   64.000000    4.000000    0.000000
max    166.000000  154.000000  216.000000   16.000000   17.000000

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 812 entries, 22 to 55
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   batsmanName  812 non-null    object
 1   runs         812 non-null    int64
 2   balls        812 non-null    int64
 3   minutes      812 non-null    int64
 4   4s           812 non-null    int64
 5   6s           812 non-null    int64
 6   SR           812 non-null    object
 7   player_link  812 non-null    object
dtypes: int64(5), object(3)
memory usage: 57.1+ KB

In [62]:
name_counts = df['batsmanName'].value_counts()

# Step 2: Add a new column to the DataFrame that shows how many times each player appears
df['inning_batted'] = df['batsmanName'].map(name_counts)

# Step 3: Display the updated DataFrame
print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

[812 rows x 9 columns]

In [63]:
print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

[812 rows x 9 columns]

In [64]:
df['SR'] = pd.to_numeric(df['SR'], errors='coerce')

df_cleaned = df[(df['SR'] != 0) & (df['SR'].notna())]

print(df_cleaned)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
420   Aaron Finch (c)    53     51       91   5   2  103.92
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
420  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

[726 rows x 9 columns]

In [65]:
df['SR'] = pd.to_numeric(df['SR'], errors='coerce').fillna(0)

df['Average_SR'] = df.groupby('batsmanName')['SR'].transform('mean')

print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted  \
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

     Average_SR
22    82.950000
627   82.950000
547   82.950000
513   82.950000
581   82.950000
..          ...
248  132.611667
714  132.611667
96   132.611667
566  132.611667
55   100.000000

[812 rows x 10 columns]

In [66]:
df['boundaries'] = df['4s'] + df['6s']

print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted  \
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

     Average_SR  boundaries
22    82.950000           0
627   82.950000           0
547   82.950000          10
513   82.950000          20
581   82.950000           4
..          ...         ...
248  132.611667           2
714  132.611667           1
96   132.611667           0
566  132.611667           5
55   100.000000           1

[812 rows x 11 columns]

In [67]:
df['boundary_runs'] = (df['4s'] * 4) + (df['6s'] * 6)

print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted  \
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

     Average_SR  boundaries  boundary_runs
22    82.950000           0              0
627   82.950000           0              0
547   82.950000          10             48
513   82.950000          20             90
581   82.950000           4             18
..          ...         ...            ...
248  132.611667           2             10
714  132.611667           1              4
96   132.611667           0              0
566  132.611667           5             26
55   100.000000           1              4

[812 rows x 12 columns]

In [68]:

df['boundary_percentage'] = (df['boundary_runs'] / df['runs']) * 100

print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted  \
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

     Average_SR  boundaries  boundary_runs  boundary_percentage
22    82.950000           0              0                  NaN
627   82.950000           0              0             0.000000
547   82.950000          10             48            58.536585
513   82.950000          20             90            58.823529
581   82.950000           4             18            50.000000
..          ...         ...            ...                  ...
248  132.611667           2             10            66.666667
714  132.611667           1              4           100.000000
96   132.611667           0              0             0.000000
566  132.611667           5             26            57.777778
55   100.000000           1              4            80.000000

[812 rows x 13 columns]

In [69]:
df['Average_Boundary_Percentage'] = df.groupby('batsmanName')['boundary_percentage'].transform('mean')

df

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs,boundary_percentage,Average_Boundary_Percentage
22,Aaron Finch (c),0,1,6,0,0,0.00,https://www.espncricinfo.com/cricketers/aaron-...,10,82.950000,0,0,NaN,45.162750
627,Aaron Finch (c),6,10,13,0,0,60.00,https://www.espncricinfo.com/cricketers/aaron-...,10,82.950000,0,0,0.000000,45.162750
547,Aaron Finch (c),82,84,94,6,4,97.61,https://www.espncricinfo.com/cricketers/aaron-...,10,82.950000,10,48,58.536585,45.162750
513,Aaron Finch (c),153,132,176,15,5,115.90,https://www.espncricinfo.com/cricketers/aaron-...,10,82.950000,20,90,58.823529,45.162750
581,Aaron Finch (c),36,35,60,3,1,102.85,https://www.espncricinfo.com/cricketers/aaron-...,10,82.950000,4,18,50.000000,45.162750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,Wahab Riaz,15,9,14,1,1,166.66,https://www.espncricinfo.com/cricketers/wahab-...,6,132.611667,2,10,66.666667,52.222222
714,Wahab Riaz,4,2,4,1,0,200.00,https://www.espncricinfo.com/cricketers/wahab-...,6,132.611667,1,4,100.000000,52.222222
96,Wahab Riaz,2,4,10,0,0,50.00,https://www.espncricinfo.com/cricketers/wahab-...,6,132.611667,0,0,0.000000,52.222222
566,Wahab Riaz,45,39,49,2,3,115.38,https://www.espncricinfo.com/cricketers/wahab-...,6,132.611667,5,26,57.777778,52.222222
55,Yuzvendra Chahal,5,5,8,1,0,100.00,https://www.espncricinfo.com/cricketers/yuzven...,1,100.000000,1,4,80.000000,80.000000

In [70]:
df['total_runs'] = df.groupby('batsmanName')['runs'].transform('sum')
df['inning_batted'] = df.groupby('batsmanName')['inning_batted'].transform('count')

# Step 2: Calculate batting average for each player and add it to the DataFrame
df['batting_average'] = df['total_runs'] / df['inning_batted']

# Step 3: Display the updated DataFrame with batting averages and other columns
print(df)

          batsmanName  runs  balls  minutes  4s  6s      SR  \
22    Aaron Finch (c)     0      1        6   0   0    0.00
627   Aaron Finch (c)     6     10       13   0   0   60.00
547   Aaron Finch (c)    82     84       94   6   4   97.61
513   Aaron Finch (c)   153    132      176  15   5  115.90
581   Aaron Finch (c)    36     35       60   3   1  102.85
..                ...   ...    ...      ...  ..  ..     ...
248        Wahab Riaz    15      9       14   1   1  166.66
714        Wahab Riaz     4      2        4   1   0  200.00
96         Wahab Riaz     2      4       10   0   0   50.00
566        Wahab Riaz    45     39       49   2   3  115.38
55   Yuzvendra Chahal     5      5        8   1   0  100.00

                                           player_link  inning_batted  \
22   https://www.espncricinfo.com/cricketers/aaron-...             10
627  https://www.espncricinfo.com/cricketers/aaron-...             10
547  https://www.espncricinfo.com/cricketers/aaron-...             10
513  https://www.espncricinfo.com/cricketers/aaron-...             10
581  https://www.espncricinfo.com/cricketers/aaron-...             10
..                                                 ...            ...
248  https://www.espncricinfo.com/cricketers/wahab-...              6
714  https://www.espncricinfo.com/cricketers/wahab-...              6
96   https://www.espncricinfo.com/cricketers/wahab-...              6
566  https://www.espncricinfo.com/cricketers/wahab-...              6
55   https://www.espncricinfo.com/cricketers/yuzven...              1

     Average_SR  boundaries  boundary_runs  boundary_percentage  \
22    82.950000           0              0                  NaN
627   82.950000           0              0             0.000000
547   82.950000          10             48            58.536585
513   82.950000          20             90            58.823529
581   82.950000           4             18            50.000000
..          ...         ...            ...                  ...
248  132.611667           2             10            66.666667
714  132.611667           1              4           100.000000
96   132.611667           0              0             0.000000
566  132.611667           5             26            57.777778
55   100.000000           1              4            80.000000

     Average_Boundary_Percentage  total_runs  batting_average
22                     45.162750         507        50.700000
627                    45.162750         507        50.700000
547                    45.162750         507        50.700000
513                    45.162750         507        50.700000
581                    45.162750         507        50.700000
..                           ...         ...              ...
248                    52.222222          88        14.666667
714                    52.222222          88        14.666667
96                     52.222222          88        14.666667
566                    52.222222          88        14.666667
55                     80.000000           5         5.000000

[812 rows x 16 columns]

In [71]:
df.to_csv('processed_batting_stats.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [72]:
columns_to_keep = ['batsmanName', 'inning_batted', 'Average_SR', 'Average_Boundary_Percentage', 'total_runs', 'batting_average']

# Create the new DataFrame with the specified columns
df2 = df[columns_to_keep]

# Display the new DataFrame
df2.head()

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
22,Aaron Finch (c),10,82.95,45.16275,507,50.7
627,Aaron Finch (c),10,82.95,45.16275,507,50.7
547,Aaron Finch (c),10,82.95,45.16275,507,50.7
513,Aaron Finch (c),10,82.95,45.16275,507,50.7
581,Aaron Finch (c),10,82.95,45.16275,507,50.7

In [73]:
# Removing duplicate rows from the DataFrame
df2 = df2.drop_duplicates()

# Display the updated DataFrame
print(df2)

          batsmanName  inning_batted  Average_SR  Average_Boundary_Percentage  \
22    Aaron Finch (c)             10   82.950000                    45.162750
590        Adam Zampa              2   16.665000                     0.000000
19        Adil Rashid              5   76.666000                    24.250000
395        Aftab Alam              3   46.666667                    85.714286
57      Aiden Markram              6   71.123333                    53.103898
..                ...            ...         ...                          ...
299     Usman Khawaja              9   90.367778                    44.331312
379     Vijay Shankar              3   81.470000                    46.655720
378   Virat Kohli (c)              9   83.860000                    32.322177
342        Wahab Riaz              6  132.611667                    52.222222
55   Yuzvendra Chahal              1  100.000000                    80.000000

     total_runs  batting_average
22          507        50.700000
590           1         0.500000
19           45         9.000000
395          14         4.666667
57          140        23.333333
..          ...              ...
299         316        35.111111
379          58        19.333333
378         443        49.222222
342          88        14.666667
55            5         5.000000

[147 rows x 6 columns]

In [74]:
df2.to_csv('final_batting_stats.csv', index=False)

In [75]:
# for openers
filtered_df2 = df2[
    (df2['batting_average'] > 30) &
    (df2['Average_SR'] >140) &
    (df2['inning_batted'] > 3) &
    (df2['Average_Boundary_Percentage'] > 50)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

Empty DataFrame
Columns: [batsmanName, inning_batted, Average_SR, Average_Boundary_Percentage, total_runs, batting_average]
Index: []

In [76]:
selected_players = filtered_df2['batsmanName']
selected_players

Series([], Name: batsmanName, dtype: object)

# Filter criteria: (typically for middle order)
# Batting Average > 40
# Strike Rate > 125
# Innings Batted > 3
# Average balls faced by the batter in an innings> 20

In [77]:
df['total_balls'] = df.groupby('batsmanName')['balls'].transform('sum')

df['innings_played'] = df.groupby('batsmanName')['inning_batted'].transform('count')
df['balls_avg'] = df['total_balls'] / df['innings_played']
df.head(10)

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs,boundary_percentage,Average_Boundary_Percentage,total_runs,batting_average,total_balls,innings_played,balls_avg
22,Aaron Finch (c),0,1,6,0,0,0.00,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,0,0,NaN,45.16275,507,50.7,497,10,49.7
627,Aaron Finch (c),6,10,13,0,0,60.00,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,0,0,0.000000,45.16275,507,50.7,497,10,49.7
547,Aaron Finch (c),82,84,94,6,4,97.61,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,10,48,58.536585,45.16275,507,50.7,497,10,49.7
513,Aaron Finch (c),153,132,176,15,5,115.90,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,20,90,58.823529,45.16275,507,50.7,497,10,49.7
581,Aaron Finch (c),36,35,60,3,1,102.85,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,4,18,50.000000,45.16275,507,50.7,497,10,49.7
420,Aaron Finch (c),53,51,91,5,2,103.92,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,7,32,60.377358,45.16275,507,50.7,497,10,49.7
297,Aaron Finch (c),100,116,144,11,2,86.20,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,13,56,56.000000,45.16275,507,50.7,497,10,49.7
65,Aaron Finch (c),3,4,9,0,0,75.00,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,0,0,0.000000,45.16275,507,50.7,497,10,49.7
757,Aaron Finch (c),66,49,63,6,4,134.69,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,10,48,72.727273,45.16275,507,50.7,497,10,49.7
208,Aaron Finch (c),8,15,19,1,0,53.33,https://www.espncricinfo.com/cricketers/aaron-...,10,82.95,1,4,50.000000,45.16275,507,50.7,497,10,49.7

In [78]:
# Merge df2 with df to add the balls_avg column
df2 = df2.merge(df[['batsmanName', 'balls_avg']], on='batsmanName', how='left')

# Display the updated df2
print(df2)

          batsmanName  inning_batted  Average_SR  Average_Boundary_Percentage  \
0     Aaron Finch (c)             10   82.950000                    45.162750
1     Aaron Finch (c)             10   82.950000                    45.162750
2     Aaron Finch (c)             10   82.950000                    45.162750
3     Aaron Finch (c)             10   82.950000                    45.162750
4     Aaron Finch (c)             10   82.950000                    45.162750
..                ...            ...         ...                          ...
807        Wahab Riaz              6  132.611667                    52.222222
808        Wahab Riaz              6  132.611667                    52.222222
809        Wahab Riaz              6  132.611667                    52.222222
810        Wahab Riaz              6  132.611667                    52.222222
811  Yuzvendra Chahal              1  100.000000                    80.000000

     total_runs  batting_average  balls_avg
0           507        50.700000       49.7
1           507        50.700000       49.7
2           507        50.700000       49.7
3           507        50.700000       49.7
4           507        50.700000       49.7
..          ...              ...        ...
807          88        14.666667       11.5
808          88        14.666667       11.5
809          88        14.666667       11.5
810          88        14.666667       11.5
811           5         5.000000        5.0

[812 rows x 7 columns]

In [79]:
# Removing duplicate rows from the DataFrame
df2 = df2.drop_duplicates()

# Display the updated DataFrame
print(df2)

          batsmanName  inning_batted  Average_SR  Average_Boundary_Percentage  \
0     Aaron Finch (c)             10   82.950000                    45.162750
10         Adam Zampa              2   16.665000                     0.000000
12        Adil Rashid              5   76.666000                    24.250000
17         Aftab Alam              3   46.666667                    85.714286
20      Aiden Markram              6   71.123333                    53.103898
..                ...            ...         ...                          ...
784     Usman Khawaja              9   90.367778                    44.331312
793     Vijay Shankar              3   81.470000                    46.655720
796   Virat Kohli (c)              9   83.860000                    32.322177
805        Wahab Riaz              6  132.611667                    52.222222
811  Yuzvendra Chahal              1  100.000000                    80.000000

     total_runs  batting_average  balls_avg
0           507        50.700000  49.700000
10            1         0.500000   1.500000
12           45         9.000000   7.600000
17           14         4.666667   4.000000
20          140        23.333333  31.000000
..          ...              ...        ...
784         316        35.111111  39.777778
793          58        19.333333  25.000000
796         443        49.222222  52.333333
805          88        14.666667  11.500000
811           5         5.000000   5.000000

[147 rows x 7 columns]

In [80]:

filtered_df2 = df2[
    (df2['batting_average'] > 30) &
    (df2['Average_SR'] > 100) &
    (df2['inning_batted'] > 3) &
    (df2['balls_avg'] > 20)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average,balls_avg
0,Alex Carey †,9,114.805556,43.785348,375,41.666667,40.000000
1,Avishka Fernando,4,106.320000,63.239142,203,50.750000,48.000000
2,Imad Wasim,5,112.144000,42.986319,162,32.400000,27.400000
3,Jason Roy,7,110.357143,68.234728,443,63.285714,54.857143
4,Jos Buttler †,9,126.351111,36.182616,312,34.666667,28.222222
5,Kusal Perera †,7,105.311429,45.171151,273,39.000000,35.142857
6,Litton Das,5,103.928000,46.869439,184,36.800000,33.400000
7,Shimron Hetmyer,8,102.527500,43.485720,257,32.125000,31.625000

In [81]:
combined_df = pd.concat([filtered_df2, selected_players])
combined_df.to_csv('selected_players.csv', index=False)

# Filter criteria: (typically for lower order)
# Batting Average > 25
# Strike Rate > 130
# Innings Batted > 3
# Average balls faced by the batter in an innings> 12
# Innings Bowled > 1

In [82]:

filtered_df2 = df2[
    (df2['batting_average'] > 25) &
    (df2['Average_SR'] > 100) &
    (df2['inning_batted'] > 3) &
    (df2['balls_avg'] > 12)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2.to_csv('temp.csv', index=False)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average,balls_avg
0,Alex Carey †,9,114.805556,43.785348,375,41.666667,40.000000
1,Avishka Fernando,4,106.320000,63.239142,203,50.750000,48.000000
2,Carlos Brathwaite,6,117.373333,53.450613,154,25.666667,24.166667
3,Hardik Pandya,9,121.186667,45.732020,226,25.111111,22.333333
4,Imad Wasim,5,112.144000,42.986319,162,32.400000,27.400000
5,Jason Roy,7,110.357143,68.234728,443,63.285714,54.857143
6,Jos Buttler †,9,126.351111,36.182616,312,34.666667,28.222222
7,Kusal Perera †,7,105.311429,45.171151,273,39.000000,35.142857
8,Lahiru Thirimanne,5,109.870000,41.348847,143,28.600000,32.600000
9,Litton Das,5,103.928000,46.869439,184,36.800000,33.400000
10,Shimron Hetmyer,8,102.527500,43.485720,257,32.125000,31.625000