In [4]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.read_csv('ipl 2020/final_players_ipl_2020_with_info.csv')
df2 = pd.read_csv('ipl 2021/final_players_ipl_2021_with_info.csv')
df3 = pd.read_csv('ipl 2022/final_players_ipl_2022_with_info.csv')
df4 = pd.read_csv('ipl 2023/final_players_ipl_2023_with_info.csv')
df5 = pd.read_csv('ipl 2024/final_players_ipl_2024_with_info.csv')
df6 = pd.read_csv('t20 2022/final_players_details_t20_2024.csv')
df7 = pd.read_csv('t20 2024/final_players_details_t20_2024.csv')
df8 = pd.read_csv('t20 2020/final_players_details_t20_2020.csv')
df9 = pd.read_csv('ODI 2019/final_players_ODI_2019_info.csv')
df10 = pd.read_csv('ODI 2024/final_players_ODI_2024_info.csv')

In [6]:
print(df1)
print(df2)
print(df3)
print(df4)
print(df5)
print(df6)
print(df7)
print(df8)
print(df9)
print(df10)

          Player Name       Country                 Role
0   Bhuvneshwar Kumar         India               Bowler
1        Chris Morris  South Africa   Bowling Allrounder
2      Jasprit Bumrah         India               Bowler
3         Pat Cummins     Australia               Bowler
4         Trent Boult   New Zealand               Bowler
5       Vijay Shankar         India           Allrounder
6          Ben Stokes       England           Allrounder
7      Kieron Pollard   West Indies   Batting Allrounder
8         Chris Gayle   West Indies           Allrounder
9        Ishan Kishan         India  Wicketkeeper Batter
10     Mayank Agarwal         India               Batter
11    Wriddhiman Saha         India  Wicketkeeper Batter
           Player Name      Country                 Role
0      Abhishek Sharma        India           Allrounder
1      Lockie Ferguson  New Zealand               Bowler
2       Mohammed Siraj        India               Bowler
3     Moises Henriques    Australia           Allrounder
4  Nathan Coulter-Nile    Australia   Bowling Allrounder
5         Ravi Bishnoi        India               Bowler
6       Mahipal Lomror    Rajasthan           Allrounder
7        Glenn Maxwell    Australia   Batting Allrounder
8       Jonny Bairstow      England  Wicketkeeper Batter
        Player Name       Country                 Role
0     Glenn Maxwell     Australia   Batting Allrounder
1    Jasprit Bumrah         India               Bowler
2       Tim Southee   New Zealand               Bowler
3     Aiden Markram  South Africa       Opening Batter
4     Andre Russell   West Indies           Allrounder
5  Liam Livingstone       England   Batting Allrounder
6      David Warner     Australia       Opening Batter
7       Jos Buttler       England  Wicketkeeper Batter
8     Rajat Patidar         India     Top order Batter
9  Suryakumar Yadav         India               Batter
         Player Name       Country                 Role
0      Naveen-ul-Haq   Afghanistan               Bowler
1      Cameron Green     Australia   Batting Allrounder
2      Glenn Maxwell     Australia   Batting Allrounder
3   Liam Livingstone       England   Batting Allrounder
4     Faf du Plessis  South Africa  Middle order Batter
5   Heinrich Klaasen  South Africa  Wicketkeeper Batter
6          Jason Roy       England       Opening Batter
7    Quinton de Kock  South Africa  Wicketkeeper Batter
8    Ruturaj Gaikwad         India               Batter
9      Sai Sudharsan         India     Top order Batter
10      Shubman Gill         India       Opening Batter
11  Suryakumar Yadav         India               Batter
12       Virat Kohli         India     Top order Batter
13  Yashasvi Jaiswal         India       Opening Batter
        Player Name      Country                 Role
0    Jasprit Bumrah        India               Bowler
1   Abhishek Sharma        India           Allrounder
2      Sunil Narine  West Indies   Bowling Allrounder
3      Sanju Samson        India  Wicketkeeper Batter
4        Will Jacks      England   Batting Allrounder
5          KL Rahul        India  Wicketkeeper Batter
6       Riyan Parag        India     Top order Batter
7     Sai Sudharsan        India     Top order Batter
8      Shubman Gill        India       Opening Batter
9       Virat Kohli        India     Top order Batter
10   Arshdeep Singh        India               Bowler
            Player Name                Role      Country
0        Arshdeep Singh              Bowler        India
1   Blessing Muzarabani              Bowler     Zimbabwe
2       Richard Ngarava              Bowler     Zimbabwe
3   Shaheen Shah Afridi              Bowler     Pakistan
4          Taskin Ahmed              Bowler   Bangladesh
5           Shadab Khan          Allrounder     Pakistan
6        Marcus Stoinis  Batting Allrounder    Australia
7            Alex Hales      Opening Batter      England
8        Glenn Phillips          Allrounder  New Zealand
9      Suryakumar Yadav              Batter        India
10          Virat Kohli    Top order Batter        India
         Player Name                 Role       Country
0     Arshdeep Singh               Bowler         India
1   Fazalhaq Farooqi               Bowler   Afghanistan
2      Kagiso Rabada               Bowler  South Africa
3       Taskin Ahmed               Bowler    Bangladesh
4         Axar Patel           Allrounder         India
5      Gareth Delany   Batting Allrounder       Ireland
6     Marcus Stoinis   Batting Allrounder     Australia
7        Harry Brook               Batter       England
8        Jos Buttler  Wicketkeeper Batter       England
9       Rohit Sharma     Top order Batter         India
10       Travis Head               Batter     Australia
11    Glenn Phillips          New Zealand    Allrounder
            Player Name                 Role      Country
0   Chamika Karunaratne   Bowling Allrounder    Sri Lanka
1          Taskin Ahmed               Bowler   Bangladesh
2     Ruben Trumpelmann               Bowler      Namibia
3           Karim Janat   Bowling Allrounder  Afghanistan
4     Wanindu Hasaranga           Allrounder    Sri Lanka
5        Mitchell Marsh           Allrounder    Australia
6           Jos Buttler         Wicketkeeper      England
7              KL Rahul  Wicketkeeper Batter        India
8      Charith Asalanka   Batting Allrounder    Sri Lanka
9          David Warner       Opening Batter    Australia
10          Travis Head               Batter    Australia
          Player Name       Country                 Role
0       Glenn Maxwell     Australia   Batting Allrounder
1    Jean-Paul Duminy  South Africa   Batting Allrounder
2   Carlos Brathwaite   West Indies           Allrounder
3       Hardik Pandya         India           Allrounder
4          Imad Wasim      Pakistan           Allrounder
5          Alex Carey     Australia  Wicketkeeper Batter
6    Avishka Fernando     Sri Lanka       Opening Batter
7           Jason Roy       England       Opening Batter
8         Jos Buttler       England  Wicketkeeper Batter
9        Kusal Perera     Sri Lanka  Wicketkeeper Batter
10         Litton Das    Bangladesh  Wicketkeeper Batter
11    Shimron Hetmyer   West Indies  Middle order Batter
12   Heinrich Klaasen  South Africa  Wicketkeeper Batter
        Player Name             Country                 Role
0    Mohammed Shami               India               Bowler
1       Travis Head           Australia     Top order Batter
2     Aiden Markram        South Africa       Opening Batter
3     Glenn Maxwell           Australia   Batting Allrounder
4      David Warner           Australia       Opening Batter
5    Glenn Phillips         New Zealand           Allrounder
6      David Miller        South Africa  Middle order Batter
7  Heinrich Klaasen        South Africa  Wicketkeeper Batter
8      Rohit Sharma               India     Top order Batter
9    Marcus Stoinis  Batting Allrounder            Australia

In [7]:
# Concatenate all DataFrames
all_players_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8,df9,df10])

# Count occurrences of each player
player_counts = all_players_df['Player Name'].value_counts()

# Display the result
print("Number of times each player appears across all DataFrames:")
player_counts

Number of times each player appears across all DataFrames:

Glenn Maxwell       5
Jos Buttler         4
Arshdeep Singh      3
David Warner        3
Suryakumar Yadav    3
                   ..
Chris Morris        1
Sunil Narine        1
Sanju Samson        1
Will Jacks          1
David Miller        1
Name: Player Name, Length: 78, dtype: int64

In [8]:
# Convert player_counts to DataFrame
player_counts_df = player_counts.reset_index()
player_counts_df.columns = ['Player Name', 'Count']  # Rename columns for clarity

# Save to CSV file
player_counts_df.to_csv('player_appearance_counts.csv', index=False)

print("Player counts saved to 'player_appearance_counts.csv'")
player_counts_df

Player counts saved to 'player_appearance_counts.csv'

         Player Name  Count
0      Glenn Maxwell      5
1        Jos Buttler      4
2     Arshdeep Singh      3
3       David Warner      3
4   Suryakumar Yadav      3
..               ...    ...
73      Chris Morris      1
74      Sunil Narine      1
75      Sanju Samson      1
76        Will Jacks      1
77      David Miller      1

[78 rows x 2 columns]

In [9]:
filtered_players_df = player_counts_df[player_counts_df["Count"] >= 3]

# Merge filtered_players_df with all_players_df to get additional details
players_with_details = pd.merge(filtered_players_df, all_players_df, on="Player Name", how="left")
players_with_details = players_with_details.drop_duplicates(subset="Player Name")

# Display the result
players_with_details

         Player Name  Count       Country                 Role
0      Glenn Maxwell      5     Australia   Batting Allrounder
5        Jos Buttler      4       England  Wicketkeeper Batter
9     Arshdeep Singh      3         India               Bowler
12      David Warner      3     Australia       Opening Batter
15  Suryakumar Yadav      3         India               Batter
18  Heinrich Klaasen      3  South Africa  Wicketkeeper Batter
21    Glenn Phillips      3   New Zealand           Allrounder
24       Virat Kohli      3         India     Top order Batter
27    Marcus Stoinis      3     Australia   Batting Allrounder
30      Taskin Ahmed      3    Bangladesh               Bowler
33    Jasprit Bumrah      3         India               Bowler
36       Travis Head      3     Australia               Batter

# now we have 2 Top order batsman 2 middle order batsman 2 batting allrounder 1 allrounder 2 wicketkeeper Batter and 3 bowler 
# in this team we consider 1 extra player abhishek sharma

In [12]:
import pandas as pd
df1 = pd.read_csv('ipl 2020/combined_player_data.csv')
df2 = pd.read_csv('ipl 2021/combined_player_data.csv')
df3 = pd.read_csv('ipl 2022/combined_player_data.csv')
df4 = pd.read_csv('ipl 2023/combined_player_data.csv')
df5 = pd.read_csv('ipl 2024/combined_player_data.csv')
df6 = pd.read_csv('t20 2022/combined_player_data.csv')
df7 = pd.read_csv('t20 2024/combined_player_data.csv')
df8 = pd.read_csv('t20 2020/combined_player_data.csv')
df9 = pd.read_csv('ODI 2019/combined_player_data.csv')
df10 = pd.read_csv('ODI 2024/combined_player_data.csv')
df10 = pd.read_csv('ODI 2024/combined_player_data.csv')
players_with_details

         Player Name  Count       Country                 Role
0      Glenn Maxwell      5     Australia   Batting Allrounder
5        Jos Buttler      4       England  Wicketkeeper Batter
9     Arshdeep Singh      3         India               Bowler
12      David Warner      3     Australia       Opening Batter
15  Suryakumar Yadav      3         India               Batter
18  Heinrich Klaasen      3  South Africa  Wicketkeeper Batter
21    Glenn Phillips      3   New Zealand           Allrounder
24       Virat Kohli      3         India     Top order Batter
27    Marcus Stoinis      3     Australia   Batting Allrounder
30      Taskin Ahmed      3    Bangladesh               Bowler
33    Jasprit Bumrah      3         India               Bowler
36       Travis Head      3     Australia               Batter

In [41]:
all_data = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10], ignore_index=True)

# Filter rows for the specified players
filtered_data = all_data[all_data['Player Name'].isin(players_with_details['Player Name'])]
filtered_data = filtered_data.sort_values(by='Player Name', ascending=True)
# Display the filtered dataframe
batsman_table = filtered_data[
    ['batsmanName', 'inning_batted', 'Average_SR', 'Average_Boundary_Percentage', 'total_runs', 'batting_average']
].dropna(subset=['batsmanName'])  # Drop rows where batsmanName is NaN
specific_players = [
    "Glenn Maxwell", "Jos Buttler", "David Warner",
    "Suryakumar Yadav", "Heinrich Klaasen", "Glenn Phillips", "Virat Kohli",
    "Marcus Stoinis", "Travis Head"
]
# Filter the batsman_table for the specific players
filtered_batsman_table = batsman_table[batsman_table['batsmanName'].isin(specific_players)]


average_stats = filtered_batsman_table.groupby('batsmanName').mean(numeric_only=True).reset_index()

# Display the resulting averages table
print("Average Stats for batsman:")
average_stats

Average Stats for batsman:

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,David Warner,10.000000,124.000602,60.686703,418.666667,41.974026
1,Glenn Maxwell,12.000000,145.685786,60.195534,358.200000,30.102515
2,Glenn Phillips,5.333333,124.623148,59.993066,181.333333,33.622222
3,Heinrich Klaasen,10.000000,123.195000,51.179057,373.000000,37.300000
4,Jos Buttler,17.000000,128.744118,60.396760,863.000000,50.764706
5,Marcus Stoinis,4.666667,138.954167,54.491348,127.333333,27.566667
6,Suryakumar Yadav,9.666667,158.564278,59.987820,368.000000,38.391667
7,Travis Head,6.500000,120.003571,71.226581,292.000000,45.630952
8,Virat Kohli,10.666667,137.169848,53.269785,521.000000,48.850505

In [40]:
# Table for bowler details
bowler_table = filtered_data[
    ['bowlerName', 'inningbowled', 'avg_bowling_economy', 'avg_bowling_strike', 'average_bowling_avg', 'average_dot_ball_%']
].dropna(subset=['bowlerName'])  # Drop rows where bowlerName is NaN
bowler_table
average_stats = bowler_table.groupby('bowlerName').mean(numeric_only=True).reset_index()

# Display the resulting averages table
print("Average Stats for bowlers:")
average_stats

Average Stats for bowlers:

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
0,Arshdeep Singh,9.333333,8.276667,12.563333,18.023333,45.480000
1,Glenn Maxwell,7.800000,7.082000,16.712000,16.516000,37.998000
2,Glenn Phillips,5.500000,7.355000,6.835000,5.640000,36.200000
3,Jasprit Bumrah,14.000000,6.810000,13.436667,14.806667,46.900000
4,Marcus Stoinis,5.333333,8.156667,13.500000,18.880000,32.876667
5,Taskin Ahmed,5.333333,7.343333,13.483333,17.176667,56.543333
6,Travis Head,5.000000,4.460000,15.000000,10.500000,49.560000