In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('final_players_ipl_2022.csv')
df

        Player Name
0     Glenn Maxwell
1    Jasprit Bumrah
2       Tim Southee
3     Aiden Markram
4     Andre Russell
5  Liam Livingstone
6      David Warner
7       Jos Buttler
8     Rajat Patidar
9  Suryakumar Yadav

In [2]:
import pandas as pd

df2 = pd.read_csv('batting.csv')  # Replace with the actual file name
df3 = pd.read_csv('bowling.csv')  # Replace with the actual file name

df_names = df['Player Name'].tolist()
df2_names = df2['batsmanName'].tolist()
df3_names = df3['bowlerName'].tolist()

# Check names in df against df2 and df3
df['In_df2'] = df['Player Name'].isin(df2_names)  # Adds a boolean column for df2
df['In_df3'] = df['Player Name'].isin(df3_names)  # Adds a boolean column for df3

# Alternatively, to get matching names
matching_in_df2 = df[df['In_df2']]
matching_in_df3 = df[df['In_df3']]

# Print the DataFrame with new columns indicating presence in df2 and df3
print("Original DataFrame with match indicators:")
print(df)

# Print the matching players
print("\nMatching players in df2:")
print(matching_in_df2)

print("\nMatching players in df3:")
print(matching_in_df3)

# Optionally, you can save the updated DataFrame to a new CSV
df

Original DataFrame with match indicators:
        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True
6      David Warner    True   False
7       Jos Buttler    True   False
8     Rajat Patidar    True   False
9  Suryakumar Yadav    True   False

Matching players in df2:
        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True
6      David Warner    True   False
7       Jos Buttler    True   False
8     Rajat Patidar    True   False
9  Suryakumar Yadav    True   False

Matching players in df3:
        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True

        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True
6      David Warner    True   False
7       Jos Buttler    True   False
8     Rajat Patidar    True   False
9  Suryakumar Yadav    True   False

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

# Load the batting data
batting_df = pd.read_csv('batting.csv')

# Create a mapping of player names to their profile links
player_links = {}
for index, row in batting_df.iterrows():
    player_name = row['batsmanName']  # Adjust if the column name is different
    player_link = row['player_link']  # Adjust if the column name is different
    player_links[player_name] = player_link

# Function to scrape the country and playing role information from player profile
def get_player_info(profile_url):
    try:
        response = requests.get(profile_url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Fetch country information
            country_elem = soup.find('a', title=lambda x: x and "cricket team profile" in x)
            country = country_elem.find('span', class_='ds-text-title-s').text.strip() if country_elem else "Country not found"
            
            # Fetch playing role information using the provided method
            player_details = soup.find('div', class_='ds-grid lg:ds-grid-cols-3 ds-grid-cols-2 ds-gap-4 ds-mb-8')
            playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None
            playing_role = playing_role_elem.find_next('span').text.strip() if playing_role_elem else "Role not found"
            
            return country, playing_role
        else:
            print(f"Failed to retrieve data for URL: {profile_url}")
    except Exception as e:
        print(f"Error fetching information for {profile_url}: {e}")
    return "Country not found", "Role not found"

# Check country and role for each player in df
countries = []
roles = []
for index, row in df.iterrows():
    player_name = row['Player Name']
    if player_name in player_links:
        profile_url = player_links[player_name]
        country, role = get_player_info(profile_url)
        countries.append(country)
        roles.append(role)
        time.sleep(1)  # Add delay to avoid overwhelming the server
    else:
        countries.append("Not Found")
        roles.append("Not Found")

# Add the country and role information to the DataFrame
df['Country'] = countries
df['Role'] = roles

# Print the updated DataFrame
print("Updated DataFrame with country and role information:")
print(df)

C:\Users\kiran\AppData\Local\Temp\ipykernel_23088\3202768010.py:29: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None

Updated DataFrame with country and role information:
        Player Name  In_df2  In_df3       Country                 Role
0     Glenn Maxwell    True    True     Australia   Batting Allrounder
1    Jasprit Bumrah    True    True         India               Bowler
2       Tim Southee    True    True   New Zealand               Bowler
3     Aiden Markram    True    True  South Africa       Opening Batter
4     Andre Russell    True    True   West Indies           Allrounder
5  Liam Livingstone    True    True       England   Batting Allrounder
6      David Warner    True   False     Australia       Opening Batter
7       Jos Buttler    True   False       England  Wicketkeeper Batter
8     Rajat Patidar    True   False         India     Top order Batter
9  Suryakumar Yadav    True   False         India               Batter

In [4]:
df = df.drop(columns=['In_df2', 'In_df3'])
df.to_csv('final_players_ipl_2022_with_info.csv', index=False)
df

        Player Name       Country                 Role
0     Glenn Maxwell     Australia   Batting Allrounder
1    Jasprit Bumrah         India               Bowler
2       Tim Southee   New Zealand               Bowler
3     Aiden Markram  South Africa       Opening Batter
4     Andre Russell   West Indies           Allrounder
5  Liam Livingstone       England   Batting Allrounder
6      David Warner     Australia       Opening Batter
7       Jos Buttler       England  Wicketkeeper Batter
8     Rajat Patidar         India     Top order Batter
9  Suryakumar Yadav         India               Batter

In [5]:
import pandas as pd

# Select players with country name 'India'
indian_players = df[df['Country'] == 'India']

# Print the result
print("Indian Players:")
print(indian_players)

# Optionally, save the Indian players to a new CSV file
indian_players.to_csv('indian_players.csv', index=False)
print("Indian players saved to indian_players.csv")

Indian Players:
        Player Name Country              Role
1    Jasprit Bumrah   India            Bowler
8     Rajat Patidar   India  Top order Batter
9  Suryakumar Yadav   India            Batter
Indian players saved to indian_players.csv

In [1]:
import pandas as pd
df = pd.read_csv('final_players_ipl_2022_with_info.csv')
df1 = pd.read_csv('final_batting_stats.csv')
df2 = pd.read_csv('final_bowling_stats.csv')
df_batting = df.merge(df1, left_on='Player Name', right_on='batsmanName', how='left')

# Merge the resulting dataframe with df2 (bowling stats) using Player Name and bowlerName
df_combined = df_batting.merge(df2, left_on='Player Name', right_on='bowlerName', how='left')

# Save the combined dataframe to a CSV file
df_combined.to_csv('combined_player_data.csv', index=False)

# Display the combined dataframe
print(df_combined)

        Player Name       Country                 Role       batsmanName  \
0     Glenn Maxwell     Australia   Batting Allrounder     Glenn Maxwell
1    Jasprit Bumrah         India               Bowler    Jasprit Bumrah
2       Tim Southee   New Zealand               Bowler       Tim Southee
3     Aiden Markram  South Africa       Opening Batter     Aiden Markram
4     Andre Russell   West Indies           Allrounder     Andre Russell
5  Liam Livingstone       England   Batting Allrounder  Liam Livingstone
6      David Warner     Australia       Opening Batter      David Warner
7       Jos Buttler       England  Wicketkeeper Batter       Jos Buttler
8     Rajat Patidar         India     Top order Batter     Rajat Patidar
9  Suryakumar Yadav         India               Batter  Suryakumar Yadav

   inning_batted  Average_SR  Average_Boundary_Percentage  total_runs  \
0             13  168.696154                    67.066195         301
1              6    0.000000                          NaN           0
2              5   24.000000                     0.000000           2
3             12  131.062500                    46.137827         381
4             12  143.687500                    70.734447         335
5             14  167.060714                    57.456103         437
6             12  125.515833                    60.034301         432
7             17  128.744118                    60.396760         863
8              7  142.585714                    57.929591         333
9              8  138.737500                    57.966489         303

   batting_average        bowlerName  inningbowled  avg_bowling_economy  \
0        23.153846     Glenn Maxwell          10.0                 6.93
1         0.000000    Jasprit Bumrah          14.0                 7.22
2         0.400000       Tim Southee           9.0                 7.73
3        31.750000     Aiden Markram           4.0                10.00
4        27.916667     Andre Russell          13.0                 9.39
5        31.214286  Liam Livingstone          12.0                10.78
6        36.000000               NaN           NaN                  NaN
7        50.764706               NaN           NaN                  NaN
8        47.571429               NaN           NaN                  NaN
9        37.875000               NaN           NaN                  NaN

   avg_bowling_strike  average_bowling_avg  average_dot_ball_%
0               14.40                16.00               42.78
1               15.83                17.00               43.65
2               13.43                15.02               45.06
3                6.00                 8.00               25.00
4                8.96                15.45               45.62
5               10.27                12.17               22.93
6                 NaN                  NaN                 NaN
7                 NaN                  NaN                 NaN
8                 NaN                  NaN                 NaN
9                 NaN                  NaN                 NaN

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)