In [6]:
import pandas as pd
import numpy as np
df=pd.read_csv('final_players_ipl_2023.csv')
df

           Player Name
0        Naveen-ul-Haq
1        Cameron Green
2        Glenn Maxwell
3     Liam Livingstone
4   Faf du Plessis (c)
5   Heinrich Klaasen †
6            Jason Roy
7    Quinton de Kock †
8      Ruturaj Gaikwad
9        Sai Sudharsan
10        Shubman Gill
11    Suryakumar Yadav
12         Virat Kohli
13    Yashasvi Jaiswal

In [7]:
import pandas as pd

# Load DataFrames from CSV files
df2 = pd.read_csv('batting.csv')  # Replace with the actual file name
df3 = pd.read_csv('bowling.csv')  # Replace with the actual file name

df_names = df['Player Name'].tolist()
df2_names = df2['batsmanName'].tolist()
df3_names = df3['bowlerName'].tolist()

# Check names in df against df2 and df3
df['In_df2'] = df['Player Name'].isin(df2_names)  # Adds a boolean column for df2
df['In_df3'] = df['Player Name'].isin(df3_names)  # Adds a boolean column for df3

# Alternatively, to get matching names
matching_in_df2 = df[df['In_df2']]
matching_in_df3 = df[df['In_df3']]

# Print the DataFrame with new columns indicating presence in df2 and df3
print("Original DataFrame with match indicators:")
print(df)

# Print the matching players
print("\nMatching players in df2:")
print(matching_in_df2)

print("\nMatching players in df3:")
print(matching_in_df3)

# Optionally, you can save the updated DataFrame to a new CSV
df

Original DataFrame with match indicators:
           Player Name  In_df2  In_df3
0        Naveen-ul-Haq    True    True
1        Cameron Green    True    True
2        Glenn Maxwell    True    True
3     Liam Livingstone    True    True
4   Faf du Plessis (c)    True   False
5   Heinrich Klaasen †    True   False
6            Jason Roy    True   False
7    Quinton de Kock †    True   False
8      Ruturaj Gaikwad    True   False
9        Sai Sudharsan    True   False
10        Shubman Gill    True   False
11    Suryakumar Yadav    True   False
12         Virat Kohli    True   False
13    Yashasvi Jaiswal    True   False

Matching players in df2:
           Player Name  In_df2  In_df3
0        Naveen-ul-Haq    True    True
1        Cameron Green    True    True
2        Glenn Maxwell    True    True
3     Liam Livingstone    True    True
4   Faf du Plessis (c)    True   False
5   Heinrich Klaasen †    True   False
6            Jason Roy    True   False
7    Quinton de Kock †    True   False
8      Ruturaj Gaikwad    True   False
9        Sai Sudharsan    True   False
10        Shubman Gill    True   False
11    Suryakumar Yadav    True   False
12         Virat Kohli    True   False
13    Yashasvi Jaiswal    True   False

Matching players in df3:
        Player Name  In_df2  In_df3
0     Naveen-ul-Haq    True    True
1     Cameron Green    True    True
2     Glenn Maxwell    True    True
3  Liam Livingstone    True    True

           Player Name  In_df2  In_df3
0        Naveen-ul-Haq    True    True
1        Cameron Green    True    True
2        Glenn Maxwell    True    True
3     Liam Livingstone    True    True
4   Faf du Plessis (c)    True   False
5   Heinrich Klaasen †    True   False
6            Jason Roy    True   False
7    Quinton de Kock †    True   False
8      Ruturaj Gaikwad    True   False
9        Sai Sudharsan    True   False
10        Shubman Gill    True   False
11    Suryakumar Yadav    True   False
12         Virat Kohli    True   False
13    Yashasvi Jaiswal    True   False

In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

# Load the batting data
batting_df = pd.read_csv('batting.csv')

# Create a mapping of player names to their profile links
player_links = {}
for index, row in batting_df.iterrows():
    player_name = row['batsmanName']  # Adjust if the column name is different
    player_link = row['player_link']  # Adjust if the column name is different
    player_links[player_name] = player_link

# Function to scrape the country and playing role information from player profile
def get_player_info(profile_url):
    try:
        response = requests.get(profile_url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Fetch country information
            country_elem = soup.find('a', title=lambda x: x and "cricket team profile" in x)
            country = country_elem.find('span', class_='ds-text-title-s').text.strip() if country_elem else "Country not found"
            
            # Fetch playing role information using the provided method
            player_details = soup.find('div', class_='ds-grid lg:ds-grid-cols-3 ds-grid-cols-2 ds-gap-4 ds-mb-8')
            playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None
            playing_role = playing_role_elem.find_next('span').text.strip() if playing_role_elem else "Role not found"
            
            return country, playing_role
        else:
            print(f"Failed to retrieve data for URL: {profile_url}")
    except Exception as e:
        print(f"Error fetching information for {profile_url}: {e}")
    return "Country not found", "Role not found"

# Check country and role for each player in df
countries = []
roles = []
for index, row in df.iterrows():
    player_name = row['Player Name']
    if player_name in player_links:
        profile_url = player_links[player_name]
        country, role = get_player_info(profile_url)
        countries.append(country)
        roles.append(role)
        time.sleep(1)  # Add delay to avoid overwhelming the server
    else:
        countries.append("Not Found")
        roles.append("Not Found")

# Add the country and role information to the DataFrame
df['Country'] = countries
df['Role'] = roles

# Print the updated DataFrame
print("Updated DataFrame with country and role information:")
print(df)

C:\Users\kiran\AppData\Local\Temp\ipykernel_20696\3202768010.py:29: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None

Updated DataFrame with country and role information:
           Player Name  In_df2  In_df3       Country                 Role
0        Naveen-ul-Haq    True    True   Afghanistan               Bowler
1        Cameron Green    True    True     Australia   Batting Allrounder
2        Glenn Maxwell    True    True     Australia   Batting Allrounder
3     Liam Livingstone    True    True       England   Batting Allrounder
4   Faf du Plessis (c)    True   False  South Africa  Middle order Batter
5   Heinrich Klaasen †    True   False  South Africa  Wicketkeeper Batter
6            Jason Roy    True   False       England       Opening Batter
7    Quinton de Kock †    True   False  South Africa  Wicketkeeper Batter
8      Ruturaj Gaikwad    True   False         India               Batter
9        Sai Sudharsan    True   False         India     Top order Batter
10        Shubman Gill    True   False         India       Opening Batter
11    Suryakumar Yadav    True   False         India               Batter
12         Virat Kohli    True   False         India     Top order Batter
13    Yashasvi Jaiswal    True   False         India       Opening Batter

In [9]:
df = df.drop(columns=['In_df2', 'In_df3'])
df.to_csv('final_players_ipl_2023_with_info.csv', index=False)
df

           Player Name       Country                 Role
0        Naveen-ul-Haq   Afghanistan               Bowler
1        Cameron Green     Australia   Batting Allrounder
2        Glenn Maxwell     Australia   Batting Allrounder
3     Liam Livingstone       England   Batting Allrounder
4   Faf du Plessis (c)  South Africa  Middle order Batter
5   Heinrich Klaasen †  South Africa  Wicketkeeper Batter
6            Jason Roy       England       Opening Batter
7    Quinton de Kock †  South Africa  Wicketkeeper Batter
8      Ruturaj Gaikwad         India               Batter
9        Sai Sudharsan         India     Top order Batter
10        Shubman Gill         India       Opening Batter
11    Suryakumar Yadav         India               Batter
12         Virat Kohli         India     Top order Batter
13    Yashasvi Jaiswal         India       Opening Batter

In [10]:
import pandas as pd

# Select players with country name 'India'
indian_players = df[df['Country'] == 'India']

# Print the result
print("Indian Players:")
print(indian_players)

# Optionally, save the Indian players to a new CSV file
indian_players.to_csv('indian_players.csv', index=False)
print("Indian players saved to indian_players.csv")

Indian Players:
         Player Name Country              Role
8    Ruturaj Gaikwad   India            Batter
9      Sai Sudharsan   India  Top order Batter
10      Shubman Gill   India    Opening Batter
11  Suryakumar Yadav   India            Batter
12       Virat Kohli   India  Top order Batter
13  Yashasvi Jaiswal   India    Opening Batter
Indian players saved to indian_players.csv

In [1]:
import pandas as pd
df = pd.read_csv('final_players_ipl_2023_with_info.csv')
df1 = pd.read_csv('final_batting_stats.csv')
df2 = pd.read_csv('final_bowling_stats.csv')
df_batting = df.merge(df1, left_on='Player Name', right_on='batsmanName', how='left')

# Merge the resulting dataframe with df2 (bowling stats) using Player Name and bowlerName
df_combined = df_batting.merge(df2, left_on='Player Name', right_on='bowlerName', how='left')

# Save the combined dataframe to a CSV file
df_combined.to_csv('combined_player_data.csv', index=False)

# Display the combined dataframe
print(df_combined)

         Player Name       Country                 Role       batsmanName  \
0      Naveen-ul-Haq   Afghanistan               Bowler     Naveen-ul-Haq
1      Cameron Green     Australia   Batting Allrounder     Cameron Green
2      Glenn Maxwell     Australia   Batting Allrounder     Glenn Maxwell
3   Liam Livingstone       England   Batting Allrounder  Liam Livingstone
4     Faf du Plessis  South Africa  Middle order Batter    Faf du Plessis
5   Heinrich Klaasen  South Africa  Wicketkeeper Batter               NaN
6          Jason Roy       England       Opening Batter         Jason Roy
7    Quinton de Kock  South Africa  Wicketkeeper Batter               NaN
8    Ruturaj Gaikwad         India               Batter   Ruturaj Gaikwad
9      Sai Sudharsan         India     Top order Batter     Sai Sudharsan
10      Shubman Gill         India       Opening Batter      Shubman Gill
11  Suryakumar Yadav         India               Batter  Suryakumar Yadav
12       Virat Kohli         India     Top order Batter       Virat Kohli
13  Yashasvi Jaiswal         India       Opening Batter  Yashasvi Jaiswal

    inning_batted  Average_SR  Average_Boundary_Percentage  total_runs  \
0             3.0   62.220000                    20.512821        16.0
1            16.0  140.250000                    47.834033       452.0
2            14.0  156.695714                    73.439447       400.0
3             9.0  130.135556                    61.939116       279.0
4             3.0  183.940000                    74.869733       163.0
5             NaN         NaN                          NaN         NaN
6             8.0  145.907500                    72.209325       285.0
7             NaN         NaN                          NaN         NaN
8            15.0  139.366667                    55.831800       590.0
9             8.0  133.975000                    52.777908       362.0
10           17.0  136.261765                    58.190414       890.0
11           15.0  154.372000                    57.794447       562.0
12           11.0  126.054545                    49.268930       526.0
13           14.0  136.939286                    70.933030       625.0

    batting_average        bowlerName  inningbowled  avg_bowling_economy  \
0          5.333333     Naveen-ul-Haq           7.0                 7.82
1         28.250000     Cameron Green          16.0                 9.60
2         28.571429     Glenn Maxwell           7.0                 8.34
3         31.000000  Liam Livingstone           5.0                13.80
4         54.333333               NaN           NaN                  NaN
5               NaN               NaN           NaN                  NaN
6         35.625000               NaN           NaN                  NaN
7               NaN               NaN           NaN                  NaN
8         39.333333               NaN           NaN                  NaN
9         45.250000               NaN           NaN                  NaN
10        52.352941               NaN           NaN                  NaN
11        37.466667               NaN           NaN                  NaN
12        47.818182               NaN           NaN                  NaN
13        44.642857               NaN           NaN                  NaN

    avg_bowling_strike  average_bowling_avg  average_dot_ball_%
0                 11.5                12.12               40.48
1                 14.4                22.90               41.49
2                  8.8                11.33               33.39
3                  9.0                21.00               10.00
4                  NaN                  NaN                 NaN
5                  NaN                  NaN                 NaN
6                  NaN                  NaN                 NaN
7                  NaN                  NaN                 NaN
8                  NaN                  NaN                 NaN
9                  NaN                  NaN                 NaN
10                 NaN                  NaN                 NaN
11                 NaN                  NaN                 NaN
12                 NaN                  NaN                 NaN
13                 NaN                  NaN                 NaN

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)