In [1]:
import pandas as pd
df = pd.read_csv('bowling.csv')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,match_id
0,Deepak Chahar,4.0,0,38,1,9.50,5,3,1,0,0,https://www.espncricinfo.com/cricketers/deepak...,scorecard
1,Tushar Deshpande,4.0,0,56,0,14.00,4,7,3,0,0,https://www.espncricinfo.com/cricketers/tushar...,scorecard
2,Maheesh Theekshana,4.0,0,36,0,9.00,8,3,2,0,0,https://www.espncricinfo.com/cricketers/mahees...,scorecard
3,Ravindra Jadeja,4.0,0,38,1,9.50,3,3,1,0,0,https://www.espncricinfo.com/cricketers/ravind...,scorecard
4,Matheesha Pathirana,4.0,0,44,2,11.00,7,4,2,2,0,https://www.espncricinfo.com/cricketers/mathee...,scorecard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,Deepak Chahar,4.0,0,29,0,7.25,9,1,2,0,0,https://www.espncricinfo.com/cricketers/deepak...,scorecard
894,Tushar Deshpande,3.2,0,51,1,15.30,5,4,4,1,1,https://www.espncricinfo.com/cricketers/tushar...,scorecard
895,Rajvardhan Hangargekar,4.0,0,36,3,9.00,10,4,1,3,1,https://www.espncricinfo.com/cricketers/rajvar...,scorecard
896,Mitchell Santner,4.0,0,32,0,8.00,7,5,0,0,0,https://www.espncricinfo.com/cricketers/mitche...,scorecard
897,Ravindra Jadeja,4.0,0,28,1,7.00,9,1,1,0,0,https://www.espncricinfo.com/cricketers/ravind...,scorecard

In [2]:
df.describe()

,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000
mean,3.170267,0.017817,28.138085,0.954343,9.189566,6.795100,2.420935,1.251670,0.697105,0.111359
std,1.045709,0.132361,11.459340,1.035129,3.385706,3.609769,1.699527,1.218184,1.027825,0.376074
min,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.000000,20.000000,0.000000,7.000000,4.000000,1.000000,0.000000,0.000000,0.000000
50%,4.000000,0.000000,28.000000,1.000000,8.750000,7.000000,2.000000,1.000000,0.000000,0.000000
75%,4.000000,0.000000,36.000000,2.000000,11.000000,9.000000,3.000000,2.000000,1.000000,0.000000
max,4.000000,1.000000,69.000000,5.000000,26.000000,19.000000,10.000000,8.000000,7.000000,3.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bowlerName   898 non-null    object
 1   overs        898 non-null    float64
 2   maidens      898 non-null    int64
 3   runs         898 non-null    int64
 4   wickets      898 non-null    int64
 5   economy      898 non-null    float64
 6   dots         898 non-null    int64
 7   fours        898 non-null    int64
 8   sixes        898 non-null    int64
 9   wides        898 non-null    int64
 10  no_balls     898 non-null    int64
 11  bowler_link  898 non-null    object
 12  match_id     898 non-null    object
dtypes: float64(2), int64(8), object(3)
memory usage: 91.3+ KB

In [4]:
df.drop(['match_id'], axis=1, inplace=True)

In [5]:
df = df.sort_values(by='bowlerName')

print(df)

           bowlerName  overs  maidens  runs  wickets  economy  dots  fours  \
202   Abhishek Sharma    3.0        0    42        1    14.00     6      1
268   Abhishek Sharma    2.0        0    15        0     7.50     5      1
418   Abhishek Sharma    3.0        0    26        1     8.66     5      2
111   Abhishek Sharma    3.0        0    28        0     9.33     5      3
147   Abhishek Sharma    1.0        0    13        0    13.00     2      1
..                ...    ...      ...   ...      ...      ...   ...    ...
774  Yuzvendra Chahal    4.0        0    27        3     6.75     8      2
98   Yuzvendra Chahal    4.0        0    40        0    10.00     9      3
588  Yuzvendra Chahal    4.0        0    41        0    10.25     5      3
168  Yuzvendra Chahal    4.0        0    37        0     9.25     4      3
513  Yuzvendra Chahal    4.0        0    28        1     7.00     7      0

     sixes  wides  no_balls                                        bowler_link
202      5      1         0  https://www.espncricinfo.com/cricketers/abhish...
268      1      0         0  https://www.espncricinfo.com/cricketers/abhish...
418      1      0         0  https://www.espncricinfo.com/cricketers/abhish...
111      1      1         0  https://www.espncricinfo.com/cricketers/abhish...
147      1      1         0  https://www.espncricinfo.com/cricketers/abhish...
..     ...    ...       ...                                                ...
774      0      2         0  https://www.espncricinfo.com/cricketers/yuzven...
98       3      1         0  https://www.espncricinfo.com/cricketers/yuzven...
588      2      0         0  https://www.espncricinfo.com/cricketers/yuzven...
168      1      1         0  https://www.espncricinfo.com/cricketers/yuzven...
513      1      2         0  https://www.espncricinfo.com/cricketers/yuzven...

[898 rows x 12 columns]

In [6]:
name_counts = df['bowlerName'].value_counts()

# Step 2: Add a new column to the DataFrame that shows how many times each player appears
df['inningbowled'] = df['bowlerName'].map(name_counts)

# Step 3: Display the updated DataFrame
print(df)

           bowlerName  overs  maidens  runs  wickets  economy  dots  fours  \
202   Abhishek Sharma    3.0        0    42        1    14.00     6      1
268   Abhishek Sharma    2.0        0    15        0     7.50     5      1
418   Abhishek Sharma    3.0        0    26        1     8.66     5      2
111   Abhishek Sharma    3.0        0    28        0     9.33     5      3
147   Abhishek Sharma    1.0        0    13        0    13.00     2      1
..                ...    ...      ...   ...      ...      ...   ...    ...
774  Yuzvendra Chahal    4.0        0    27        3     6.75     8      2
98   Yuzvendra Chahal    4.0        0    40        0    10.00     9      3
588  Yuzvendra Chahal    4.0        0    41        0    10.25     5      3
168  Yuzvendra Chahal    4.0        0    37        0     9.25     4      3
513  Yuzvendra Chahal    4.0        0    28        1     7.00     7      0

     sixes  wides  no_balls  \
202      5      1         0
268      1      0         0
418      1      0         0
111      1      1         0
147      1      1         0
..     ...    ...       ...
774      0      2         0
98       3      1         0
588      2      0         0
168      1      1         0
513      1      2         0

                                           bowler_link  inningbowled
202  https://www.espncricinfo.com/cricketers/abhish...             5
268  https://www.espncricinfo.com/cricketers/abhish...             5
418  https://www.espncricinfo.com/cricketers/abhish...             5
111  https://www.espncricinfo.com/cricketers/abhish...             5
147  https://www.espncricinfo.com/cricketers/abhish...             5
..                                                 ...           ...
774  https://www.espncricinfo.com/cricketers/yuzven...            14
98   https://www.espncricinfo.com/cricketers/yuzven...            14
588  https://www.espncricinfo.com/cricketers/yuzven...            14
168  https://www.espncricinfo.com/cricketers/yuzven...            14
513  https://www.espncricinfo.com/cricketers/yuzven...            14

[898 rows x 13 columns]

In [7]:
import pandas as pd

# Load the CSV file and make sure to reference the correct column name
players_to_check_df = pd.read_csv('temp.csv')

# Convert the 'batsmanName' column to a list
players_to_check = players_to_check_df['batsmanName'].tolist()

# Filter the DataFrame to find players who have bowled more than 2 innings
filtered_df = df[df['inningbowled'] > 2]

# Check if the player names are present in the filtered DataFrame
present_players = filtered_df[filtered_df['bowlerName'].isin(players_to_check)]

# Display the result
present_players

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled
241,Cameron Green,2.0,0,15,1,7.50,6,3,0,0,0,https://www.espncricinfo.com/cricketers/camero...,16
340,Cameron Green,2.0,0,15,0,7.50,7,2,0,0,0,https://www.espncricinfo.com/cricketers/camero...,16
383,Cameron Green,3.0,0,31,0,10.33,10,2,2,4,0,https://www.espncricinfo.com/cricketers/camero...,16
760,Cameron Green,3.0,0,20,0,6.66,6,0,1,1,0,https://www.espncricinfo.com/cricketers/camero...,16
475,Cameron Green,2.0,0,39,0,19.50,0,2,4,0,0,https://www.espncricinfo.com/cricketers/camero...,16
213,Cameron Green,1.0,0,13,0,13.00,3,0,2,0,0,https://www.espncricinfo.com/cricketers/camero...,16
850,Cameron Green,2.0,0,30,1,15.00,4,2,3,0,0,https://www.espncricinfo.com/cricketers/camero...,16
309,Cameron Green,1.0,0,10,0,10.00,4,2,0,1,1,https://www.espncricinfo.com/cricketers/camero...,16
706,Cameron Green,3.0,0,30,0,10.00,4,5,0,1,0,https://www.espncricinfo.com/cricketers/camero...,16
606,Cameron Green,4.0,0,29,1,7.25,9,4,0,1,0,https://www.espncricinfo.com/cricketers/camero...,16
12,Cameron Green,3.0,0,35,0,11.66,4,3,2,0,0,https://www.espncricinfo.com/cricketers/camero...,16
32,Cameron Green,3.0,0,15,0,5.00,7,1,0,0,0,https://www.espncricinfo.com/cricketers/camero...,16
523,Cameron Green,4.0,0,41,2,10.25,9,2,4,0,0,https://www.espncricinfo.com/cricketers/camero...,16
57,Cameron Green,1.0,0,2,0,2.00,4,0,0,0,0,https://www.espncricinfo.com/cricketers/camero...,16
631,Cameron Green,2.0,0,20,1,10.00,6,1,1,2,0,https://www.espncricinfo.com/cricketers/camero...,16
134,Cameron Green,2.0,0,16,0,8.00,5,1,1,0,0,https://www.espncricinfo.com/cricketers/camero...,16
378,Glenn Maxwell,1.0,0,3,1,3.00,3,0,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,7
610,Glenn Maxwell,2.4,0,28,1,10.50,4,0,3,1,0,https://www.espncricinfo.com/cricketers/glenn-...,7
518,Glenn Maxwell,2.0,0,25,0,12.50,3,2,2,0,0,https://www.espncricinfo.com/cricketers/glenn-...,7
583,Glenn Maxwell,1.0,0,5,0,5.00,1,0,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,7
845,Glenn Maxwell,1.0,0,16,0,16.00,0,1,1,1,0,https://www.espncricinfo.com/cricketers/glenn-...,7
297,Glenn Maxwell,1.4,0,14,0,8.40,4,1,1,0,0,https://www.espncricinfo.com/cricketers/glenn-...,7
175,Glenn Maxwell,1.0,0,3,1,3.00,4,0,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,7
400,Liam Livingstone,1.0,0,16,0,16.00,0,3,0,0,0,https://www.espncricinfo.com/cricketers/liam-l...,5
261,Liam Livingstone,2.0,0,27,0,13.50,2,4,1,0,0,https://www.espncricinfo.com/cricketers/liam-l...,5
437,Liam Livingstone,1.0,0,19,1,19.00,1,3,1,0,0,https://www.espncricinfo.com/cricketers/liam-l...,5
578,Liam Livingstone,1.0,0,9,0,9.00,0,1,0,0,0,https://www.espncricinfo.com/cricketers/liam-l...,5
533,Liam Livingstone,2.0,0,23,1,11.50,2,4,0,0,0,https://www.espncricinfo.com/cricketers/liam-l...,5

In [8]:
selected_players =pd.read_csv('selected_players.csv')
selected_players = pd.concat([present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

           bowlerName         batsmanName
241     Cameron Green                 NaN
340     Cameron Green                 NaN
383     Cameron Green                 NaN
760     Cameron Green                 NaN
475     Cameron Green                 NaN
213     Cameron Green                 NaN
850     Cameron Green                 NaN
309     Cameron Green                 NaN
706     Cameron Green                 NaN
606     Cameron Green                 NaN
12      Cameron Green                 NaN
32      Cameron Green                 NaN
523     Cameron Green                 NaN
57      Cameron Green                 NaN
631     Cameron Green                 NaN
134     Cameron Green                 NaN
378     Glenn Maxwell                 NaN
610     Glenn Maxwell                 NaN
518     Glenn Maxwell                 NaN
583     Glenn Maxwell                 NaN
845     Glenn Maxwell                 NaN
297     Glenn Maxwell                 NaN
175     Glenn Maxwell                 NaN
400  Liam Livingstone                 NaN
261  Liam Livingstone                 NaN
437  Liam Livingstone                 NaN
578  Liam Livingstone                 NaN
533  Liam Livingstone                 NaN
0                 NaN  Faf du PlessisÂ (c)
1                 NaN  Heinrich KlaasenÂ â€
2                 NaN           Jason Roy
3                 NaN   Quinton de KockÂ â€
4                 NaN     Ruturaj Gaikwad
5                 NaN       Sai Sudharsan
6                 NaN        Shubman Gill
7                 NaN    Suryakumar Yadav
8                 NaN         Virat Kohli
9                 NaN    Yashasvi Jaiswal
10                NaN                 NaN
11                NaN                 NaN
13                NaN                 NaN
14                NaN                 NaN
15                NaN                 NaN
16                NaN                 NaN

In [9]:
# PARAMETERS
# Batting Average > 15
# Strike Rate > 130
# Innings Batted > 2
# Innings Bowled > 4
# Bowling Economy > 7
# Bowling Strike Rate > 20

In [10]:
df2 = pd.read_csv('final_batting_stats.csv')
df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Abdul Basith,1,100.000000,0.000000,1,1.000000
1,Abdul Samad,8,144.896250,65.616818,169,21.125000
2,Abhinav Manohar,6,131.355000,41.147741,114,19.000000
3,Abhishek Sharma,11,111.402727,52.103458,226,20.545455
4,Abishek PorelÂ â€,4,88.852500,29.285714,33,8.250000
...,...,...,...,...,...,...
188,Wayne Parnell,1,40.000000,0.000000,2,2.000000
189,Wriddhiman SahaÂ â€,17,107.431765,58.950648,371,21.823529
190,Yash Dhull,3,53.886667,10.256410,16,5.333333
191,Yashasvi Jaiswal,14,136.939286,70.933030,625,44.642857
192,Yudhvir Singh,2,50.000000,0.000000,1,0.500000

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   batsmanName                  193 non-null    object
 1   inning_batted                193 non-null    int64
 2   Average_SR                   193 non-null    float64
 3   Average_Boundary_Percentage  181 non-null    float64
 4   total_runs                   193 non-null    int64
 5   batting_average              193 non-null    float64
dtypes: float64(3), int64(2), object(1)
memory usage: 9.2+ KB

In [12]:
filtered_df2 = df2[
    (df2['batting_average'] > 15) &
    (df2['Average_SR'] > 127) &
    (df2['inning_batted'] > 2)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Abdul Samad,8,144.896250,65.616818,169,21.125000
1,Abhinav Manohar,6,131.355000,41.147741,114,19.000000
2,Ajinkya Rahane,11,161.448182,47.188619,326,29.636364
3,Anmolpreet Singh,3,130.110000,74.814815,74,24.666667
4,Atharva Taide,7,131.380000,63.609049,186,26.571429
5,Axar Patel,13,143.928462,50.809178,283,21.769231
6,Cameron Green,16,140.250000,47.834033,452,28.250000
7,Faf du Plessis,3,183.940000,74.869733,163,54.333333
8,Faf du PlessisÂ (c),11,153.735455,62.737770,567,51.545455
9,Glenn Maxwell,14,156.695714,73.439447,400,28.571429
10,Hardik PandyaÂ (c),15,138.796667,56.289205,346,23.066667
11,Harpreet Singh,3,130.286667,66.587071,76,25.333333
12,Heinrich KlaasenÂ â€,11,182.172727,61.097009,448,40.727273
13,Ishan KishanÂ â€,15,128.024667,64.380908,454,30.266667
14,Jason Roy,8,145.907500,72.209325,285,35.625000
15,Jitesh SharmaÂ â€,14,148.360714,67.673417,309,22.071429
16,Liam Livingstone,9,130.135556,61.939116,279,31.000000
17,Nehal Wadhera,10,139.970000,71.804439,241,24.100000
18,Nicholas Pooran,4,170.447500,52.782132,113,28.250000
19,Nicholas PooranÂ â€,11,131.639091,58.714198,245,22.272727
20,Quinton de KockÂ â€,4,133.430000,61.410099,143,35.750000
21,Rahul Tripathi,13,127.175385,58.145040,273,21.000000
22,Ravindra Jadeja,12,148.148333,42.790828,190,15.833333
23,Rinku Singh,14,144.611429,55.986462,474,33.857143
24,Ruturaj Gaikwad,15,139.366667,55.831800,590,39.333333
25,Sai Sudharsan,8,133.975000,52.777908,362,45.250000
26,Sam Curran,10,129.133000,44.262795,205,20.500000
27,Shimron Hetmyer,13,129.983846,41.676722,299,23.000000
28,Shivam Dube,14,153.422143,56.228640,418,29.857143
29,Shubman Gill,17,136.261765,58.190414,890,52.352941
30,Sikandar Raza,7,128.842857,38.367846,139,19.857143
31,Suryakumar Yadav,15,154.372000,57.794447,562,37.466667
32,Tilak Varma,11,158.990909,57.368581,343,31.181818
33,Vijay Shankar,10,149.695000,60.114255,301,30.100000
34,Yashasvi Jaiswal,14,136.939286,70.933030,625,44.642857

In [13]:
df['avg_bowling_economy'] = df.groupby('bowlerName')['economy'].transform('mean')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Yuzvendra Chahal,4.0,0,27,3,6.75,8,2,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714
98,Yuzvendra Chahal,4.0,0,40,0,10.00,9,3,3,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714
588,Yuzvendra Chahal,4.0,0,41,0,10.25,5,3,2,0,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714
168,Yuzvendra Chahal,4.0,0,37,0,9.25,4,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714
513,Yuzvendra Chahal,4.0,0,28,1,7.00,7,0,1,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714

bowling strike rate = avg no of balls required to take a wicket = total run / total wickets

In [14]:
import numpy as np

# Calculate the bowling strike rate and set to 0 if wickets = 0
df['bowling SR'] = np.where(df['wickets'] == 0, 0, (df['overs'] * 6) / df['wickets'])

# Display the updated DataFrame
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Yuzvendra Chahal,4.0,0,27,3,6.75,8,2,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,8.0
98,Yuzvendra Chahal,4.0,0,40,0,10.00,9,3,3,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0
588,Yuzvendra Chahal,4.0,0,41,0,10.25,5,3,2,0,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0
168,Yuzvendra Chahal,4.0,0,37,0,9.25,4,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0
513,Yuzvendra Chahal,4.0,0,28,1,7.00,7,0,1,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,24.0

In [15]:
# Step 1: Filter the DataFrame to exclude rows where economy is 0
filtered_df = df[df['bowling SR'] != 0]

# Step 2: Calculate the average economy for each bowler and add it to the original DataFrame
df['avg_bowling_strike'] = df.groupby('bowlerName')['bowling SR'].transform(lambda x: x[x != 0].mean())

# Display the updated DataFrame
df.head(20)

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.0
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.0
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.0
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.0
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.0
457,Adam Zampa,3.0,0,22,3,7.33,7,2,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,6.0,18.0
701,Adam Zampa,4.0,0,43,1,10.75,5,4,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,24.0,18.0
621,Adam Zampa,4.0,0,32,1,8.00,9,2,2,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,24.0,18.0
97,Adam Zampa,4.0,0,26,1,6.50,6,2,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,24.0,18.0
324,Adam Zampa,3.0,0,40,0,13.33,3,3,3,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,0.0,18.0
167,Adam Zampa,4.0,0,25,2,6.25,10,2,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,12.0,18.0
856,Adil Rashid,4.0,0,33,0,8.25,6,1,2,0,0,https://www.espncricinfo.com/cricketers/adil-r...,2,7.955000,0.0,9.0
787,Adil Rashid,3.0,0,23,2,7.66,8,2,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,2,7.955000,9.0,9.0
490,Aiden Markram,1.0,0,7,0,7.00,0,0,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0
68,Aiden Markram,0.1,0,1,0,6.00,0,0,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0
786,Aiden Markram,2.0,0,14,0,7.00,5,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0
555,Aiden Markram,1.0,0,11,0,11.00,2,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0
145,Aiden Markram,1.0,0,13,0,13.00,0,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0
330,Aiden Markram,3.0,0,24,1,8.00,5,2,1,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,18.0,18.0
841,Akash Deep,3.0,0,29,1,9.66,7,2,2,0,0,https://www.espncricinfo.com/cricketers/akash-...,2,12.330000,18.0,18.0

In [16]:
import numpy as np

# Calculate the bowling strike rate and set to 0 if wickets = 0
df['bowling_avg'] = np.where(df['wickets'] == 0, 0, (df['runs']) / df['wickets'])

# Display the updated DataFrame
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.000000,42.0
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.000000,26.0
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Yuzvendra Chahal,4.0,0,27,3,6.75,8,2,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,8.0,14.555556,9.0
98,Yuzvendra Chahal,4.0,0,40,0,10.00,9,3,3,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0
588,Yuzvendra Chahal,4.0,0,41,0,10.25,5,3,2,0,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0
168,Yuzvendra Chahal,4.0,0,37,0,9.25,4,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0
513,Yuzvendra Chahal,4.0,0,28,1,7.00,7,0,1,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,24.0,14.555556,28.0

In [17]:
# Step 1: Filter the DataFrame to exclude rows where bowling_avg is 0
filtered_df = df[df['bowling_avg'] != 0]

# Step 2: Calculate the average bowling_avg for each bowler and add it to the original DataFrame
df['average_bowling_avg'] = df.groupby('bowlerName')['bowling_avg'].transform(lambda x: x[x != 0].mean())

# Display the updated DataFrame
df.head(20)

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.0,42.000000,34.000000
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.0,0.000000,34.000000
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.0,26.000000,34.000000
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.0,0.000000,34.000000
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.0,0.000000,34.000000
457,Adam Zampa,3.0,0,22,3,7.33,7,2,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,6.0,18.0,7.333333,24.166667
701,Adam Zampa,4.0,0,43,1,10.75,5,4,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,24.0,18.0,43.000000,24.166667
621,Adam Zampa,4.0,0,32,1,8.00,9,2,2,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,24.0,18.0,32.000000,24.166667
97,Adam Zampa,4.0,0,26,1,6.50,6,2,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,24.0,18.0,26.000000,24.166667
324,Adam Zampa,3.0,0,40,0,13.33,3,3,3,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,0.0,18.0,0.000000,24.166667
167,Adam Zampa,4.0,0,25,2,6.25,10,2,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,6,8.693333,12.0,18.0,12.500000,24.166667
856,Adil Rashid,4.0,0,33,0,8.25,6,1,2,0,0,https://www.espncricinfo.com/cricketers/adil-r...,2,7.955000,0.0,9.0,0.000000,11.500000
787,Adil Rashid,3.0,0,23,2,7.66,8,2,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,2,7.955000,9.0,9.0,11.500000,11.500000
490,Aiden Markram,1.0,0,7,0,7.00,0,0,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0,0.000000,24.000000
68,Aiden Markram,0.1,0,1,0,6.00,0,0,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0,0.000000,24.000000
786,Aiden Markram,2.0,0,14,0,7.00,5,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0,0.000000,24.000000
555,Aiden Markram,1.0,0,11,0,11.00,2,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0,0.000000,24.000000
145,Aiden Markram,1.0,0,13,0,13.00,0,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,0.0,18.0,0.000000,24.000000
330,Aiden Markram,3.0,0,24,1,8.00,5,2,1,0,0,https://www.espncricinfo.com/cricketers/aiden-...,6,8.666667,18.0,18.0,24.000000,24.000000
841,Akash Deep,3.0,0,29,1,9.66,7,2,2,0,0,https://www.espncricinfo.com/cricketers/akash-...,2,12.330000,18.0,18.0,29.000000,29.000000

In [18]:
# dot ball percentage
df['dot_ball_percentage'] = ((df['dots']) / (df['overs']*6)) *100
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg,dot_ball_percentage
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.000000,42.0,34.000000,33.333333
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0,34.000000,41.666667
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.000000,26.0,34.000000,27.777778
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0,34.000000,27.777778
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0,34.000000,33.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Yuzvendra Chahal,4.0,0,27,3,6.75,8,2,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,8.0,14.555556,9.0,19.583333,33.333333
98,Yuzvendra Chahal,4.0,0,40,0,10.00,9,3,3,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0,19.583333,37.500000
588,Yuzvendra Chahal,4.0,0,41,0,10.25,5,3,2,0,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0,19.583333,20.833333
168,Yuzvendra Chahal,4.0,0,37,0,9.25,4,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0,19.583333,16.666667
513,Yuzvendra Chahal,4.0,0,28,1,7.00,7,0,1,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,24.0,14.555556,28.0,19.583333,29.166667

In [19]:
df['average_dot_ball_%'] = df.groupby('bowlerName')['dot_ball_percentage'].transform('mean')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg,dot_ball_percentage,average_dot_ball_%
202,Abhishek Sharma,3.0,0,42,1,14.00,6,1,5,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.000000,42.0,34.000000,33.333333,32.777778
268,Abhishek Sharma,2.0,0,15,0,7.50,5,1,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0,34.000000,41.666667,32.777778
418,Abhishek Sharma,3.0,0,26,1,8.66,5,2,1,0,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,18.0,18.000000,26.0,34.000000,27.777778,32.777778
111,Abhishek Sharma,3.0,0,28,0,9.33,5,3,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0,34.000000,27.777778,32.777778
147,Abhishek Sharma,1.0,0,13,0,13.00,2,1,1,1,0,https://www.espncricinfo.com/cricketers/abhish...,5,10.498000,0.0,18.000000,0.0,34.000000,33.333333,32.777778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,Yuzvendra Chahal,4.0,0,27,3,6.75,8,2,0,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,8.0,14.555556,9.0,19.583333,33.333333,30.555556
98,Yuzvendra Chahal,4.0,0,40,0,10.00,9,3,3,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0,19.583333,37.500000,30.555556
588,Yuzvendra Chahal,4.0,0,41,0,10.25,5,3,2,0,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0,19.583333,20.833333,30.555556
168,Yuzvendra Chahal,4.0,0,37,0,9.25,4,3,1,1,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,0.0,14.555556,0.0,19.583333,16.666667,30.555556
513,Yuzvendra Chahal,4.0,0,28,1,7.00,7,0,1,2,0,https://www.espncricinfo.com/cricketers/yuzven...,14,8.295714,24.0,14.555556,28.0,19.583333,29.166667,30.555556

In [20]:
df.fillna(0, inplace=True)
df = df.round(2)
df.to_csv('processed_balling_stats.csv', index=False)

In [21]:
df3 = df[['bowlerName', 'inningbowled', 'avg_bowling_economy', 'avg_bowling_strike', 'average_bowling_avg', 'average_dot_ball_%']].copy()
df3.drop_duplicates(inplace=True)
df3
df3.to_csv('final_bowling_stats.csv', index=False)

In [22]:
# Filter the DataFrame based on the given conditions
filtered_df3 = df3[
    (df3['inningbowled'] > 2) & 
    (df3['avg_bowling_economy'] < 7) & 
    (df3['avg_bowling_strike'] < 20) 
]

# Display the filtered DataFrame
filtered_df3

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
691,Matthew Short,3,6.67,0.0,0.0,41.67
896,Mitchell Santner,3,6.75,18.0,17.5,30.56

In [23]:
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Abdul Samad,8,144.896250,65.616818,169,21.125000
1,Abhinav Manohar,6,131.355000,41.147741,114,19.000000
2,Ajinkya Rahane,11,161.448182,47.188619,326,29.636364
3,Anmolpreet Singh,3,130.110000,74.814815,74,24.666667
4,Atharva Taide,7,131.380000,63.609049,186,26.571429
5,Axar Patel,13,143.928462,50.809178,283,21.769231
6,Cameron Green,16,140.250000,47.834033,452,28.250000
7,Faf du Plessis,3,183.940000,74.869733,163,54.333333
8,Faf du PlessisÂ (c),11,153.735455,62.737770,567,51.545455
9,Glenn Maxwell,14,156.695714,73.439447,400,28.571429
10,Hardik PandyaÂ (c),15,138.796667,56.289205,346,23.066667
11,Harpreet Singh,3,130.286667,66.587071,76,25.333333
12,Heinrich KlaasenÂ â€,11,182.172727,61.097009,448,40.727273
13,Ishan KishanÂ â€,15,128.024667,64.380908,454,30.266667
14,Jason Roy,8,145.907500,72.209325,285,35.625000
15,Jitesh SharmaÂ â€,14,148.360714,67.673417,309,22.071429
16,Liam Livingstone,9,130.135556,61.939116,279,31.000000
17,Nehal Wadhera,10,139.970000,71.804439,241,24.100000
18,Nicholas Pooran,4,170.447500,52.782132,113,28.250000
19,Nicholas PooranÂ â€,11,131.639091,58.714198,245,22.272727
20,Quinton de KockÂ â€,4,133.430000,61.410099,143,35.750000
21,Rahul Tripathi,13,127.175385,58.145040,273,21.000000
22,Ravindra Jadeja,12,148.148333,42.790828,190,15.833333
23,Rinku Singh,14,144.611429,55.986462,474,33.857143
24,Ruturaj Gaikwad,15,139.366667,55.831800,590,39.333333
25,Sai Sudharsan,8,133.975000,52.777908,362,45.250000
26,Sam Curran,10,129.133000,44.262795,205,20.500000
27,Shimron Hetmyer,13,129.983846,41.676722,299,23.000000
28,Shivam Dube,14,153.422143,56.228640,418,29.857143
29,Shubman Gill,17,136.261765,58.190414,890,52.352941
30,Sikandar Raza,7,128.842857,38.367846,139,19.857143
31,Suryakumar Yadav,15,154.372000,57.794447,562,37.466667
32,Tilak Varma,11,158.990909,57.368581,343,31.181818
33,Vijay Shankar,10,149.695000,60.114255,301,30.100000
34,Yashasvi Jaiswal,14,136.939286,70.933030,625,44.642857

In [24]:
# List of player names to check
players_to_check = filtered_df2['batsmanName'].tolist()

# Check if these names are present in the 'bowlerName' column of filtered_df3
present_players2 = filtered_df3[filtered_df3['bowlerName'].isin(players_to_check)]

# Display the result
present_players2
# Display unique bowler names to verify if players exist

Empty DataFrame
Columns: [bowlerName, inningbowled, avg_bowling_economy, avg_bowling_strike, average_bowling_avg, average_dot_ball_%]
Index: []

In [25]:
selected_players = pd.concat([present_players2['bowlerName'], present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

    bowlerName        bowlerName         batsmanName
241        NaN     Cameron Green                 NaN
340        NaN     Cameron Green                 NaN
383        NaN     Cameron Green                 NaN
760        NaN     Cameron Green                 NaN
475        NaN     Cameron Green                 NaN
213        NaN     Cameron Green                 NaN
850        NaN     Cameron Green                 NaN
309        NaN     Cameron Green                 NaN
706        NaN     Cameron Green                 NaN
606        NaN     Cameron Green                 NaN
12         NaN     Cameron Green                 NaN
32         NaN     Cameron Green                 NaN
523        NaN     Cameron Green                 NaN
57         NaN     Cameron Green                 NaN
631        NaN     Cameron Green                 NaN
134        NaN     Cameron Green                 NaN
378        NaN     Glenn Maxwell                 NaN
610        NaN     Glenn Maxwell                 NaN
518        NaN     Glenn Maxwell                 NaN
583        NaN     Glenn Maxwell                 NaN
845        NaN     Glenn Maxwell                 NaN
297        NaN     Glenn Maxwell                 NaN
175        NaN     Glenn Maxwell                 NaN
400        NaN  Liam Livingstone                 NaN
261        NaN  Liam Livingstone                 NaN
437        NaN  Liam Livingstone                 NaN
578        NaN  Liam Livingstone                 NaN
533        NaN  Liam Livingstone                 NaN
0          NaN               NaN  Faf du PlessisÂ (c)
1          NaN               NaN  Heinrich KlaasenÂ â€
2          NaN               NaN           Jason Roy
3          NaN               NaN   Quinton de KockÂ â€
4          NaN               NaN     Ruturaj Gaikwad
5          NaN               NaN       Sai Sudharsan
6          NaN               NaN        Shubman Gill
7          NaN               NaN    Suryakumar Yadav
8          NaN               NaN         Virat Kohli
9          NaN               NaN    Yashasvi Jaiswal
10         NaN               NaN                 NaN
11         NaN               NaN                 NaN
13         NaN               NaN                 NaN
14         NaN               NaN                 NaN
15         NaN               NaN                 NaN
16         NaN               NaN                 NaN

In [26]:
# Filter the DataFrame based on the given conditions
filtered_df4 = df3[
    (df3['inningbowled'] > 3) & 
    (df3['avg_bowling_economy'] < 8) & 
    (df3['avg_bowling_strike'] < 16) &
    (df3['average_bowling_avg'] < 25) &
    (df3['average_dot_ball_%'] > 40 ) 
]

# Display the filtered DataFrame
filtered_df4

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
137,Naveen-ul-Haq,7,7.82,11.5,12.12,40.48

In [27]:
selected_players = pd.concat([filtered_df4['bowlerName'],present_players2['bowlerName'], present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

        bowlerName bowlerName        bowlerName         batsmanName
137  Naveen-ul-Haq        NaN               NaN                 NaN
241            NaN        NaN     Cameron Green                 NaN
340            NaN        NaN     Cameron Green                 NaN
383            NaN        NaN     Cameron Green                 NaN
760            NaN        NaN     Cameron Green                 NaN
475            NaN        NaN     Cameron Green                 NaN
213            NaN        NaN     Cameron Green                 NaN
850            NaN        NaN     Cameron Green                 NaN
309            NaN        NaN     Cameron Green                 NaN
706            NaN        NaN     Cameron Green                 NaN
606            NaN        NaN     Cameron Green                 NaN
12             NaN        NaN     Cameron Green                 NaN
32             NaN        NaN     Cameron Green                 NaN
523            NaN        NaN     Cameron Green                 NaN
57             NaN        NaN     Cameron Green                 NaN
631            NaN        NaN     Cameron Green                 NaN
134            NaN        NaN     Cameron Green                 NaN
378            NaN        NaN     Glenn Maxwell                 NaN
610            NaN        NaN     Glenn Maxwell                 NaN
518            NaN        NaN     Glenn Maxwell                 NaN
583            NaN        NaN     Glenn Maxwell                 NaN
845            NaN        NaN     Glenn Maxwell                 NaN
297            NaN        NaN     Glenn Maxwell                 NaN
175            NaN        NaN     Glenn Maxwell                 NaN
400            NaN        NaN  Liam Livingstone                 NaN
261            NaN        NaN  Liam Livingstone                 NaN
437            NaN        NaN  Liam Livingstone                 NaN
578            NaN        NaN  Liam Livingstone                 NaN
533            NaN        NaN  Liam Livingstone                 NaN
0              NaN        NaN               NaN  Faf du PlessisÂ (c)
1              NaN        NaN               NaN  Heinrich KlaasenÂ â€
2              NaN        NaN               NaN           Jason Roy
3              NaN        NaN               NaN   Quinton de KockÂ â€
4              NaN        NaN               NaN     Ruturaj Gaikwad
5              NaN        NaN               NaN       Sai Sudharsan
6              NaN        NaN               NaN        Shubman Gill
7              NaN        NaN               NaN    Suryakumar Yadav
8              NaN        NaN               NaN         Virat Kohli
9              NaN        NaN               NaN    Yashasvi Jaiswal
10             NaN        NaN               NaN                 NaN
11             NaN        NaN               NaN                 NaN
13             NaN        NaN               NaN                 NaN
14             NaN        NaN               NaN                 NaN
15             NaN        NaN               NaN                 NaN
16             NaN        NaN               NaN                 NaN

In [28]:
# Combine the 'bowlerName' and 'batsmanName' columns, removing NaN values
player_names = selected_players[['bowlerName', 'batsmanName']].stack().dropna().unique()

# Convert to a list if required
player_names_list = list(player_names)

# Print the list of unique player names
player_names_list

['Naveen-ul-Haq',
 'Cameron Green',
 'Glenn Maxwell',
 'Liam Livingstone',
 'Faf du Plessis\xa0(c)',
 'Heinrich Klaasen\xa0â€ ',
 'Jason Roy',
 'Quinton de Kock\xa0â€ ',
 'Ruturaj Gaikwad',
 'Sai Sudharsan',
 'Shubman Gill',
 'Suryakumar Yadav',
 'Virat Kohli',
 'Yashasvi Jaiswal']

In [29]:
df_players = pd.DataFrame(player_names_list, columns=["Player Name"])

# Save the DataFrame to a CSV file
csv_filename = 'final_players_ipl_2023.csv'
df_players.to_csv(csv_filename, index=False)

print(f"Player names saved to {csv_filename}")

Player names saved to final_players_ipl_2023.csv