In [1]:
import pandas as pd
df = pd.read_csv('bowling.csv')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,match_id
0,Mitchell Starc,10.0,0,55,3,5.50,30,4,1,3,0,https://www.espncricinfo.com/cricketers/mitche...,scorecard
1,Josh Hazlewood,10.0,0,60,2,6.00,22,4,1,1,0,https://www.espncricinfo.com/cricketers/josh-h...,scorecard
2,Glenn Maxwell,6.0,0,35,1,5.83,19,4,1,0,0,https://www.espncricinfo.com/cricketers/glenn-...,scorecard
3,Pat Cummins,10.0,0,34,2,3.40,30,0,0,2,0,https://www.espncricinfo.com/cricketers/pat-cu...,scorecard
4,Adam Zampa,10.0,0,44,1,4.40,22,1,0,1,0,https://www.espncricinfo.com/cricketers/adam-z...,scorecard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,Sam Curran,6.0,2,47,1,7.83,17,6,1,2,0,https://www.espncricinfo.com/cricketers/sam-cu...,scorecard
570,Mark Wood,5.0,0,55,0,11.00,9,7,2,1,0,https://www.espncricinfo.com/cricketers/mark-w...,scorecard
571,Moeen Ali,9.2,0,60,0,6.42,20,2,3,0,0,https://www.espncricinfo.com/cricketers/moeen-...,scorecard
572,Adil Rashid,7.0,0,47,0,6.71,15,4,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,scorecard
573,Liam Livingstone,3.0,0,24,0,8.00,7,4,0,0,0,https://www.espncricinfo.com/cricketers/liam-l...,scorecard

In [2]:
df.describe()

,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls
count,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000,574.000000
mean,7.351045,0.256098,42.322300,1.202091,5.922369,22.918118,3.900697,1.121951,1.158537,0.097561
std,2.685601,0.533933,19.651473,1.193757,2.135935,10.251561,2.599953,1.302075,1.535259,0.330362
min,0.300000,0.000000,1.000000,0.000000,1.350000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,0.000000,30.000000,0.000000,4.500000,16.000000,2.000000,0.000000,0.000000,0.000000
50%,8.000000,0.000000,41.000000,1.000000,5.660000,24.000000,4.000000,1.000000,1.000000,0.000000
75%,10.000000,0.000000,55.000000,2.000000,7.075000,30.000000,5.000000,2.000000,2.000000,0.000000
max,10.000000,3.000000,115.000000,7.000000,16.000000,48.000000,15.000000,6.000000,10.000000,2.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bowlerName   574 non-null    object
 1   overs        574 non-null    float64
 2   maidens      574 non-null    int64
 3   runs         574 non-null    int64
 4   wickets      574 non-null    int64
 5   economy      574 non-null    float64
 6   dots         574 non-null    int64
 7   fours        574 non-null    int64
 8   sixes        574 non-null    int64
 9   wides        574 non-null    int64
 10  no_balls     574 non-null    int64
 11  bowler_link  574 non-null    object
 12  match_id     574 non-null    object
dtypes: float64(2), int64(8), object(3)
memory usage: 58.4+ KB

In [4]:
df.drop(['match_id'], axis=1, inplace=True)

In [5]:
df = df.sort_values(by='bowlerName')

print(df)

          bowlerName  overs  maidens  runs  wickets  economy  dots  fours  \
524       Adam Zampa    8.0        0    53        0     6.62    13      4
152       Adam Zampa   10.0        0    21        3     2.10    41      0
364       Adam Zampa   10.0        0    53        4     5.30    25      3
15        Adam Zampa    7.0        0    55        0     7.85    21      1
407       Adam Zampa    8.0        1    47        4     5.87    26      5
..               ...    ...      ...   ...      ...      ...   ...    ...
554  Vikramjit Singh    2.0        0    16        0     8.00     5      3
289  Vikramjit Singh    4.0        0    27        0     6.75    13      3
506  Vikramjit Singh    1.0        0     9        0     9.00     1      1
370      Virat Kohli    0.3        0     2        0     4.00     1      0
46       Virat Kohli    3.0        0    13        1     4.33    10      1

     sixes  wides  no_balls                                        bowler_link
524      0      0         0  https://www.espncricinfo.com/cricketers/adam-z...
152      0      2         0  https://www.espncricinfo.com/cricketers/adam-z...
364      1      1         0  https://www.espncricinfo.com/cricketers/adam-z...
15       6      0         0  https://www.espncricinfo.com/cricketers/adam-z...
407      1      2         0  https://www.espncricinfo.com/cricketers/adam-z...
..     ...    ...       ...                                                ...
554      0      0         0  https://www.espncricinfo.com/cricketers/vikram...
289      1      1         0  https://www.espncricinfo.com/cricketers/vikram...
506      0      0         0  https://www.espncricinfo.com/cricketers/vikram...
370      0      0         0  https://www.espncricinfo.com/cricketers/virat-...
46       0      0         0  https://www.espncricinfo.com/cricketers/virat-...

[574 rows x 12 columns]

In [6]:
name_counts = df['bowlerName'].value_counts()

# Step 2: Add a new column to the DataFrame that shows how many times each player appears
df['inningbowled'] = df['bowlerName'].map(name_counts)

# Step 3: Display the updated DataFrame
print(df)

          bowlerName  overs  maidens  runs  wickets  economy  dots  fours  \
524       Adam Zampa    8.0        0    53        0     6.62    13      4
152       Adam Zampa   10.0        0    21        3     2.10    41      0
364       Adam Zampa   10.0        0    53        4     5.30    25      3
15        Adam Zampa    7.0        0    55        0     7.85    21      1
407       Adam Zampa    8.0        1    47        4     5.87    26      5
..               ...    ...      ...   ...      ...      ...   ...    ...
554  Vikramjit Singh    2.0        0    16        0     8.00     5      3
289  Vikramjit Singh    4.0        0    27        0     6.75    13      3
506  Vikramjit Singh    1.0        0     9        0     9.00     1      1
370      Virat Kohli    0.3        0     2        0     4.00     1      0
46       Virat Kohli    3.0        0    13        1     4.33    10      1

     sixes  wides  no_balls  \
524      0      0         0
152      0      2         0
364      1      1         0
15       6      0         0
407      1      2         0
..     ...    ...       ...
554      0      0         0
289      1      1         0
506      0      0         0
370      0      0         0
46       0      0         0

                                           bowler_link  inningbowled
524  https://www.espncricinfo.com/cricketers/adam-z...            11
152  https://www.espncricinfo.com/cricketers/adam-z...            11
364  https://www.espncricinfo.com/cricketers/adam-z...            11
15   https://www.espncricinfo.com/cricketers/adam-z...            11
407  https://www.espncricinfo.com/cricketers/adam-z...            11
..                                                 ...           ...
554  https://www.espncricinfo.com/cricketers/vikram...             3
289  https://www.espncricinfo.com/cricketers/vikram...             3
506  https://www.espncricinfo.com/cricketers/vikram...             3
370  https://www.espncricinfo.com/cricketers/virat-...             2
46   https://www.espncricinfo.com/cricketers/virat-...             2

[574 rows x 13 columns]

In [7]:
import pandas as pd

# Load the CSV file and make sure to reference the correct column name
players_to_check_df = pd.read_csv('temp.csv')

# Convert the 'batsmanName' column to a list
players_to_check = players_to_check_df['batsmanName'].tolist()

# Filter the DataFrame to find players who have bowled more than 2 innings
filtered_df = df[df['inningbowled'] > 2]

# Check if the player names are present in the filtered DataFrame
present_players = filtered_df[filtered_df['bowlerName'].isin(players_to_check)]

# Display the result
present_players

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled
137,Aiden Markram,2.0,0,17,0,8.50,4,1,1,1,0,https://www.espncricinfo.com/cricketers/aiden-...,4
75,Aiden Markram,4.3,0,25,0,5.55,13,2,1,0,0,https://www.espncricinfo.com/cricketers/aiden-...,4
263,Aiden Markram,4.0,0,20,0,5.00,12,2,0,0,0,https://www.espncricinfo.com/cricketers/aiden-...,4
20,Aiden Markram,8.0,1,23,1,2.87,34,1,1,1,0,https://www.espncricinfo.com/cricketers/aiden-...,4
2,Glenn Maxwell,6.0,0,35,1,5.83,19,4,1,0,0,https://www.espncricinfo.com/cricketers/glenn-...,8
406,Glenn Maxwell,9.3,0,36,1,3.78,30,2,0,1,0,https://www.espncricinfo.com/cricketers/glenn-...,8
258,Glenn Maxwell,10.0,0,62,1,6.20,22,4,2,0,0,https://www.espncricinfo.com/cricketers/glenn-...,8
365,Glenn Maxwell,5.0,0,40,0,8.00,10,6,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,8
16,Glenn Maxwell,10.0,0,35,0,3.50,35,3,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,8
453,Glenn Maxwell,10.0,1,34,2,3.40,32,0,0,2,0,https://www.espncricinfo.com/cricketers/glenn-...,8
110,Glenn Maxwell,10.0,0,55,1,5.50,24,2,1,0,1,https://www.espncricinfo.com/cricketers/glenn-...,8
522,Glenn Maxwell,8.0,0,33,0,4.12,24,1,1,0,0,https://www.espncricinfo.com/cricketers/glenn-...,8
164,Glenn Phillips,5.0,1,42,0,8.40,13,3,3,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10
29,Glenn Phillips,5.0,0,33,0,6.60,11,1,2,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10
331,Glenn Phillips,2.0,0,12,0,6.00,3,1,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10
252,Glenn Phillips,10.0,0,37,3,3.70,30,2,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10
194,Glenn Phillips,7.0,0,52,0,7.42,15,2,3,2,0,https://www.espncricinfo.com/cricketers/glenn-...,10
567,Glenn Phillips,3.0,0,17,2,5.66,5,1,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10
443,Glenn Phillips,2.0,0,13,1,6.50,8,1,1,0,1,https://www.espncricinfo.com/cricketers/glenn-...,10
91,Glenn Phillips,1.0,0,3,0,3.00,3,0,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10
390,Glenn Phillips,3.0,0,13,0,4.33,7,0,0,1,0,https://www.espncricinfo.com/cricketers/glenn-...,10
512,Glenn Phillips,2.0,0,11,0,5.50,2,0,0,0,0,https://www.espncricinfo.com/cricketers/glenn-...,10

In [8]:
selected_players =pd.read_csv('selected_players.csv')
selected_players = pd.concat([present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

         bowlerName       batsmanName
137   Aiden Markram               NaN
75    Aiden Markram               NaN
263   Aiden Markram               NaN
20    Aiden Markram               NaN
2     Glenn Maxwell      David Warner
406   Glenn Maxwell               NaN
258   Glenn Maxwell               NaN
365   Glenn Maxwell               NaN
16    Glenn Maxwell               NaN
453   Glenn Maxwell               NaN
110   Glenn Maxwell               NaN
522   Glenn Maxwell               NaN
164  Glenn Phillips               NaN
29   Glenn Phillips               NaN
331  Glenn Phillips               NaN
252  Glenn Phillips               NaN
194  Glenn Phillips               NaN
567  Glenn Phillips               NaN
443  Glenn Phillips               NaN
91   Glenn Phillips               NaN
390  Glenn Phillips               NaN
512  Glenn Phillips               NaN
0               NaN     Aiden Markram
1               NaN      David Miller
3               NaN     Glenn Maxwell
4               NaN  Heinrich Klaasen
5               NaN  Rohit SharmaÂ (c)
6               NaN               NaN

In [9]:
# PARAMETERS
# Batting Average > 15
# Strike Rate > 130
# Innings Batted > 2
# Innings Bowled > 4
# Bowling Economy > 7
# Bowling Strike Rate > 20

In [10]:
df2 = pd.read_csv('final_batting_stats.csv')
df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Abdullah Shafique,8,71.400000,63.433218,336.0,42.000000
1,Adam Zampa,6,75.230000,18.307210,48.0,8.000000
2,Adil Rashid,9,91.631111,33.487762,92.0,10.222222
3,Aiden Markram,8,166.606250,61.245493,304.0,38.000000
4,Aiden MarkramÂ (c),2,91.200000,42.380952,102.0,51.000000
...,...,...,...,...,...,...
146,Usama Mir,1,0.000000,NaN,0.0,0.000000
147,Vikramjit Singh,6,52.366667,45.273504,98.0,16.333333
148,Virat Kohli,11,83.206364,45.102901,765.0,69.545455
149,Wesley Barresi,4,66.167500,31.674357,83.0,20.750000
150,Will Young,6,68.415000,64.010023,206.0,34.333333

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   batsmanName                  151 non-null    object
 1   inning_batted                151 non-null    int64
 2   Average_SR                   151 non-null    float64
 3   Average_Boundary_Percentage  149 non-null    float64
 4   total_runs                   151 non-null    float64
 5   batting_average              151 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [12]:
filtered_df2 = df2[
    (df2['batting_average'] > 15) &
    (df2['Average_SR'] > 127) &
    (df2['inning_batted'] > 2)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Aiden Markram,8,166.606250,61.245493,304.0,38.000000
1,Rohit SharmaÂ (c),11,127.897273,79.805764,597.0,54.272727

In [13]:
df['avg_bowling_economy'] = df.groupby('bowlerName')['economy'].transform('mean')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,Vikramjit Singh,2.0,0,16,0,8.00,5,3,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667
289,Vikramjit Singh,4.0,0,27,0,6.75,13,3,1,1,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667
506,Vikramjit Singh,1.0,0,9,0,9.00,1,1,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667
370,Virat Kohli,0.3,0,2,0,4.00,1,0,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000
46,Virat Kohli,3.0,0,13,1,4.33,10,1,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000

bowling strike rate = avg no of balls required to take a wicket = total run / total wickets

In [14]:
import numpy as np

# Calculate the bowling strike rate and set to 0 if wickets = 0
df['bowling SR'] = np.where(df['wickets'] == 0, 0, (df['overs'] * 6) / df['wickets'])

# Display the updated DataFrame
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,15.0
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,Vikramjit Singh,2.0,0,16,0,8.00,5,3,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0
289,Vikramjit Singh,4.0,0,27,0,6.75,13,3,1,1,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0
506,Vikramjit Singh,1.0,0,9,0,9.00,1,1,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0
370,Virat Kohli,0.3,0,2,0,4.00,1,0,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,0.0
46,Virat Kohli,3.0,0,13,1,4.33,10,1,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,18.0

In [15]:
# Step 1: Filter the DataFrame to exclude rows where economy is 0
filtered_df = df[df['bowling SR'] != 0]

# Step 2: Calculate the average economy for each bowler and add it to the original DataFrame
df['avg_bowling_strike'] = df.groupby('bowlerName')['bowling SR'].transform(lambda x: x[x != 0].mean())

# Display the updated DataFrame
df.head(20)

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,15.0,31.277778
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,12.0,31.277778
112,Adam Zampa,10.0,0,58,1,5.80,22,2,2,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,60.0,31.277778
4,Adam Zampa,10.0,0,44,1,4.40,22,1,0,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,60.0,31.277778
65,Adam Zampa,10.0,0,32,2,3.20,39,2,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,30.0,31.277778
259,Adam Zampa,10.0,0,74,3,7.40,22,6,3,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778
455,Adam Zampa,10.0,0,70,1,7.00,20,9,0,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,60.0,31.277778
296,Adam Zampa,3.0,0,8,4,2.66,10,0,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,4.5,31.277778
58,Adil Rashid,10.0,0,55,2,5.50,26,4,1,1,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143
227,Adil Rashid,10.0,0,35,2,3.50,35,3,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143
418,Adil Rashid,10.0,1,42,3,4.20,29,1,1,1,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,20.0,30.857143
498,Adil Rashid,10.0,0,42,1,4.20,31,1,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,60.0,30.857143
337,Adil Rashid,10.0,0,61,2,6.10,20,4,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143
281,Adil Rashid,4.4,0,39,0,8.35,9,1,3,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,0.0,30.857143
148,Adil Rashid,10.0,0,38,2,3.80,34,1,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143
572,Adil Rashid,7.0,0,47,0,6.71,15,4,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,0.0,30.857143
107,Adil Rashid,8.0,0,54,3,6.75,22,5,2,1,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,16.0,30.857143

In [16]:
import numpy as np

# Calculate the bowling strike rate and set to 0 if wickets = 0
df['bowling_avg'] = np.where(df['wickets'] == 0, 0, (df['runs']) / df['wickets'])

# Display the updated DataFrame
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.00
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778,7.00
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,15.0,31.277778,13.25
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.00
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,12.0,31.277778,11.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,Vikramjit Singh,2.0,0,16,0,8.00,5,3,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00
289,Vikramjit Singh,4.0,0,27,0,6.75,13,3,1,1,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00
506,Vikramjit Singh,1.0,0,9,0,9.00,1,1,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00
370,Virat Kohli,0.3,0,2,0,4.00,1,0,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,0.0,18.000000,0.00
46,Virat Kohli,3.0,0,13,1,4.33,10,1,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,18.0,18.000000,13.00

In [17]:
# Step 1: Filter the DataFrame to exclude rows where bowling_avg is 0
filtered_df = df[df['bowling_avg'] != 0]

# Step 2: Calculate the average bowling_avg for each bowler and add it to the original DataFrame
df['average_bowling_avg'] = df.groupby('bowlerName')['bowling_avg'].transform(lambda x: x[x != 0].mean())

# Display the updated DataFrame
df.head(20)

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.000000,27.407407
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778,7.000000,27.407407
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,15.0,31.277778,13.250000,27.407407
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.000000,27.407407
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,12.0,31.277778,11.750000,27.407407
112,Adam Zampa,10.0,0,58,1,5.80,22,2,2,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,60.0,31.277778,58.000000,27.407407
4,Adam Zampa,10.0,0,44,1,4.40,22,1,0,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,60.0,31.277778,44.000000,27.407407
65,Adam Zampa,10.0,0,32,2,3.20,39,2,1,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,30.0,31.277778,16.000000,27.407407
259,Adam Zampa,10.0,0,74,3,7.40,22,6,3,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778,24.666667,27.407407
455,Adam Zampa,10.0,0,70,1,7.00,20,9,0,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,60.0,31.277778,70.000000,27.407407
296,Adam Zampa,3.0,0,8,4,2.66,10,0,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,4.5,31.277778,2.000000,27.407407
58,Adil Rashid,10.0,0,55,2,5.50,26,4,1,1,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143,27.500000,24.071429
227,Adil Rashid,10.0,0,35,2,3.50,35,3,0,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143,17.500000,24.071429
418,Adil Rashid,10.0,1,42,3,4.20,29,1,1,1,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,20.0,30.857143,14.000000,24.071429
498,Adil Rashid,10.0,0,42,1,4.20,31,1,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,60.0,30.857143,42.000000,24.071429
337,Adil Rashid,10.0,0,61,2,6.10,20,4,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143,30.500000,24.071429
281,Adil Rashid,4.4,0,39,0,8.35,9,1,3,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,0.0,30.857143,0.000000,24.071429
148,Adil Rashid,10.0,0,38,2,3.80,34,1,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,30.0,30.857143,19.000000,24.071429
572,Adil Rashid,7.0,0,47,0,6.71,15,4,1,0,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,0.0,30.857143,0.000000,24.071429
107,Adil Rashid,8.0,0,54,3,6.75,22,5,2,1,0,https://www.espncricinfo.com/cricketers/adil-r...,9,5.456667,16.0,30.857143,18.000000,24.071429

In [18]:
# dot ball percentage
df['dot_ball_percentage'] = ((df['dots']) / (df['overs']*6)) *100
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg,dot_ball_percentage
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.00,27.407407,27.083333
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778,7.00,27.407407,68.333333
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,15.0,31.277778,13.25,27.407407,41.666667
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.00,27.407407,50.000000
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,12.0,31.277778,11.75,27.407407,54.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,Vikramjit Singh,2.0,0,16,0,8.00,5,3,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00,NaN,41.666667
289,Vikramjit Singh,4.0,0,27,0,6.75,13,3,1,1,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00,NaN,54.166667
506,Vikramjit Singh,1.0,0,9,0,9.00,1,1,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00,NaN,16.666667
370,Virat Kohli,0.3,0,2,0,4.00,1,0,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,0.0,18.000000,0.00,13.000000,55.555556
46,Virat Kohli,3.0,0,13,1,4.33,10,1,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,18.0,18.000000,13.00,13.000000,55.555556

In [19]:
df['average_dot_ball_%'] = df.groupby('bowlerName')['dot_ball_percentage'].transform('mean')
df

,bowlerName,overs,maidens,runs,wickets,economy,dots,fours,sixes,wides,no_balls,bowler_link,inningbowled,avg_bowling_economy,bowling SR,avg_bowling_strike,bowling_avg,average_bowling_avg,dot_ball_percentage,average_dot_ball_%
524,Adam Zampa,8.0,0,53,0,6.62,13,4,0,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.00,27.407407,27.083333,45.921717
152,Adam Zampa,10.0,0,21,3,2.10,41,0,0,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,20.0,31.277778,7.00,27.407407,68.333333,45.921717
364,Adam Zampa,10.0,0,53,4,5.30,25,3,1,1,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,15.0,31.277778,13.25,27.407407,41.666667,45.921717
15,Adam Zampa,7.0,0,55,0,7.85,21,1,6,0,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,0.0,31.277778,0.00,27.407407,50.000000,45.921717
407,Adam Zampa,8.0,1,47,4,5.87,26,5,1,2,0,https://www.espncricinfo.com/cricketers/adam-z...,11,5.290909,12.0,31.277778,11.75,27.407407,54.166667,45.921717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,Vikramjit Singh,2.0,0,16,0,8.00,5,3,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00,NaN,41.666667,37.500000
289,Vikramjit Singh,4.0,0,27,0,6.75,13,3,1,1,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00,NaN,54.166667,37.500000
506,Vikramjit Singh,1.0,0,9,0,9.00,1,1,0,0,0,https://www.espncricinfo.com/cricketers/vikram...,3,7.916667,0.0,NaN,0.00,NaN,16.666667,37.500000
370,Virat Kohli,0.3,0,2,0,4.00,1,0,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,0.0,18.000000,0.00,13.000000,55.555556,55.555556
46,Virat Kohli,3.0,0,13,1,4.33,10,1,0,0,0,https://www.espncricinfo.com/cricketers/virat-...,2,4.165000,18.0,18.000000,13.00,13.000000,55.555556,55.555556

In [20]:
df.fillna(0, inplace=True)
df = df.round(2)
df.to_csv('processed_balling_stats.csv', index=False)

In [21]:
df3 = df[['bowlerName', 'inningbowled', 'avg_bowling_economy', 'avg_bowling_strike', 'average_bowling_avg', 'average_dot_ball_%']].copy()
df3.drop_duplicates(inplace=True)
df3
df3.to_csv('final_bowling_stats.csv', index=False)

In [22]:
# Filter the DataFrame based on the given conditions
filtered_df3 = df3[
    (df3['inningbowled'] > 2) & 
    (df3['avg_bowling_economy'] < 7) & 
    (df3['avg_bowling_strike'] < 20) 
]

# Display the filtered DataFrame
filtered_df3

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
182,Angelo Mathews,5,4.92,16.10,13.00,50.93
164,Glenn Phillips,10,5.71,13.67,11.28,39.07
241,Mahedi Hasan,3,6.27,16.50,18.88,47.96
303,Mahmudullah,3,6.55,0.00,0.00,29.63
456,Mitchell Marsh,5,6.85,12.00,9.50,39.17
141,Mohammed Shami,7,5.14,15.11,14.01,63.59
302,Nasum Ahmed,3,6.74,0.00,0.00,41.81
153,Travis Head,5,4.46,15.00,10.50,49.56

In [23]:
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Aiden Markram,8,166.606250,61.245493,304.0,38.000000
1,Rohit SharmaÂ (c),11,127.897273,79.805764,597.0,54.272727

In [24]:
# List of player names to check
players_to_check = filtered_df2['batsmanName'].tolist()

# Check if these names are present in the 'bowlerName' column of filtered_df3
present_players2 = filtered_df3[filtered_df3['bowlerName'].isin(players_to_check)]

# Display the result
present_players2
# Display unique bowler names to verify if players exist

Empty DataFrame
Columns: [bowlerName, inningbowled, avg_bowling_economy, avg_bowling_strike, average_bowling_avg, average_dot_ball_%]
Index: []

In [25]:
selected_players = pd.concat([present_players2['bowlerName'], present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

    bowlerName      bowlerName       batsmanName
137        NaN   Aiden Markram               NaN
75         NaN   Aiden Markram               NaN
263        NaN   Aiden Markram               NaN
20         NaN   Aiden Markram               NaN
2          NaN   Glenn Maxwell      David Warner
406        NaN   Glenn Maxwell               NaN
258        NaN   Glenn Maxwell               NaN
365        NaN   Glenn Maxwell               NaN
16         NaN   Glenn Maxwell               NaN
453        NaN   Glenn Maxwell               NaN
110        NaN   Glenn Maxwell               NaN
522        NaN   Glenn Maxwell               NaN
164        NaN  Glenn Phillips               NaN
29         NaN  Glenn Phillips               NaN
331        NaN  Glenn Phillips               NaN
252        NaN  Glenn Phillips               NaN
194        NaN  Glenn Phillips               NaN
567        NaN  Glenn Phillips               NaN
443        NaN  Glenn Phillips               NaN
91         NaN  Glenn Phillips               NaN
390        NaN  Glenn Phillips               NaN
512        NaN  Glenn Phillips               NaN
0          NaN             NaN     Aiden Markram
1          NaN             NaN      David Miller
3          NaN             NaN     Glenn Maxwell
4          NaN             NaN  Heinrich Klaasen
5          NaN             NaN  Rohit SharmaÂ (c)
6          NaN             NaN               NaN

In [26]:
# Filter the DataFrame based on the given conditions
filtered_df4 = df3[
    (df3['inningbowled'] > 3) & 
    (df3['avg_bowling_economy'] < 8) & 
    (df3['avg_bowling_strike'] < 16) &
    (df3['average_bowling_avg'] < 25) &
    (df3['average_dot_ball_%'] > 40 ) 
]

# Display the filtered DataFrame
filtered_df4

,bowlerName,inningbowled,avg_bowling_economy,avg_bowling_strike,average_bowling_avg,average_dot_ball_%
141,Mohammed Shami,7,5.14,15.11,14.01,63.59
153,Travis Head,5,4.46,15.00,10.50,49.56

In [27]:
selected_players = pd.concat([filtered_df4['bowlerName'],present_players2['bowlerName'], present_players['bowlerName'], selected_players['batsmanName']], axis=1)
selected_players

         bowlerName bowlerName      bowlerName       batsmanName
141  Mohammed Shami        NaN             NaN               NaN
153     Travis Head        NaN             NaN               NaN
137             NaN        NaN   Aiden Markram               NaN
75              NaN        NaN   Aiden Markram               NaN
263             NaN        NaN   Aiden Markram               NaN
20              NaN        NaN   Aiden Markram               NaN
2               NaN        NaN   Glenn Maxwell      David Warner
406             NaN        NaN   Glenn Maxwell               NaN
258             NaN        NaN   Glenn Maxwell               NaN
365             NaN        NaN   Glenn Maxwell               NaN
16              NaN        NaN   Glenn Maxwell               NaN
453             NaN        NaN   Glenn Maxwell               NaN
110             NaN        NaN   Glenn Maxwell               NaN
522             NaN        NaN   Glenn Maxwell               NaN
164             NaN        NaN  Glenn Phillips               NaN
29              NaN        NaN  Glenn Phillips               NaN
331             NaN        NaN  Glenn Phillips               NaN
252             NaN        NaN  Glenn Phillips               NaN
194             NaN        NaN  Glenn Phillips               NaN
567             NaN        NaN  Glenn Phillips               NaN
443             NaN        NaN  Glenn Phillips               NaN
91              NaN        NaN  Glenn Phillips               NaN
390             NaN        NaN  Glenn Phillips               NaN
512             NaN        NaN  Glenn Phillips               NaN
0               NaN        NaN             NaN     Aiden Markram
1               NaN        NaN             NaN      David Miller
3               NaN        NaN             NaN     Glenn Maxwell
4               NaN        NaN             NaN  Heinrich Klaasen
5               NaN        NaN             NaN  Rohit SharmaÂ (c)
6               NaN        NaN             NaN               NaN

In [28]:
# Combine the 'bowlerName' and 'batsmanName' columns, removing NaN values
player_names = selected_players[['bowlerName', 'batsmanName']].stack().dropna().unique()

# Convert to a list if required
player_names_list = list(player_names)

# Print the list of unique player names
player_names_list

['Mohammed Shami',
 'Travis Head',
 'Aiden Markram',
 'Glenn Maxwell',
 'David Warner',
 'Glenn Phillips',
 'David Miller',
 'Heinrich Klaasen',
 'Rohit Sharma\xa0(c)']

In [29]:
df_players = pd.DataFrame(player_names_list, columns=["Player Name"])

# Save the DataFrame to a CSV file
csv_filename = 'final_players_ODI_2024.csv'
df_players.to_csv(csv_filename, index=False)

print(f"Player names saved to {csv_filename}")

Player names saved to final_players_ODI_2024.csv