In [121]:
import pandas as pd

# Filter criteria: (typically for openers)
# 1. Batting Average > 30
# 2. Strike Rate > 140
# 3. Innings Batted >= 3
# 4. Boundary % > 50

In [122]:
file_path = "batting.csv"  
df = pd.read_csv(file_path)
print(df.head())

        batsmanName runs balls minutes 4s 6s      SR  \
0  Rohit Sharma (c)   47    31      44  4  3  151.61
1      Shubman Gill    4     7      21  0  0   57.14
2       Virat Kohli   54    63      99  4  0   85.71
3      Shreyas Iyer    4     3       3  1  0  133.33
4        KL Rahul †   66   107     133  1  0   61.68

                                         player_link   match_id
0  https://www.espncricinfo.com/cricketers/rohit-...  scorecard
1  https://www.espncricinfo.com/cricketers/shubma...  scorecard
2  https://www.espncricinfo.com/cricketers/virat-...  scorecard
3  https://www.espncricinfo.com/cricketers/shreya...  scorecard
4  https://www.espncricinfo.com/cricketers/kl-rah...  scorecard

In [123]:
print(df.dtypes)

batsmanName    object
runs           object
balls          object
minutes        object
4s             object
6s             object
SR             object
player_link    object
match_id       object
dtype: object

In [124]:
df['runs'] = pd.to_numeric(df['runs'], errors='coerce')
df['balls'] = pd.to_numeric(df['balls'], errors='coerce')
df['4s'] = pd.to_numeric(df['4s'], errors='coerce')
df['6s'] = pd.to_numeric(df['6s'], errors='coerce')
df['SR'] = pd.to_numeric(df['SR'], errors='coerce')

In [125]:
df = df.drop(columns=['match_id'])
print(df.head())

        batsmanName  runs  balls minutes   4s   6s      SR  \
0  Rohit Sharma (c)  47.0   31.0      44  4.0  3.0  151.61
1      Shubman Gill   4.0    7.0      21  0.0  0.0   57.14
2       Virat Kohli  54.0   63.0      99  4.0  0.0   85.71
3      Shreyas Iyer   4.0    3.0       3  1.0  0.0  133.33
4        KL Rahul †  66.0  107.0     133  1.0  0.0   61.68

                                         player_link
0  https://www.espncricinfo.com/cricketers/rohit-...
1  https://www.espncricinfo.com/cricketers/shubma...
2  https://www.espncricinfo.com/cricketers/virat-...
3  https://www.espncricinfo.com/cricketers/shreya...
4  https://www.espncricinfo.com/cricketers/kl-rah...

In [126]:
df = df.sort_values(by='batsmanName')

print(df)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
82   Abdullah Shafique    0.0    2.0       2   0.0  0.0    0.00
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link
740  https://www.espncricinfo.com/cricketers/abdull...
82   https://www.espncricinfo.com/cricketers/abdull...
402  https://www.espncricinfo.com/cricketers/abdull...
558  https://www.espncricinfo.com/cricketers/abdull...
664  https://www.espncricinfo.com/cricketers/abdull...
..                                                 ...
392  https://www.espncricinfo.com/cricketers/will-y...
585  https://www.espncricinfo.com/cricketers/will-y...
769  https://www.espncricinfo.com/cricketers/will-y...
491  https://www.espncricinfo.com/cricketers/will-y...
295  https://www.espncricinfo.com/cricketers/will-y...

[876 rows x 8 columns]

In [127]:
df.describe()

             runs       balls          4s          6s          SR
count  875.000000  875.000000  875.000000  875.000000  871.000000
mean    26.773714   29.090286    2.558857    0.736000   83.151458
std     31.018840   28.579166    3.148084    1.490633   52.930719
min      0.000000    0.000000    0.000000    0.000000    0.000000
25%      5.000000    8.000000    0.000000    0.000000   50.000000
50%     15.000000   19.000000    1.000000    0.000000   80.760000
75%     39.000000   40.500000    4.000000    1.000000  106.900000
max    201.000000  143.000000   21.000000   11.000000  600.000000

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 876 entries, 740 to 295
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   batsmanName  876 non-null    object
 1   runs         875 non-null    float64
 2   balls        875 non-null    float64
 3   minutes      876 non-null    object
 4   4s           875 non-null    float64
 5   6s           875 non-null    float64
 6   SR           871 non-null    float64
 7   player_link  876 non-null    object
dtypes: float64(5), object(3)
memory usage: 61.6+ KB

In [129]:
name_counts = df['batsmanName'].value_counts()

# Step 2: Add a new column to the DataFrame that shows how many times each player appears
df['inning_batted'] = df['batsmanName'].map(name_counts)

# Step 3: Display the updated DataFrame
print(df)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
82   Abdullah Shafique    0.0    2.0       2   0.0  0.0    0.00
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link  inning_batted
740  https://www.espncricinfo.com/cricketers/abdull...              8
82   https://www.espncricinfo.com/cricketers/abdull...              8
402  https://www.espncricinfo.com/cricketers/abdull...              8
558  https://www.espncricinfo.com/cricketers/abdull...              8
664  https://www.espncricinfo.com/cricketers/abdull...              8
..                                                 ...            ...
392  https://www.espncricinfo.com/cricketers/will-y...              6
585  https://www.espncricinfo.com/cricketers/will-y...              6
769  https://www.espncricinfo.com/cricketers/will-y...              6
491  https://www.espncricinfo.com/cricketers/will-y...              6
295  https://www.espncricinfo.com/cricketers/will-y...              6

[876 rows x 9 columns]

In [130]:
print(df)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
82   Abdullah Shafique    0.0    2.0       2   0.0  0.0    0.00
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link  inning_batted
740  https://www.espncricinfo.com/cricketers/abdull...              8
82   https://www.espncricinfo.com/cricketers/abdull...              8
402  https://www.espncricinfo.com/cricketers/abdull...              8
558  https://www.espncricinfo.com/cricketers/abdull...              8
664  https://www.espncricinfo.com/cricketers/abdull...              8
..                                                 ...            ...
392  https://www.espncricinfo.com/cricketers/will-y...              6
585  https://www.espncricinfo.com/cricketers/will-y...              6
769  https://www.espncricinfo.com/cricketers/will-y...              6
491  https://www.espncricinfo.com/cricketers/will-y...              6
295  https://www.espncricinfo.com/cricketers/will-y...              6

[876 rows x 9 columns]

In [131]:
df['SR'] = pd.to_numeric(df['SR'], errors='coerce')

df_cleaned = df[(df['SR'] != 0) & (df['SR'].notna())]

print(df_cleaned)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
316  Abdullah Shafique   68.0   69.0      94   9.0  2.0   98.55
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link  inning_batted
740  https://www.espncricinfo.com/cricketers/abdull...              8
402  https://www.espncricinfo.com/cricketers/abdull...              8
558  https://www.espncricinfo.com/cricketers/abdull...              8
664  https://www.espncricinfo.com/cricketers/abdull...              8
316  https://www.espncricinfo.com/cricketers/abdull...              8
..                                                 ...            ...
392  https://www.espncricinfo.com/cricketers/will-y...              6
585  https://www.espncricinfo.com/cricketers/will-y...              6
769  https://www.espncricinfo.com/cricketers/will-y...              6
491  https://www.espncricinfo.com/cricketers/will-y...              6
295  https://www.espncricinfo.com/cricketers/will-y...              6

[798 rows x 9 columns]

In [132]:
df['SR'] = pd.to_numeric(df['SR'], errors='coerce').fillna(0)

df['Average_SR'] = df.groupby('batsmanName')['SR'].transform('mean')
df

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR
740,Abdullah Shafique,113.0,103.0,150,10.0,3.0,109.70,https://www.espncricinfo.com/cricketers/abdull...,8,71.400
82,Abdullah Shafique,0.0,2.0,2,0.0,0.0,0.00,https://www.espncricinfo.com/cricketers/abdull...,8,71.400
402,Abdullah Shafique,9.0,17.0,21,1.0,0.0,52.94,https://www.espncricinfo.com/cricketers/abdull...,8,71.400
558,Abdullah Shafique,64.0,61.0,93,7.0,2.0,104.91,https://www.espncricinfo.com/cricketers/abdull...,8,71.400
664,Abdullah Shafique,20.0,24.0,39,3.0,0.0,83.33,https://www.espncricinfo.com/cricketers/abdull...,8,71.400
...,...,...,...,...,...,...,...,...,...,...
392,Will Young,32.0,37.0,44,4.0,1.0,86.48,https://www.espncricinfo.com/cricketers/will-y...,6,68.415
585,Will Young,54.0,64.0,98,4.0,3.0,84.37,https://www.espncricinfo.com/cricketers/will-y...,6,68.415
769,Will Young,70.0,80.0,106,7.0,2.0,87.50,https://www.espncricinfo.com/cricketers/will-y...,6,68.415
491,Will Young,17.0,27.0,41,3.0,0.0,62.96,https://www.espncricinfo.com/cricketers/will-y...,6,68.415
295,Will Young,33.0,37.0,50,5.0,0.0,89.18,https://www.espncricinfo.com/cricketers/will-y...,6,68.415

In [133]:
df['boundaries'] = df['4s'] + df['6s']

print(df)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
82   Abdullah Shafique    0.0    2.0       2   0.0  0.0    0.00
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link  inning_batted  \
740  https://www.espncricinfo.com/cricketers/abdull...              8
82   https://www.espncricinfo.com/cricketers/abdull...              8
402  https://www.espncricinfo.com/cricketers/abdull...              8
558  https://www.espncricinfo.com/cricketers/abdull...              8
664  https://www.espncricinfo.com/cricketers/abdull...              8
..                                                 ...            ...
392  https://www.espncricinfo.com/cricketers/will-y...              6
585  https://www.espncricinfo.com/cricketers/will-y...              6
769  https://www.espncricinfo.com/cricketers/will-y...              6
491  https://www.espncricinfo.com/cricketers/will-y...              6
295  https://www.espncricinfo.com/cricketers/will-y...              6

     Average_SR  boundaries
740      71.400        13.0
82       71.400         0.0
402      71.400         1.0
558      71.400         9.0
664      71.400         3.0
..          ...         ...
392      68.415         5.0
585      68.415         7.0
769      68.415         9.0
491      68.415         3.0
295      68.415         5.0

[876 rows x 11 columns]

In [134]:
df['boundary_runs'] = (df['4s'] * 4) + (df['6s'] * 6)

df

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs
740,Abdullah Shafique,113.0,103.0,150,10.0,3.0,109.70,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,13.0,58.0
82,Abdullah Shafique,0.0,2.0,2,0.0,0.0,0.00,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,0.0,0.0
402,Abdullah Shafique,9.0,17.0,21,1.0,0.0,52.94,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,1.0,4.0
558,Abdullah Shafique,64.0,61.0,93,7.0,2.0,104.91,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,9.0,40.0
664,Abdullah Shafique,20.0,24.0,39,3.0,0.0,83.33,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,3.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
392,Will Young,32.0,37.0,44,4.0,1.0,86.48,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,5.0,22.0
585,Will Young,54.0,64.0,98,4.0,3.0,84.37,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,7.0,34.0
769,Will Young,70.0,80.0,106,7.0,2.0,87.50,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,9.0,40.0
491,Will Young,17.0,27.0,41,3.0,0.0,62.96,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,3.0,12.0
295,Will Young,33.0,37.0,50,5.0,0.0,89.18,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,5.0,20.0

In [135]:
df

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs
740,Abdullah Shafique,113.0,103.0,150,10.0,3.0,109.70,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,13.0,58.0
82,Abdullah Shafique,0.0,2.0,2,0.0,0.0,0.00,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,0.0,0.0
402,Abdullah Shafique,9.0,17.0,21,1.0,0.0,52.94,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,1.0,4.0
558,Abdullah Shafique,64.0,61.0,93,7.0,2.0,104.91,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,9.0,40.0
664,Abdullah Shafique,20.0,24.0,39,3.0,0.0,83.33,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,3.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...
392,Will Young,32.0,37.0,44,4.0,1.0,86.48,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,5.0,22.0
585,Will Young,54.0,64.0,98,4.0,3.0,84.37,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,7.0,34.0
769,Will Young,70.0,80.0,106,7.0,2.0,87.50,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,9.0,40.0
491,Will Young,17.0,27.0,41,3.0,0.0,62.96,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,3.0,12.0
295,Will Young,33.0,37.0,50,5.0,0.0,89.18,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,5.0,20.0

In [136]:

df['boundary_percentage'] = (df['boundary_runs'] / df['runs']) * 100

print(df)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
82   Abdullah Shafique    0.0    2.0       2   0.0  0.0    0.00
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link  inning_batted  \
740  https://www.espncricinfo.com/cricketers/abdull...              8
82   https://www.espncricinfo.com/cricketers/abdull...              8
402  https://www.espncricinfo.com/cricketers/abdull...              8
558  https://www.espncricinfo.com/cricketers/abdull...              8
664  https://www.espncricinfo.com/cricketers/abdull...              8
..                                                 ...            ...
392  https://www.espncricinfo.com/cricketers/will-y...              6
585  https://www.espncricinfo.com/cricketers/will-y...              6
769  https://www.espncricinfo.com/cricketers/will-y...              6
491  https://www.espncricinfo.com/cricketers/will-y...              6
295  https://www.espncricinfo.com/cricketers/will-y...              6

     Average_SR  boundaries  boundary_runs  boundary_percentage
740      71.400        13.0           58.0            51.327434
82       71.400         0.0            0.0                  NaN
402      71.400         1.0            4.0            44.444444
558      71.400         9.0           40.0            62.500000
664      71.400         3.0           12.0            60.000000
..          ...         ...            ...                  ...
392      68.415         5.0           22.0            68.750000
585      68.415         7.0           34.0            62.962963
769      68.415         9.0           40.0            57.142857
491      68.415         3.0           12.0            70.588235
295      68.415         5.0           20.0            60.606061

[876 rows x 13 columns]

In [137]:
df['Average_Boundary_Percentage'] = df.groupby('batsmanName')['boundary_percentage'].transform('mean')

df

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs,boundary_percentage,Average_Boundary_Percentage
740,Abdullah Shafique,113.0,103.0,150,10.0,3.0,109.70,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,13.0,58.0,51.327434,63.433218
82,Abdullah Shafique,0.0,2.0,2,0.0,0.0,0.00,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,0.0,0.0,NaN,63.433218
402,Abdullah Shafique,9.0,17.0,21,1.0,0.0,52.94,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,1.0,4.0,44.444444,63.433218
558,Abdullah Shafique,64.0,61.0,93,7.0,2.0,104.91,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,9.0,40.0,62.500000,63.433218
664,Abdullah Shafique,20.0,24.0,39,3.0,0.0,83.33,https://www.espncricinfo.com/cricketers/abdull...,8,71.400,3.0,12.0,60.000000,63.433218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,Will Young,32.0,37.0,44,4.0,1.0,86.48,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,5.0,22.0,68.750000,64.010023
585,Will Young,54.0,64.0,98,4.0,3.0,84.37,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,7.0,34.0,62.962963,64.010023
769,Will Young,70.0,80.0,106,7.0,2.0,87.50,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,9.0,40.0,57.142857,64.010023
491,Will Young,17.0,27.0,41,3.0,0.0,62.96,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,3.0,12.0,70.588235,64.010023
295,Will Young,33.0,37.0,50,5.0,0.0,89.18,https://www.espncricinfo.com/cricketers/will-y...,6,68.415,5.0,20.0,60.606061,64.010023

In [138]:
df['total_runs'] = df.groupby('batsmanName')['runs'].transform('sum')
df['inning_batted'] = df.groupby('batsmanName')['inning_batted'].transform('count')

# Step 2: Calculate batting average for each player and add it to the DataFrame
df['batting_average'] = df['total_runs'] / df['inning_batted']

# Step 3: Display the updated DataFrame with batting averages and other columns
print(df)

           batsmanName   runs  balls minutes    4s   6s      SR  \
740  Abdullah Shafique  113.0  103.0     150  10.0  3.0  109.70
82   Abdullah Shafique    0.0    2.0       2   0.0  0.0    0.00
402  Abdullah Shafique    9.0   17.0      21   1.0  0.0   52.94
558  Abdullah Shafique   64.0   61.0      93   7.0  2.0  104.91
664  Abdullah Shafique   20.0   24.0      39   3.0  0.0   83.33
..                 ...    ...    ...     ...   ...  ...     ...
392         Will Young   32.0   37.0      44   4.0  1.0   86.48
585         Will Young   54.0   64.0      98   4.0  3.0   84.37
769         Will Young   70.0   80.0     106   7.0  2.0   87.50
491         Will Young   17.0   27.0      41   3.0  0.0   62.96
295         Will Young   33.0   37.0      50   5.0  0.0   89.18

                                           player_link  inning_batted  \
740  https://www.espncricinfo.com/cricketers/abdull...              8
82   https://www.espncricinfo.com/cricketers/abdull...              8
402  https://www.espncricinfo.com/cricketers/abdull...              8
558  https://www.espncricinfo.com/cricketers/abdull...              8
664  https://www.espncricinfo.com/cricketers/abdull...              8
..                                                 ...            ...
392  https://www.espncricinfo.com/cricketers/will-y...              6
585  https://www.espncricinfo.com/cricketers/will-y...              6
769  https://www.espncricinfo.com/cricketers/will-y...              6
491  https://www.espncricinfo.com/cricketers/will-y...              6
295  https://www.espncricinfo.com/cricketers/will-y...              6

     Average_SR  boundaries  boundary_runs  boundary_percentage  \
740      71.400        13.0           58.0            51.327434
82       71.400         0.0            0.0                  NaN
402      71.400         1.0            4.0            44.444444
558      71.400         9.0           40.0            62.500000
664      71.400         3.0           12.0            60.000000
..          ...         ...            ...                  ...
392      68.415         5.0           22.0            68.750000
585      68.415         7.0           34.0            62.962963
769      68.415         9.0           40.0            57.142857
491      68.415         3.0           12.0            70.588235
295      68.415         5.0           20.0            60.606061

     Average_Boundary_Percentage  total_runs  batting_average
740                    63.433218       336.0        42.000000
82                     63.433218       336.0        42.000000
402                    63.433218       336.0        42.000000
558                    63.433218       336.0        42.000000
664                    63.433218       336.0        42.000000
..                           ...         ...              ...
392                    64.010023       206.0        34.333333
585                    64.010023       206.0        34.333333
769                    64.010023       206.0        34.333333
491                    64.010023       206.0        34.333333
295                    64.010023       206.0        34.333333

[876 rows x 16 columns]

In [139]:
df.to_csv('processed_batting_stats.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [140]:
columns_to_keep = ['batsmanName', 'inning_batted', 'Average_SR', 'Average_Boundary_Percentage', 'total_runs', 'batting_average']

# Create the new DataFrame with the specified columns
df2 = df[columns_to_keep]

# Display the new DataFrame
df2.head()

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
740,Abdullah Shafique,8,71.4,63.433218,336.0,42.0
82,Abdullah Shafique,8,71.4,63.433218,336.0,42.0
402,Abdullah Shafique,8,71.4,63.433218,336.0,42.0
558,Abdullah Shafique,8,71.4,63.433218,336.0,42.0
664,Abdullah Shafique,8,71.4,63.433218,336.0,42.0

In [141]:
# Removing duplicate rows from the DataFrame
df2 = df2.drop_duplicates()

# Display the updated DataFrame
print(df2)

           batsmanName  inning_batted  Average_SR  \
740  Abdullah Shafique              8   71.400000
228         Adam Zampa              6   75.230000
433        Adil Rashid              9   91.631111
808      Aiden Markram              8  166.606250
512  Aiden Markram (c)              2   91.200000
..                 ...            ...         ...
565          Usama Mir              1    0.000000
851    Vikramjit Singh              6   52.366667
339        Virat Kohli             11   83.206364
154     Wesley Barresi              4   66.167500
874         Will Young              6   68.415000

     Average_Boundary_Percentage  total_runs  batting_average
740                    63.433218       336.0        42.000000
228                    18.307210        48.0         8.000000
433                    33.487762        92.0        10.222222
808                    61.245493       304.0        38.000000
512                    42.380952       102.0        51.000000
..                           ...         ...              ...
565                          NaN         0.0         0.000000
851                    45.273504        98.0        16.333333
339                    45.102901       765.0        69.545455
154                    31.674357        83.0        20.750000
874                    64.010023       206.0        34.333333

[151 rows x 6 columns]

In [142]:
df2.to_csv('final_batting_stats.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [143]:
# for openers
filtered_df2 = df2[
    (df2['batting_average'] > 30) &
    (df2['Average_SR'] >140) &
    (df2['inning_batted'] > 3) &
    (df2['Average_Boundary_Percentage'] > 50)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average
0,Aiden Markram,8,166.60625,61.245493,304.0,38.0

In [144]:
selected_players = filtered_df2['batsmanName']
selected_players

0    Aiden Markram
Name: batsmanName, dtype: object

# Filter criteria: (typically for middle order)
# Batting Average > 40
# Strike Rate > 125
# Innings Batted > 3
# Average balls faced by the batter in an innings> 20

In [145]:
df['total_balls'] = df.groupby('batsmanName')['balls'].transform('sum')

df['innings_played'] = df.groupby('batsmanName')['inning_batted'].transform('count')
df['balls_avg'] = df['total_balls'] / df['innings_played']
df.head(10)

,batsmanName,runs,balls,minutes,4s,6s,SR,player_link,inning_batted,Average_SR,boundaries,boundary_runs,boundary_percentage,Average_Boundary_Percentage,total_runs,batting_average,total_balls,innings_played,balls_avg
740,Abdullah Shafique,113.0,103.0,150,10.0,3.0,109.70,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,13.0,58.0,51.327434,63.433218,336.0,42.0,360.0,8,45.0
82,Abdullah Shafique,0.0,2.0,2,0.0,0.0,0.00,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,0.0,0.0,NaN,63.433218,336.0,42.0,360.0,8,45.0
402,Abdullah Shafique,9.0,17.0,21,1.0,0.0,52.94,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,1.0,4.0,44.444444,63.433218,336.0,42.0,360.0,8,45.0
558,Abdullah Shafique,64.0,61.0,93,7.0,2.0,104.91,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,9.0,40.0,62.500000,63.433218,336.0,42.0,360.0,8,45.0
664,Abdullah Shafique,20.0,24.0,39,3.0,0.0,83.33,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,3.0,12.0,60.000000,63.433218,336.0,42.0,360.0,8,45.0
316,Abdullah Shafique,68.0,69.0,94,9.0,2.0,98.55,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,11.0,48.0,70.588235,63.433218,336.0,42.0,360.0,8,45.0
478,Abdullah Shafique,58.0,75.0,89,5.0,2.0,77.33,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,7.0,32.0,55.172414,63.433218,336.0,42.0,360.0,8,45.0
249,Abdullah Shafique,4.0,9.0,8,1.0,0.0,44.44,https://www.espncricinfo.com/cricketers/abdull...,8,71.40,1.0,4.0,100.000000,63.433218,336.0,42.0,360.0,8,45.0
228,Adam Zampa,29.0,19.0,23,4.0,0.0,152.63,https://www.espncricinfo.com/cricketers/adam-z...,6,75.23,4.0,16.0,55.172414,18.307210,48.0,8.0,60.0,6,10.0
389,Adam Zampa,0.0,3.0,2,0.0,0.0,0.00,https://www.espncricinfo.com/cricketers/adam-z...,6,75.23,0.0,0.0,NaN,18.307210,48.0,8.0,60.0,6,10.0

In [146]:
# Merge df2 with df to add the balls_avg column
df2 = df2.merge(df[['batsmanName', 'balls_avg']], on='batsmanName', how='left')

# Display the updated df2
print(df2)

           batsmanName  inning_batted  Average_SR  \
0    Abdullah Shafique              8      71.400
1    Abdullah Shafique              8      71.400
2    Abdullah Shafique              8      71.400
3    Abdullah Shafique              8      71.400
4    Abdullah Shafique              8      71.400
..                 ...            ...         ...
871         Will Young              6      68.415
872         Will Young              6      68.415
873         Will Young              6      68.415
874         Will Young              6      68.415
875         Will Young              6      68.415

     Average_Boundary_Percentage  total_runs  batting_average  balls_avg
0                      63.433218       336.0        42.000000       45.0
1                      63.433218       336.0        42.000000       45.0
2                      63.433218       336.0        42.000000       45.0
3                      63.433218       336.0        42.000000       45.0
4                      63.433218       336.0        42.000000       45.0
..                           ...         ...              ...        ...
871                    64.010023       206.0        34.333333       41.0
872                    64.010023       206.0        34.333333       41.0
873                    64.010023       206.0        34.333333       41.0
874                    64.010023       206.0        34.333333       41.0
875                    64.010023       206.0        34.333333       41.0

[876 rows x 7 columns]

In [147]:
# Removing duplicate rows from the DataFrame
df2 = df2.drop_duplicates()

# Display the updated DataFrame
print(df2)

           batsmanName  inning_batted  Average_SR  \
0    Abdullah Shafique              8   71.400000
8           Adam Zampa              6   75.230000
14         Adil Rashid              9   91.631111
23       Aiden Markram              8  166.606250
31   Aiden Markram (c)              2   91.200000
..                 ...            ...         ...
848          Usama Mir              1    0.000000
849    Vikramjit Singh              6   52.366667
855        Virat Kohli             11   83.206364
866     Wesley Barresi              4   66.167500
870         Will Young              6   68.415000

     Average_Boundary_Percentage  total_runs  batting_average  balls_avg
0                      63.433218       336.0        42.000000  45.000000
8                      18.307210        48.0         8.000000  10.000000
14                     33.487762        92.0        10.222222  10.111111
23                     61.245493       304.0        38.000000  31.625000
31                     42.380952       102.0        51.000000  56.500000
..                           ...         ...              ...        ...
848                          NaN         0.0         0.000000   3.000000
849                    45.273504        98.0        16.333333  25.000000
855                    45.102901       765.0        69.545455  77.000000
866                    31.674357        83.0        20.750000  28.000000
870                    64.010023       206.0        34.333333  41.000000

[151 rows x 7 columns]

In [148]:

filtered_df2 = df2[
    (df2['batting_average'] > 35) &
    (df2['Average_SR'] > 110) &
    (df2['inning_batted'] > 3) &
    (df2['balls_avg'] > 20)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average,balls_avg
0,Aiden Markram,8,166.606250,61.245493,304.0,38.000000,31.625000
1,David Miller,10,123.346000,63.900068,356.0,35.600000,33.000000
2,David Warner,11,119.574545,63.924299,535.0,48.636364,44.909091
3,Glenn Maxwell,9,112.667778,43.240638,400.0,44.444444,29.555556
4,Heinrich Klaasen,10,123.195000,51.179057,373.0,37.300000,28.000000
5,Rohit Sharma (c),11,127.897273,79.805764,597.0,54.272727,43.090909

In [149]:
combined_df = pd.concat([filtered_df2, selected_players])
combined_df.to_csv('selected_players.csv', index=False)

c:\Users\kiran\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

# Filter criteria: (typically for lower order)
# Batting Average > 25
# Strike Rate > 130
# Innings Batted > 3
# Average balls faced by the batter in an innings> 12
# Innings Bowled > 1

In [150]:

filtered_df2 = df2[
    (df2['batting_average'] > 25) &
    (df2['Average_SR'] > 110) &
    (df2['inning_batted'] > 3) &
    (df2['balls_avg'] > 12)
]

filtered_df2.reset_index(drop=True, inplace=True)
filtered_df2.to_csv('temp.csv', index=False)
filtered_df2

,batsmanName,inning_batted,Average_SR,Average_Boundary_Percentage,total_runs,batting_average,balls_avg
0,Aiden Markram,8,166.606250,61.245493,304.0,38.000000,31.625000
1,David Miller,10,123.346000,63.900068,356.0,35.600000,33.000000
2,David Warner,11,119.574545,63.924299,535.0,48.636364,44.909091
3,Glenn Maxwell,9,112.667778,43.240638,400.0,44.444444,29.555556
4,Glenn Phillips,9,119.544444,61.344287,285.0,31.666667,28.333333
5,Harry Brook,6,118.498333,70.210339,169.0,28.166667,25.000000
6,Heinrich Klaasen,10,123.195000,51.179057,373.0,37.300000,28.000000
7,Rohit Sharma (c),11,127.897273,79.805764,597.0,54.272727,43.090909
8,Towhid Hridoy,6,117.153333,38.245058,164.0,27.333333,35.000000